### ISSUE TITLE
License

### ISSUE THREAD

**Issue by justmiles** [phillbaker/terraform-provider-elasticsearch#1]
Could you attach a license to this repo? It looks like [Terraform's license](https://github.com/hashicorp/terraform/blob/master/LICENSE) is MPL 2.0. I'm not certain that's what you'd need or want - just throwing it out there. I'd like to use/contribute to this but can't until it has a license.

**Comment by phillbaker** [comment]
Whoops, thanks @justmiles, 70a3502 should address this issue (MPL 2.0) and should cover the original contributions from @vrcsix as well.

@vrcsix please let us know if this doesn't make sense.

**Comment by phillbaker** [comment]
Closing as added a license and haven't heard any objections.
