### ISSUE TITLE
elastic: Error 400 (Bad Request): property isn't a map

### ISSUE THREAD

**Issue by MIsazaB95** [phillbaker/terraform-provider-elasticsearch#104]
Can´t create my own custom ingest pipelines..
I´m trying to create y own processor called docs, but when i do terraform apply does not work:

elastic: Error 400 (Bad Request): No processor type exists with name [docs] [type=parse_exception]

**Comment by phillbaker** [comment]
Please include a redacted copy of the terraform config that you're using.

**Comment by MIsazaB95** [comment]
This is the resource to create the ingest pipeline
```
resource "elasticsearch_ingest_pipeline" "ingest_dotnet_pipeline" {
  name  = "dotnet"
  body  = file("${path.module}/ingest_pipeline_dotnet.json")
}
```
The boy of my pipeline is this:
```
{
  "description": "Dotnet pipeline",
  "processors": [
    {
      "grok": {
        "field": "message",
        "patterns": [
          "%{TIMESTAMP_ISO8601:app.logtime}%{SPACE}\\[%{DOTNETLOGLEVEL:app.loglevel}\\]%{SPACE}\\(%{DOTNETAPP:app.name}/%{DOTNEMACHINE:app.machine}/%{DOTNETTHREAD:app.thread}\\)%{SPACE}%{MLMSG:app.message}"
        ],
        "pattern_definitions": {
          "THREAD": "([A-Za-z0-9-]| )+",
          "DOTNETLOGLEVEL": "([A-Za-z0-9-]| )+",
          "DOTNETAPP": "[A-Za-z0-9-]+",
          "DOTNEMACHINE": "[A-Za-z0-9-]+",
          "DOTNETTHREAD": "[A-Za-z0-9-]+",
          "NONEMPTY": "\\S+",
          "MLMSG": "(.|\n)*"
        }
      }
    },
    {
      "remove": {
        "field": "message"
      }
    },
      {
        "docs": {
          "0": {
            "_source": {
              "message": "2020-09-16T20:47:24.5088988+00:00 [ERR] (sso-server/null/83) Invalid reference token."
            }
          }
        }
      }
    }
  ]
}
 ```
But, when i do a tf apply, it says that docs is not a valid proccessor type

**Comment by phillbaker** [comment]
Is this pipeline valid when using the simulate endpoint in elasticsearch (https://www.elastic.co/guide/en/elasticsearch/reference/6.8/simulate-pipeline-api.html)? Ie using `POST _ingest/pipeline/_simulate`?

**Comment by phillbaker** [comment]
In fact the body that you're using is the body to the simulate endpoint, not one that's for creating pipelines. Please see https://www.elastic.co/guide/en/elasticsearch/reference/6.8/put-pipeline-api.html and the example here: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/ae280f3de1eb5006c0bda94e91fe3a91156b73f8/examples/ingest_pipeline/main.tf#L7-L30
