### ISSUE TITLE
kibana object always fails if index does not exist

### ISSUE THREAD

**Issue by nothingofuse** [phillbaker/terraform-provider-elasticsearch#106]
i believe theres a simple bug in this conditional - https://github.com/phillbaker/terraform-provider-elasticsearch/blob/e9f5b3b12816c6b0fe98440cc836c10bca0e080e/es/resource_elasticsearch_kibana_object.go#L126

if it tries to create the .kibana index; it always returns err

**Comment by phillbaker** [comment]
What are the cases when `createIndex.Acknowledged` is true, but an err is also returned?

https://github.com/phillbaker/terraform-provider-elasticsearch/blob/e9f5b3b12816c6b0fe98440cc836c10bca0e080e/es/resource_elasticsearch_kibana_object.go#L124-L127

**Comment by phillbaker** [comment]
Hi @nothingofuse can you provide an update regarding the question above or provide a test case where the index fails? Please also clarify the version of terrraform, provider and ES version where you are seeing this.

**Comment by phillbaker** [comment]
I'm closing this issue for now since no further details have been provided. If you can help write a test case or provide additional details, please reopen the issue.
