### ISSUE TITLE
Kibana index patterns don't work

### ISSUE THREAD

**Issue by tjbaker** [phillbaker/terraform-provider-elasticsearch#108]
You can create a Kibana index pattern via the provider, but it does not contain enough metadata to be displayed or edited in Kibana 7.8.0.  You can export all the index patterns and see your data there, but you can not view/edit it via the index pattern UI, which throws a 404 for the index id.

ie
I see this in the ndjson export
```
{"attributes":{"timeFieldName":"@timestamp","title":"cwl-foo-2020.11*"},"id":"test","references":[],"type":"index-pattern","version":"WzIyMCwxXQ=="}
```

But the response when I try to load the index pattern in Kibaba is

```
{"saved_objects":[{"id":"test","type":"index-pattern","error":{"statusCode":404,"error":"Not Found","message":"Saved object [index-pattern/test] not found"}}]}
```

I can see it in the filtered list of index patterns in the Kibana UI, but can not interact with it due to the 404 above.

```
/// variables ///
variable index_patterns {
  description = "Map of index patterns."
  type        = map
  default     = {
    test = {
      index_pattern  = "cwl-foo-2020.11*",
      time_field = "@timestamp"
    }
  }
}

/// main ///
terraform {
  required_providers {
    elasticsearch = {
      source = "phillbaker/elasticsearch"
      version = ">1.5.0"
    }
  }
}

provider "elasticsearch" {
  url = "https://xxx.yyy.com"
}

module "index_patterns" {
  source = "./modules/index_pattern"

  for_each = var.index_patterns

  id = each.key
  index_pattern = each.value.index_pattern
  time_field = each.value.time_field
}


/// module ///
terraform {
  required_providers {
    elasticsearch = {
      source = "phillbaker/elasticsearch"
      version = ">=1.5.0"
    }
  }
}

resource "elasticsearch_kibana_object" "index_pattern" {
  body = <<EOF
[{
  "_id": "${var.id}",
  "_type": "doc",
  "_source": {
    "type": "index-pattern",
    "index-pattern": {
      "title": "${var.index_pattern}",
      "timeFieldName": "${var.time_field}"
    }
  }
}]
EOF
}

```

**Comment by tjbaker** [comment]
hmmm, somehow it does not like patterns named `test` but is fine with `test1`.

test1 is working as expect
test shows in the ui and export, but I can not interact with it via tf or the api, it keeps throwing 404 even though the pattern mgmt UI shows it

**Comment by tjbaker** [comment]
arg, I can't get rid of the test doc/pattern

In sql workbench I can find it via 
`select * from .kibana_4 where type = 'index-pattern' and updated_at IS NULL;`

There is just one row, and it is the one in question.  But this also fails
`delete from .kibana_4 where type = 'index-pattern' and updated_at IS NULL;`

**Comment by tjbaker** [comment]
I was able to delete the offending index-pattern and will continue testing.

**Comment by tjbaker** [comment]
IDK how the above happened, but I did manage to create an invalid index pattern which would display in the UI but could not be interacted with, often throwing a 404.  I had to delete it manually via curl in the kibana index.  I have not been able to reproduce the issue though.

**Comment by phillbaker** [comment]
I'm going to close this for now, please re-open if the test case above is reproducible.

**Comment by petrukngantuk** [comment]
hello @phillbaker @tjbaker , I experience this case, but already fixed with json example you mentioned above,
but I experienced strange error,
the index pattern showed up in the kibana dashboard, but when I click it, it didn't go to the details,
check in the inspect element, got error like this :

```
{statusCode: 400, error: "Bad Request", message: "Bad Request",…}
attributes: {objects: [{id: "fluentd-us-west-2-eks-dev-001", type: "index-pattern",…}]}
objects: [{id: "fluentd-us-west-2-eks-dev-001", type: "index-pattern",…}]
0: {id: "fluentd-us-west-2-eks-dev-001", type: "index-pattern",…}
error: {statusCode: 404, message: "Not found"}
message: "Not found"
statusCode: 404
id: "fluentd-us-west-2-eks-dev-001"
type: "index-pattern"
error: "Bad Request"
message: "Bad Request"
statusCode: 400
```

but when I created the same config from kibana dashboard directly it's working as expected, is there a thing that I missing somewhere?

attached :
`index-pattern.json`
```
[
  {
    "_id": "${name}",
    "_type": "doc",
    "_source": {
      "type": "index-pattern",
      "index-pattern": {
        "title": "${index_patterns}",
        "timeFieldName": "@timestamp"
      },
      "migrationVersion": {
        "index-pattern": "7.6.0"
      }
    }
  }
]
```

`tf code`

```
resource "elasticsearch_kibana_object" "fluentd" {
  body = templatefile("${path.module}/kibana/index-pattern.json", {
    name = local.name
    index_patterns = local.index_patterns
  })

  depends_on = [helm_release.fluentd]
}
```

any insight?
I tried to show my index-pattern that sended from kubernetes cluster, deployed with [this helm chart](https://github.com/kokuwaio/helm-charts/tree/main/charts/fluentd-elasticsearch)
