### ISSUE TITLE
Resource elasticsearch_index with alias fails on multi node elastic 

### ISSUE THREAD

**Issue by kumar-shantanu** [phillbaker/terraform-provider-elasticsearch#110]
Hi, 
I am creating elasticsearch_index using this provider, this works against a single node elastic cluster however fails with the error "Error: rpc error: code = Unavailable desc = transport is closing" while running the same against a multi-node elastic cluster.

resource "elasticsearch_index" "dev-index" {
  for_each           = toset(var.dev)
  name               = "logs-${each.value}-dev-1"
  number_of_shards   = 1
  number_of_replicas = 1
  aliases = jsonencode({
    "logs-${each.value}-dev" = {
      "is_write_index" = false
    }
  })
}

**Comment by shantanu-sapient** [comment]
After Investing a bit more around this I found this was problem on the ELK side. It's just that the provider is not outputting the correct error message. For now I am closing this ticket.

**Comment by phillbaker** [comment]
What is the error message you were expecting to see? How is the ES cluster
configured so that the connection would not work?

**Comment by kumar-shantanu** [comment]
After Investing a bit more around this I found this was a problem on the ELK side. It's just that the provider is not outputting the correct error message. For now, I am closing this ticket.

**Comment by kumar-shantanu** [comment]
@phillbaker - This is what i am getting when I am doing a post through kibana dev tools for example, 

{
  "error" : {
    "root_cause" : [
      {
        "type" : "illegal_argument_exception",
        "reason" : "cannot create index with name [logs-xxx-dev-1], because it matches with template [logs] that creates data streams only, use create data stream api instead"
      }
    ],

Here is clearly saying why it's failing, I was hoping for a similar output from the provider :)

**Comment by phillbaker** [comment]
Fixed in https://github.com/phillbaker/terraform-provider-elasticsearch/commit/068a12c6fcf73bd9944814dfe4fcd25878ebe903
