### ISSUE TITLE
"no Elasticsearch node available" when using module input

### ISSUE THREAD

**Issue by guyelia** [phillbaker/terraform-provider-elasticsearch#111]
Hey, 
I have the following configuration for the provider:
```
provider "elasticsearch" {
  url = "https://${module.es.endpoint}"
}
```
When I know that the output of `module.es.endpoint` is:
`"vpc-MY_AWS_ES.us-east-1.es.amazonaws.com"`

But, when I apply, I get:
`Error: health check timeout: no Elasticsearch node available`

Even if I disabling  the healthcheck I get the same error:
`no URLs found: no Elasticsearch node available`

Writing the hardcoded URL is working fine.
any idea what I'm doing wrong?

Thanks!

**Comment by phillbaker** [comment]
Being about to create these at the same time would be great - as I remember, there were upstream terraform issues: terraform 0.11 specifically documented that providers could not depend on resources: https://www.terraform.io/docs/configuration-0-11/providers.html#interpolation.

It looks like 0.12 has similar language: https://www.terraform.io/docs/configuration/providers.html#provider-configuration:
> The configuration arguments defined by the provider may be assigned using expressions, which can for example allow them to be parameterized by input variables. However, since provider configurations must be evaluated in order to perform any resource type action, provider configurations may refer only to values that are known before the configuration is applied. In particular, avoid referring to attributes exported by other resources unless their values are specified directly in the configuration.

Unfortunately this is a feature request for terraform itself, not this provider. Please see #11 and https://github.com/phillbaker/terraform-provider-elasticsearch/issues/63 as well

**Comment by guyelia** [comment]
Hey, we not initializing it at the same time, we saved it as an output.

It turns out that this is a known issue with tf13.
You can read about it [here](https://github.com/hashicorp/terraform/issues/26274)

With the help of @yahel2410 we found a temporary solution:
`tf apply -target = module.es_logs_dev -target = output.es_logs_dev_url`

thanks anyway! you can close it.

**Comment by phillbaker** [comment]
> With the help of @yahel2410 we found a temporary solution:
tf apply -target = module.es_logs_dev -target = output.es_logs_dev_url

Yes, this sounds like a workaround, thanks for sharing.

**Comment by john-delivuk-rl** [comment]
Created #119 to address
