### ISSUE TITLE
Insecure not working

### ISSUE THREAD

**Issue by CumpsD** [phillbaker/terraform-provider-elasticsearch#113]
We are tunneling to Elasticsearch over SSH and using the provider like this:

```
provider "elasticsearch" {
  version     = "~> 1.5.0"
  url         = "https://localhost:${var.elasticsearch_ssh_port_forward}"
  insecure    = true
  username    = var.elasticsearch_master_user_name
  password    = var.elasticsearch_master_user_password
  sniff       = false
  healthcheck = false
  aws_region  = var.aws_region
  aws_profile = var.aws_profile
}
```

This results in:

```
Error: Get "https://localhost:19000/": x509: certificate is valid for *.eu-west-1.es.amazonaws.com, not localhost

  on core.tf line 54, in provider "elasticsearch":
  54: provider "elasticsearch" {
```

I would assume it would not error on this because of `insecure = true`?

**Comment by phillbaker** [comment]
It should: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/c88de6531c4a6841d63a8179776b3b7be2e3e51d/es/provider.go#L385-L392

Is there any additional error information? Can you try setting the [ES version explicitly](https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs#elasticsearch_version)?

**Comment by CumpsD** [comment]
No extra info :(

When I set the es version it errors out with:

```
module.api.elasticsearch_opendistro_role.reader: Creating...

Error: rpc error: code = Unavailable desc = transport is closing
```

**Comment by CumpsD** [comment]
If I don't set health check to `false` I get some more information:

```
Error: health check timeout: Head "https://localhost:19000": x509: certificate is valid for *.eu-west-1.es.amazonaws.com, not localhost: no Elasticsearch node available

  on core.tf line 56, in provider "elasticsearch":
  56: provider "elasticsearch" {
```

Which is probably also SSL related, because when I browse to it I get:

```json
{
name: "4893a361fdd5584a03a0b8b0029aff57",
cluster_name: "830031229216:xxxxx-staging",
cluster_uuid: "R37Vs3eoQ-GMG6MrXErn5w",
version: {
number: "7.8.0",
build_flavor: "oss",
build_type: "tar",
build_hash: "unknown",
build_date: "2020-10-30T13:32:39.918902Z",
build_snapshot: false,
lucene_version: "8.5.1",
minimum_wire_compatibility_version: "6.8.0",
minimum_index_compatibility_version: "6.0.0-beta1"
},
tagline: "You Know, for Search"
}```

**Comment by CumpsD** [comment]
Ok, I figured it out.

Because I have this in my config:

```
aws_region  = var.aws_region
aws_profile = var.aws_profile
```

It did not create a `tlsHttpClient` in this piece of code but an `awsHttpClient`, where the `insecure` is ignored.

https://github.com/phillbaker/terraform-provider-elasticsearch/blob/c88de6531c4a6841d63a8179776b3b7be2e3e51d/es/provider.go#L211-L219

Final result:

```
provider "elasticsearch" {
  version     = "~> 1.5.0"
  url         = "https://localhost:${var.elasticsearch_ssh_port_forward}"
  insecure    = true
  username    = var.elasticsearch_master_user_name
  password    = var.elasticsearch_master_user_password
}
```

```
  Enter a value: yes

module.api.elasticsearch_opendistro_role.reader: Creating...
module.api.elasticsearch_opendistro_role.reader: Creation complete after 5s [id=oslo_reader]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

I leave it up to you if you want to close this, or somehow take insecure in with the aws client.

**Comment by phillbaker** [comment]
> It did not create a tlsHttpClient in this piece of code but an awsHttpClient, where the insecure is ignored.

Ah, thanks. I'll take a look

**Comment by phillbaker** [comment]
I've added the insecure check to the aws client in this commit: https://github.com/phillbaker/terraform-provider-elasticsearch/commit/f924ab6c1d061db238dd49fab7365df9b89f7c3c.

Thanks for the details on this.

**Comment by CumpsD** [comment]
Thanks!
