### ISSUE TITLE
Assume role credentials should use the profile passed in

### ISSUE THREAD

**Issue by v3i1r4in** [phillbaker/terraform-provider-elasticsearch#114]
https://github.com/phillbaker/terraform-provider-elasticsearch/blob/9ae95fad41b2be18009051366bd27e738bd9322b/es/provider.go#L337 

Should pass along the AWS profile here so that we can use a specific profile to assume a role.

**Comment by phillbaker** [comment]
👋 thanks @v3i1r4in could that possibly explain https://github.com/phillbaker/terraform-provider-elasticsearch/issues/112 ?

**Comment by v3i1r4in** [comment]
Not sure, I am getting `aws.Config.CredentialsChainVerboseErrors` which is different from what they got. They don't seem to be using assume role though.

**Comment by phillbaker** [comment]
> Should pass along the AWS profile here so that we can use a specific profile to assume a role.

Can you clarify where the profile should be passed along, I don't see a spot to pass a profile in the docs: 
https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/#AssumeRoleProvider

https://github.com/phillbaker/terraform-provider-elasticsearch/blob/9ae95fad41b2be18009051366bd27e738bd9322b/es/provider.go#L304-L313

**Comment by v3i1r4in** [comment]
I have no experience with go nor the go aws sdk, but following is my best guess of what might work:
```go
if aws_access_key_id != "" {
	sessOpts.Config.Credentials = awscredentials.NewStaticCredentials(aws_access_key_id, aws_secret_access_key, aws_session_token)
} else if aws_profile != "" {
	sessOpts.Profile = aws_profile

	if aws_assume_role_arn != "" {
		sessOpts.Config.Credentials = assumeRoleCredentials(region, aws_assume_role_arn)
	}
}
```

**Comment by phillbaker** [comment]
I've added the profile to be passed down to aws in this commit: https://github.com/phillbaker/terraform-provider-elasticsearch/commit/f924ab6c1d061db238dd49fab7365df9b89f7c3c, I'll have a beta release in the next day or so, would you be able to test it?

**Comment by v3i1r4in** [comment]
yeah, that's great! thanks!

**Comment by phillbaker** [comment]
I've released https://registry.terraform.io/providers/phillbaker/elasticsearch/1.5.1-beta, could you give that a shot and confirm it's working?

**Comment by v3i1r4in** [comment]
Yes! It worked as expected!

**Comment by phillbaker** [comment]
Great, thanks for confirming.
