### ISSUE TITLE
create kibana alert/monitor

### ISSUE THREAD

**Issue by nadavtsa** [phillbaker/terraform-provider-elasticsearch#115]
Hi, I am a little new to terraform so maybe there is something I meissed but I can't understand how to create a kibana alert.

Can you add to the documentation (or send here) an example of how to create a kibana alert?

Thank you :)

**Comment by phillbaker** [comment]
Are you using XPack Watches or OpenDistro Monitors?

**Comment by nadavtsa** [comment]
OpenDistro Monitors

**Comment by phillbaker** [comment]
Will be on the terraform provider site in the next release, but for now can reference https://github.com/phillbaker/terraform-provider-elasticsearch/commit/91cd3abfa88648df872eb32f368167c6e51b728d
