### ISSUE TITLE
AWS Elasticsearch service: elasticsearch_xpack_index_lifecycle_policy always returns 401

### ISSUE THREAD

**Issue by marcuz** [phillbaker/terraform-provider-elasticsearch#118]
I consistently get (even opening up all permissions to terraform):

```hcl
Error: elastic: Error 401 (Unauthorized)
```

when trying to create the following resource on AWS ES service:

```hcl
resource "elasticsearch_xpack_index_lifecycle_policy" "test" {
  provider = elasticsearch.es_logs

  name = "terraform-test"
  body = <<-EOF
  {
      "policy": {
          "policy_id": "test",
          "description": "Changes replica count and deletes.",
          "last_updated_time": 1607102372176,
          "schema_version": 1,
          "error_notification": null,
          "default_state": "current",
          "states": [
              {
                  "name": "current",
                  "actions": [],
                  "transitions": [
                      {
                          "state_name": "delete",
                          "conditions": {
                              "min_index_age": "7d"
                          }
                      }
                  ]
              },
              {
                  "name": "delete",
                  "actions": [
                      {
                          "delete": {}
                      }
                  ],
                  "transitions": []
              }
          ]
      }
  }
  EOF
}
```

Creating the policy via Kibana works.

Is this to be expected in AWS ES?

**Comment by phillbaker** [comment]
Hello, can you provide a redacted version of how you've configured the provider?

**Comment by phillbaker** [comment]
Also to clarify, if this is a cluster running on AWS-managed elasticsearch service, it doesn't support xpack plugins. Trying to access xpack routes results in the http 401, see for example: https://github.com/elastic/beats/issues/8086

The similar OpenDistro plugins are usually available, see: https://github.com/phillbaker/terraform-provider-elasticsearch#opendistro

**Comment by marcuz** [comment]
You are right, I apologise.

I'm using the AWS-managed ES service and assumed I could use `elasticsearch_xpack_index_lifecycle_policy`.

`elasticsearch_opendistro_ism_policy` should be the way to go, thank you!
