### ISSUE TITLE
"invalid character 'Y' looking for beginning of value" when trying to manage an ES instance

### ISSUE THREAD

**Issue by alex-pravdin-sn** [phillbaker/terraform-provider-elasticsearch#121]
I'm getting the following error when trying to create an index:

```
Error: invalid character 'Y' looking for beginning of value

  on main.tf line 22, in provider "elasticsearch":
  22: provider "elasticsearch" {
```

TF configuration is:
```
terraform {
  required_providers {
    elasticsearch = {
      version = "1.5.0"
      source = "phillbaker/elasticsearch"
    }
  }
}

provider "elasticsearch" {
  url = "http://${var.es_host}"
  insecure = true
  sign_aws_requests = false
}

resource "elasticsearch_index" "tasks_index" {
  name = "${var.name}_${var.branch_name}"
  number_of_shards = var.es_number_of_shards
  number_of_replicas = var.es_number_of_replicas
}
```

The `es_host` variable contains only the hostname without protocol and port.

The server is HTTP-only v5.6.

Am I doing something wrong?

**Comment by phillbaker** [comment]
Hello, can you please include the following:
* terraform version
* logs from running terraform with  [TF_LOG=info](https://www.terraform.io/docs/internals/debugging.html)

**Comment by alex-pravdin-sn** [comment]
TF version 0.14.0

**Comment by alex-pravdin-sn** [comment]
No additional logs produced with TF_LOG=info

**Comment by phillbaker** [comment]
@alex-pravdin-sn sorry for the slow response here, this looks very similar to the issue reported in https://github.com/phillbaker/terraform-provider-elasticsearch/issues/127#issuecomment-757059334, did you need to use `https` instead of `http`?

**Comment by phillbaker** [comment]
I'm going to close this issue for now to consolidate, please re-open if there are further details.
