### ISSUE TITLE
Resources documentation

### ISSUE THREAD

**Issue by tzoratto** [phillbaker/terraform-provider-elasticsearch#122]
Hello,

first, thanks for all the work on this provider. When we started using the ELK stack (with elastic cloud) last year we were disappointed to see there was no official terraform provider for it and this one didn't seem to be "ready for production" at that point. Today I see all the work all of you have pushed into it this year and thank you for that. Now we want to try and use it.

This issue is about the documentation of the various resources this provider supports. On the terraform registry site there are only a few of them that are listed, for instance under Xpack there is only the elasticsearch_xpack_watch resource (+ elasticsearch_license in 1.5.1-beta but the naming seems wrong, it should be elasticsearch_xpack_licence, right ?) while it seems to support also elasticsearch_xpack_index_lifecycle_policy and others.

Are there any plans to update the documentation in order to accelerate this provider adoption ? We use many terraform providers and having the up-to-date documentation on terraform site really is a time-saver.

Thanks

**Comment by phillbaker** [comment]
I'm actually looking at using https://github.com/hashicorp/terraform-plugin-docs to generate the docs, hopefully that will fill in some of the gaps as well.

**Comment by phillbaker** [comment]
This should be complete, please open additional, specific issues or pull requests if you see any thing else missing!
