### ISSUE TITLE
Provider Doesn't Respect password changes. 

### ISSUE THREAD

**Issue by john-delivuk-rl** [phillbaker/terraform-provider-elasticsearch#126]
We lost the state for our password generated by `random_password`. When the next run happened, there were no changes made to the user. This may be an edge case, but definitely no bueno. I'll dig in tonight to see if I can resolve, but I wanted to log an issue here. 

As a work around, taint your resource before running an apply.

**Comment by phillbaker** [comment]
Hi @john-delivuk-rl, sorry to hear you had an issue. I'm not quite following what happened here, can you provide an example terraform config to clarify what resources were being used? (xpack or opendistro user?)

> We lost the state for our password generated by random_password

Was this data loss related to this provider or was local/remote state was removed?

**Comment by john-delivuk-rl** [comment]
Sorry for being vague, it was a busy day.
```
resource "random_password" "password" {
  length           = 24
  special          = true
  override_special = "_%@"
}

resource "elasticsearch_xpack_role" "some_role" {
  role_name = "role1"
  indices {
    names      = ["indexname*"]
    privileges = ["read", "write", "create_index"]
  }
  cluster = ["monitor"]
}

resource "elasticsearch_xpack_user" "some_user" {
  username = local.elasticsearch_user
  password = random_password.password.result
  roles    = ["role1"]
}
```
We were moving state to reconcile a part of our Infra as code, lets call them State KEEPIT, and State TRASH. We updated our state by doing imports into KEEPIT for the resources that were created in TRASH.  We skipped importing `random_password.password` because we assumed when the new password was generated, we would see it get updated in the downstream resources, which happened everywhere but `elasticsearch_xpack_user`. It never detected a change, retaining the old password. I think in a simpler case if someone were to taint the `random_password.password`, `elasticsearch_xpack_user` would fail to update the existing user.

My hunch is the password isn't in state and it's being ignored for change detection. I'm going to look around and see how other providers handle this.

**Comment by john-delivuk-rl** [comment]
Looks like mysql hashes the password to compare the values on subsequent runs, if you're good with it I can throw together a PR. 

https://github.com/terraform-providers/terraform-provider-mysql/blob/master/mysql/resource_user.go#L38

**Comment by phillbaker** [comment]
@john-delivuk-rl thanks for the details. 

Yes, hashing the password for subsequent comparison does make sense. We currently only diff it on create:
https://github.com/phillbaker/terraform-provider-elasticsearch/blob/b6219618248d7dc93c8cb72af5ef7967b1daafa6/es/resource_elasticsearch_xpack_user.go#L53
https://github.com/phillbaker/terraform-provider-elasticsearch/blob/b6219618248d7dc93c8cb72af5ef7967b1daafa6/es/resource_elasticsearch_xpack_user.go#L60
https://github.com/phillbaker/terraform-provider-elasticsearch/blob/b6219618248d7dc93c8cb72af5ef7967b1daafa6/es/resource_elasticsearch_opendistro_user.go#L31
https://github.com/phillbaker/terraform-provider-elasticsearch/blob/b6219618248d7dc93c8cb72af5ef7967b1daafa6/es/resource_elasticsearch_opendistro_user.go#L38

Please swap out in all four spots!

**Comment by phillbaker** [comment]
@john-delivuk-rl are you still thinking of pulling this into a PR?

**Comment by john-delivuk-rl** [comment]
Sorry been a bit tied up. I'll try to knock this out by Wednesday. Also I see a few bugs might have popped up from my previous changes. Let me know if you need a hand.

**Comment by john-delivuk-rl** [comment]
Hey @phillbaker Working on this now. For `password` and `password_hash` do we want to deprecate either of these? I think it makes sense to use `password` or `plaintext_password` and deprecate `password_hash`.

**Comment by phillbaker** [comment]
> For password and password_hash do we want to deprecate either of these? I think it makes sense to use password or plaintext_password and deprecate password_hash.

For now I think it's fine to keep them both as you have in your PR, thanks. I think `password_hash` matches the API?

**Comment by sergkondr** [comment]
Hello! I've faced this issue too. Do you have any updates?

<details>
<summary>My terraform code</summary>

```
locals {
  user_password = var.user_password != "" ? var.user_password : random_password.user_password.result
}

resource "elasticsearch_opendistro_user" "this" {
  username    = var.user_name
  password    = local.user_password
  description = "static user for ${var.role_name}(${var.issue})"
  backend_roles = [
    elasticsearch_opendistro_role.this.id
  ]
}

resource "random_password" "user_password" {
  length  = var.user_password_length
  lower   = true
  upper   = true
  number  = true
  special = true

  min_numeric = 2
  min_lower   = 2
  min_upper   = 2
  min_special = 2

  override_special = "!@%?"
}
```
</details>

```
Terraform v0.14.2
+ provider registry.terraform.io/hashicorp/aws v3.25.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/random v3.0.1
+ provider registry.terraform.io/phillbaker/elasticsearch v1.5.1
```
Opendistro for Elasticsearch on AWS
