### ISSUE TITLE
elasticsearch_opendistro_role throws error 500 while creating a new role

### ISSUE THREAD

**Issue by BenediktB** [phillbaker/terraform-provider-elasticsearch#129]
Currently i am facing some problems while deploying new roles in Elasticsearch OpenDistro.
As far as i understand the error mainly happens when things get deployed to fast. If i deploy the stack again it usually does not happen again. Only for the first creation of a role.

My terraform code looks like:

```
resource "elasticsearch_index_template" "beats" {
  count = length(local.config.beats_templates)
  name  = "${local.config.beats_templates[count.index]}-${local.config.beats_version}"
  body  = file("${abspath(path.root)}/${path.module}/assets/templates/${local.config.beats_templates[count.index]}-${local.config.beats_version}.json")
}

resource "elasticsearch_opendistro_role" "full_admin" {
  role_name           = local.full_admin_label
  description         = "Grants admin access to all ressources"
  cluster_permissions = ["*"]
  index_permissions {
    index_patterns  = ["*"]
    allowed_actions = ["*"]
  }
  tenant_permissions {
    tenant_patterns = ["*"]
    allowed_actions = ["*"]
  }
  depends_on = [elasticsearch_index_template.beats]
}

resource "elasticsearch_opendistro_roles_mapping" "admin_user_mapping" {
  role_name     = elasticsearch_opendistro_role.full_admin.id
  users         = var.users
  backend_roles = var.backend_roles
  depends_on = [elasticsearch_opendistro_role.full_admin]
}
```

Terraform output is:

```
elasticsearch_index_template.beats[2]: Creating...[0m[0m
elasticsearch_index_template.beats[4]: Creating...[0m[0m
elasticsearch_index_template.beats[0]: Creating...[0m[0m
elasticsearch_index_template.beats[1]: Creating...[0m[0m
elasticsearch_index_template.beats[3]: Creating...[0m[0m
elasticsearch_index_template.beats[2]: Still creating... [10s elapsed][0m[0m
elasticsearch_index_template.beats[4]: Still creating... [10s elapsed][0m[0m
elasticsearch_index_template.beats[0]: Still creating... [10s elapsed][0m[0m
elasticsearch_index_template.beats[1]: Still creating... [10s elapsed][0m[0m
elasticsearch_index_template.beats[3]: Still creating... [10s elapsed][0m[0m
elasticsearch_index_template.beats[0]: Creation complete after 11s [id=auditbeat-7.10.0][0m[0m
elasticsearch_index_template.beats[1]: Creation complete after 12s [id=filebeat-7.10.0][0m[0m
elasticsearch_index_template.beats[2]: Still creating... [20s elapsed][0m[0m
elasticsearch_index_template.beats[4]: Still creating... [20s elapsed][0m[0m
elasticsearch_index_template.beats[3]: Still creating... [20s elapsed][0m[0m
elasticsearch_index_template.beats[4]: Creation complete after 23s [id=winlogbeat-7.10.0][0m[0m
elasticsearch_index_template.beats[2]: Creation complete after 23s [id=heartbeat-7.10.0][0m[0m
elasticsearch_index_template.beats[3]: Creation complete after 24s [id=metricbeat-7.10.0][0m[0m
elasticsearch_opendistro_role.full_admin: Creating...[0m[0m
error creating role mapping: elastic: Error 500 (Internal Server Error): java.util.concurrent.TimeoutException: Timeout after 5SECONDS while retrieving configuration for [ROLES](index=.opendistro_security) [type=exception]: [][0m
```
Versions:
- Terraform: 0.12.26
- Provider 1.5.2-beta
- Elasticsearch: 7.9.1 (OpenDistro on AWS)

In general it seems to work if there is enough time between two action i.e. a null-ressource with a "sleep  10000" command but this somehow feels not like it is a promising way.

Maybe there is something i am not aware of?

**Comment by phillbaker** [comment]
Hi @BenediktB, thanks for opening an issue, can you please include the following:
* terraform version
* provider version
* elasticsearch version
* redacted version of the terraform resource configuration
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

After a quick look, it doesn't seem like this is an issue with the provider, but with the elasticsearch cluster. You can also try adjusting terraform's [built in mechanism for parallelism](https://www.terraform.io/docs/commands/apply.html#parallelism-n).

**Comment by BenediktB** [comment]
Thank you for your response.
We already tried setting -parallelism=1 but this won't fix the issue we have either. We also tried settigns the dependencies properly so that only ressource is created. This will fix most errors, but sometimes they randonly occur again.

Currently we don't do anything with the cluster and just deployed it on AWS with terraform.
Once i can run our pipeline again i will provide you the terraform logs.

**Comment by phillbaker** [comment]
Hi @BenediktB, if you have dependencies between different resources, then you will need to either declare them explicitly or construct your dependencies so that the relationships determine order.

Since this 500 response comes from the cluster, I would encourage you to file a bug on the relevant upstream opendistro project or ask in their support forums - this doesn't seem like an issue with the provider itself.

I'm going to close this for now, please reopen if there are issues with the provider.
