### ISSUE TITLE
Feature Request: Resource and data documentation

### ISSUE THREAD

**Issue by Jeeppler** [phillbaker/terraform-provider-elasticsearch#13]
It would be nice to have a documentation of the resources and data objects this provider supports, maybe even with examples.

**Comment by Jeeppler** [comment]
Yes, I did not see that folder. Does this provider really only support two resources? Are there no data sources?

Did you test this provider only with AWS Elasticsearch?

**Comment by phillbaker** [comment]
@Jeeppler I have used it primarily with AWS ES, but I believe others are using it on self-managed clusters.

**Comment by Jeeppler** [comment]
@phillbaker thnaks for the clarification.
