### ISSUE TITLE
Filebeat pipeline - YAML to JSON error

### ISSUE THREAD

**Issue by Kronk74** [phillbaker/terraform-provider-elasticsearch#135]
Hi,

With filebeat version 7.4.0, it was possible to push modules pipelines with json from git repo:
https://github.com/elastic/beats/tree/7.4/filebeat/module/elasticsearch/server/ingest

But with version 7.10.2, only yaml file are available : 
https://github.com/elastic/beats/tree/7.10/filebeat/module/elasticsearch/server/ingest

I tried to use yamldecode to replace by the new one but it seems not working also : 

```
Error: Incorrect attribute value type

  on filebeat.tf line 73, in resource "elasticsearch_ingest_pipeline" "filebeat_7102_elastic_server_log":
  73:   body = yamldecode(file("${path.module}/ingest-pipelines/elasticsearch/filebeat-7.10.2-elasticsearch-server-pipeline.yml"))
    |----------------
    | path.module is "."

```
Did you already met this kind of issue ?

I don't know how to push filebeat pipeline with new version.

Regards,

Thomas

**Comment by phillbaker** [comment]
This is more of a general terraform question than a question specific to this provider.

The body needs to be json, so you could probably try something like `body = jsonencode(yamldecode(file(...)))`, I haven't tried it myself though :).

**Comment by phillbaker** [comment]
Hi @Kronk74, I'm going to close this issue, please re-open if there are provider specific issues.

**Comment by Kronk74** [comment]
Hi @phillbaker 

Sorry for my late answer but I finally find a way to do it.

```
locals {
  pipe = yamldecode(file("${path.module}/ingest-pipelines/nginx/filebeat-7.10.2-nginx-access-default.yaml"))
}

resource "elasticsearch_ingest_pipeline" "filebeat_7102_nginx_access" {    
  name = "filebeat-7.10.2-nginx-access-default"    
  body = jsonencode(local.pipe)    
} 
```
You must create a local variable on which you do `yamldecode`. After that, use `jsonencode` in body resource.

Tested with terraform 0.13 but I think with later version it will work also.

I hope this little tips will help someone 👍 

Best regards,

Thomas
