### ISSUE TITLE
"elasticsearch_index_template" keeps wanting to change "order"

### ISSUE THREAD

**Issue by imriz** [phillbaker/terraform-provider-elasticsearch#136]
Hi,

We're using layered templates, but it seems the provider won't respect the "order" value.
It shows this change every run:
```
 # elasticsearch_index_template.default-logstash-template will be updated in-place
  ~ resource "elasticsearch_index_template" "default-logstash-template" {
      ~ body = jsonencode(
          ~ {
                index_patterns = [
                    "logstash-*",
                ]
                mappings       = {
                    _size = {
                        enabled = true
                    }
                }
              + order          = 0
```

**Comment by phillbaker** [comment]
Hello, can you please include the following:
* terraform version
* provider version
* elasticsearch version
* redacted version of the terraform resource configuration
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by imriz** [comment]
Hi, thank you for you reply:

- terraform version: 0.13.5/0.13.1
- provider version: 1.5.0
- elasticsearch version: 7.9.1 (AWS ElasticSearch)
- redacted version of the terraform resource configuration:
```
resource "elasticsearch_index_template" "default-logstash-template" {
  name = "default-logstash-template"
  body = file("${path.module}/templates/default-logstash-template.json")
}
```
- terraform logs by setting TF_LOG=info:
attached
[tf.log](https://github.com/phillbaker/terraform-provider-elasticsearch/files/5899514/tf.log)

**Comment by mpereira** [comment]
I'm seeing this too.

| | |
|-|-|
| Terraform | v0.13.5 |
| terraform-provider-elasticsearch | v1.5.3 |
| AWS Elasticsearch | 7.9.1 |

**Terraform resource**
```tf
resource "elasticsearch_index_template" "telemetry_services" {
  name = "telemetry_services"
  body = <<EOF
{
  "index_patterns": "${var.telemetry_span_index_prefix}-jaeger-service-*",
  "settings": {
    "index.number_of_shards": ${var.telemetry_service_index_number_of_shards},
    "index.number_of_replicas": ${var.telemetry_service_index_number_of_replicas}
  },
  "mappings": {
    "properties": {
      "operationName": {
        "type": "keyword"
      },
      "serviceName": {
        "type": "keyword"
      }
    }
  }
}
EOF
}
```

**Comment by phillbaker** [comment]
Hello, following up on this, have you tried specifying the order in the template definition? If the API is returning the value, I suggest you "backport" it into the JSON. This is an unfortunate side effect of specifying the json bodies directly, see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/93 for a potential fix.

**Comment by phillbaker** [comment]
I'm going to close this issue for now, please see my comment above. Please re-open if there are further details.
