### ISSUE TITLE
AWS Custom Endpoint Support

### ISSUE THREAD

**Issue by Munkfeister** [phillbaker/terraform-provider-elasticsearch#138]
AWS provider support doesn't allow you to use a custom endpoint for the AWS ElasticSearch instance.

https://github.com/phillbaker/terraform-provider-elasticsearch/blob/116c9ff6da0d481881aa687d3e7bb2e03fdcfcd4/es/provider.go#L28

This line 'auto detects' whether to use AWS credentials to connect to the ElasticSearch instance.  However, this means it doesn't support the use of a custom endpoint.

Suggest having a input variable to override this auto-detection if a custom endpoint is being used.

**Comment by phillbaker** [comment]
Hi @Munkfeister thanks for opening an issue, are you setting any of the other `aws_*` attributes on the provider?

**Comment by Munkfeister** [comment]
Hello!  Not explicitly, no.  I currently rely on environment variables to populate those values as I'm trying to use it in a CI/CD pipeline which contain those values already.  However, just looking through your provider code again, I can see now that I could explicitly specify an aws_region for using a custom endpoint url.  Is that correct?

**Comment by phillbaker** [comment]
Hi @Munkfeister that's correct, either should opt into the AWS request signing: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/es/provider.go#L248-L253

Did this end up working for you? How could we document this more clearly?

**Comment by phillbaker** [comment]
This is in fact already documented in the `aws_region` parameter: https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs#aws_region

I'll add a note in the section about AWS auth as well.
