### ISSUE TITLE
Failed to create index patterns via elasticsearch_kibana_object resource

### ISSUE THREAD

**Issue by mrtnfchs** [phillbaker/terraform-provider-elasticsearch#140]
Our existing implementation is using the `elasticsearch_kibana_object` resources to create index patterns as part of the initial setup of the AWS ElasticSearch managed service. We plan to enable `advanced_security_options` and make use of the `internal user database` functionality. In order for this provider to work with these advanced security options we've extended the provider details as following

```
provider "elasticsearch" {
  url = "vpc-******.es.amazonaws.com"
  sniff = false
  insecure = true
  elasticsearch_version = "7.9"
  healthcheck = false
  sign_aws_requests = false
  username = "admin"
  password = "**********"
}
```

As a result we're able to create resources like `elasticsearch_opendistro_role`, `elasticsearch_opendistro_user` and `elasticsearch_opendistro_ism_policy` but we're unable to create index patterns the same way we did before. Terraform outputs a successful creation of the `elasticsearch_kibana_object` (no errors) but verifying in Kibana shows no index patterns are created. This behavior popped up since the `advanced_security_options` was enabled. Is anyone aware of any open issue related to this topic? The following snippet shows how we used to create index patterns before and which now seems to fail without an error

```
resource "elasticsearch_kibana_object" "index_pattern_application" {
  body = <<EOF
[
  {
    "_id": "index-pattern:application",
    "_type": "doc",
    "_source": {
      "type": "index-pattern",
      "index-pattern": {
        "title": "application-*",
        "timeFieldName": "@timestamp"
      }
    }
  }
]
EOF
  depends_on = [aws_elasticsearch_domain.es]
}
```

Details:
- ElasticSearch type: `VPC-based`
- ElasticSearch version: `v7.9`
- Terraform version: `v0.12.24`
- Provider version: `provider.elasticsearch v1.5.2-beta1` and `provider.elasticsearch v1.5.1` were both tested

**Comment by lfacchinelli** [comment]
I'm having the exact same issue with `v1.5.5`.

Terraform apply finish successfully but no index-pattern is created. 

Wonder if this is somehow related to AWS Elasticsearch. Seems like some API handlers are not available on AWS

**Comment by mkoertgen** [comment]
Works fine with elastic-oss. Having the same problem with open-distro, i.e. `terraform plan/apply` shows successful creation of resources.

 From what i can see is that the provider seems not be aware of the .kibana-alias settings. 
In open-distro it creates the resources in `.kibana_1` instead of `.kibana_<id>_user` resulting in Kibana not showing the newly created resources.

I am not too much into open-distro yet but maybe this is related to https://github.com/phillbaker/terraform-provider-elasticsearch/issues/169

**Comment by mkoertgen** [comment]
I digged a little deeper and am quite sure that this is related to the tenanct concept of open-distro.

Here are the defined aliases

```json
GET _alias
{
  ".kibana_1" : {
    "aliases" : {
      ".kibana" : { }
    }
  },
  "security-auditlog-2021.06.03" : {
    "aliases" : { }
  },
  ".kibana_92668751_admin_1" : {
    "aliases" : {
      ".kibana_92668751_admin" : { }
    }
  },
  ".opendistro_security" : {
    "aliases" : { }
  }
}
```

**Comment by mkoertgen** [comment]
Until #169 is ready and merged here is my workaround using [external_data_source](https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source) and a quick python3 helper script

 workaround

**Comment by mkoertgen** [comment]
I updated my workaround to just determinstically deriving the kibana user name (= tenant name) using
- https://github.com/jcantrill/cluster-logging-tools/blob/master/scripts/kibana-index-name

However, the helper script requires python on the terraform agent (works both with python 2/3 and on windows/linux as well).

**Comment by phillbaker** [comment]
Going to close this issue in favor of https://github.com/phillbaker/terraform-provider-elasticsearch/issues/169 as it does look like the same underlying solution. Thanks for the investigation on this!
