### ISSUE TITLE
Possible to update an index template's settings after creation ?

### ISSUE THREAD

**Issue by tanalan** [phillbaker/terraform-provider-elasticsearch#141]
Hi,

I'm using terraform to manage an AWS Elasticsearch cluster.
Terraform v0.13.5 and v1.5.0 of this terraform-provider-elasticsearch.

Is there a way to update an index template's settings after creating it?
I am excluding the mappings/properties type as I believe that Elasticsearch doesn't allow this (we'd have to re-index or create a new index).

For example, if I initially have
```
resource "elasticsearch_index_template" "my-index-name" {
    name = "blah"
    body = <<EOF {
        ...,
        "settings": {
            "number_of_shards": 5,
            ....
        }
    }
}
```

Would it be possible to change number of shards somehow using the provider, without making a new index?
Additionally, is it possible to add new settings like perhaps [index/search slow logs](https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-slowlog.html)?

I did try, but the index doesn't seem to pick up these changes, so I'm assuming no, but I wanted to ask, if perhaps there is a workaround or other solution.

Thank you!

**Comment by phillbaker** [comment]
Hi @tanalan, the `elasticsearch_index_template` resource is only used to create indices, not update them later.

In the code for the of the `elasticsearch_index` resource which can update indices, there's a distinction between settings that cannot be changed after creation (static) and those that can be updated (dynamic) - this is based on elasticsearch limitations: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/8d01aa6608088f4cf987c669ba46aa1cf439a969/es/resource_elasticsearch_index.go#L18-L32

That being said, not all possible settings are available today, it would definitely be possible to add more.

**Comment by tanalan** [comment]
Gotcha, thank you for confirming, @phillbaker ! It'd be great to have more settings added in the future (:
That said, I'll close this issue, thank you again!
