### ISSUE TITLE
Possible to Upload Saved Object to Specific Tenant of Elasticsearch

### ISSUE THREAD

**Issue by bjfish25** [phillbaker/terraform-provider-elasticsearch#142]
On my aws elasticsearch cluster version 7.9 with multiple tenants, saved objects created with this provider are created on the global tenant.

I was curious if it would be possible to create a saved-object on a custom tenant using this provider?

**Comment by phillbaker** [comment]
Hi @bjfish25, can you link to documentation for how this would be done with the underlying elasticsearch API? Assuming it's possible via the API, it would be possible to add in the provider. Can you share an example resource configuration and how the tenant might be configured?

**Comment by bjfish25** [comment]
Hi @phillbaker thanks for the response. I'm not sure exactly where on the olivere/elastic thus adding tenants as an enhancement may have to include them. 

See https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/#manage-kibana-indices 

Indices would be saved on a different .kibana index
```
.kibana_<hash>_<tenant_name>
.kibana_<hash>_<username>
```

**Comment by phillbaker** [comment]
Hi @bjfish25, this PR https://github.com/phillbaker/terraform-provider-elasticsearch/pull/144 adds support for creating kibana tenants in opendistro. It seems like you should be able to use that resource and just setting the index (as is already possible) in the `kibana_object_resource`? What do you think?

**Comment by bjfish25** [comment]
Thanks @phillbaker . thanks for the [index reference](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/dc185f13240eee33703e93045aee917464cc4e6f/es/resource_elasticsearch_kibana_object.go#L59) completely missed that.

I think #144 is really promising but I think a little bit more is needed for this for something done other than manual, I think this may be a opendistro limitation to just monitor until fixed.

For example, I had created a tenant with the resource.
```hcl
resource "elasticsearch_opendistro_kibana_tenant" "test" {
  tenant_name = "testtenant"
  description = "testtenant"
}
```

The ".kibana_-1636436036_testtenant_1" index is generated. See [here for a discussion](https://discuss.opendistrocommunity.dev/t/tenant-saved-objects-kibana-index/1981/3) and this [jsfiddle](http://jsfiddle.net/Ciul/w42en/) or if you can think of a different way to get this index name.

It would be great if elasticsearch_opendistro_kibana_tenant had an output with the index with the hash.

For example here is the current state for a tenant
```
    {
      "mode": "managed",
      "type": "elasticsearch_opendistro_kibana_tenant",
      "name": "test",
      "provider": "provider[\"registry.terraform.io/phillbaker/elasticsearch\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "description": "terraform-tenant-test",
            "id": "terraform-tenant-test",
            "tenant_name": "terraform-tenant-test"
          },
          "sensitive_attributes": []
        }
      ]
    },
```

**Comment by bjfish25** [comment]
Fixed in https://github.com/phillbaker/terraform-provider-elasticsearch/releases/tag/v1.6.0

Thanks @phillbaker
