### ISSUE TITLE
On index_not_found_exception, just create the index

### ISSUE THREAD

**Issue by bnelson729** [phillbaker/terraform-provider-elasticsearch#143]
When you receive a `Error: elastic: Error 404 (Not Found): no such index [logs] [type=index_not_found_exception]` during the refresh, you shouldn't error out the terraform plan. Other providers will just take that as a sign that the resource needs to be created.

**Comment by phillbaker** [comment]
HI @bnelson729 can you clarify what resource this is impacting? Is it `resource_elasticsearch_index`?

**Comment by phillbaker** [comment]
@bnelson729 can you clarify how this happened?

Was an index created using the resource, deleted out of band, and then the resource refreshed?
