### ISSUE TITLE
'error creating role mapping' while trying to create an opendistro_role

### ISSUE THREAD

**Issue by tdmalone** [phillbaker/terraform-provider-elasticsearch#145]
With the following code:
```
resource "elasticsearch_opendistro_role" "audit_manage" {
  role_name   = "audit_manage"
  description = "Allows management of application audit indices, including deletion."

  index_permissions {
    allowed_actions = ["create_index", "delete", "manage_aliases"]
    index_patterns  = [local.index_pattern]
  }
}
```

and the following plan:
```
Terraform will perform the following actions:

  # module.db_es_04.elasticsearch_opendistro_role.audit_manage will be created
  + resource "elasticsearch_opendistro_role" "audit_manage" {
      + description = "Allows management of application audit indices, including deletion."
      + id          = (known after apply)
      + role_name   = "audit_manage"

      + index_permissions {
          + allowed_actions = [
              + "create_index",
              + "delete",
              + "manage_aliases",
            ]
          + fls             = []
          + index_patterns  = [
              + "app-*",
            ]
          + masked_fields   = []
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

I receive the error:
```
Error: error creating role mapping: elastic: Error 400 (Bad Request): []

  on ../../modules/app-elasticsearch-cluster/security.tf line 53, in resource "elasticsearch_opendistro_role" "audit_manage":
  53: resource "elasticsearch_opendistro_role" "audit_manage" {
```

(Note how it's referring to a 'role mapping' possibly called 'elastic' - I'm not trying to create any mappings yet, just the role itself).

With `TF_LOG=DEBUG`, the relevant portion doesn't appear to shed much more light:
```

2021-02-21T16:48:57.816+1100 [DEBUG] plugin: plugin process exited: path=/Users/tim/terraform/realms/ops/.terraform/plugins/darwin_amd64/terraform-provider-aws_v3.26.0_x5 pid=65861
2021-02-21T16:48:57.816+1100 [DEBUG] plugin: plugin exited
2021-02-21T16:48:57.817+1100 [INFO]  plugin: configuring client automatic mTLS
2021-02-21T16:48:57.840+1100 [DEBUG] plugin: starting plugin: path=/Users/tim/.terraform.d/plugins/terraform-provider-elasticsearch args=[/Users/tim/.terraform.d/plugins/terraform-provider-elasticsearch]
2021-02-21T16:48:57.849+1100 [DEBUG] plugin: plugin started: path=/Users/tim/.terraform.d/plugins/terraform-provider-elasticsearch pid=65862
2021-02-21T16:48:57.849+1100 [DEBUG] plugin: waiting for RPC address: path=/Users/tim/.terraform.d/plugins/terraform-provider-elasticsearch
2021-02-21T16:48:57.862+1100 [INFO]  plugin.terraform-provider-elasticsearch: configuring server automatic mTLS: timestamp=2021-02-21T16:48:57.862+1100
2021-02-21T16:48:57.892+1100 [DEBUG] plugin: using plugin: version=5
2021-02-21T16:48:57.892+1100 [DEBUG] plugin.terraform-provider-elasticsearch: plugin address: address=/var/folders/r3/m56_97kx73g2n442gr8kc3p40000gp/T/plugin422340885 network=unix timestamp=2021-02-21T16:48:57.891+1100
2021-02-21T16:48:57.945+1100 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unimplemented desc = unknown service plugin.GRPCStdio"
module.db_es_04.elasticsearch_opendistro_role.audit_manage: Creating...
2021/02/21 16:48:58 [DEBUG] module.db_es_04.elasticsearch_opendistro_role.audit_manage: applying the planned Create change
2021/02/21 16:48:58 [DEBUG] module.db_es_04.elasticsearch_opendistro_role.audit_manage: apply errored, but we're indicating that via the Error pointer rather than returning it: error creating role mapping: elastic: Error 400 (Bad Request): []
2021/02/21 16:48:58 [ERROR] module.db_es_04: eval: *terraform.EvalApplyPost, err: error creating role mapping: elastic: Error 400 (Bad Request): []
2021/02/21 16:48:58 [ERROR] module.db_es_04: eval: *terraform.EvalSequence, err: error creating role mapping: elastic: Error 400 (Bad Request): []
2021/02/21 16:48:58 [DEBUG] Uploading remote state to S3: {
```

This is on Terraform v0.12.29, with the v1.5.3 of this provider installed from master (we haven't quite finished our 0.13 upgrade, so I can't use the provider registry yet).

I am able to create the role using the REST API:
```
$ curl --silent https://<HOSTNAME>/_opendistro/_security/api/roles/audit_manage -X PUT -u '<USER>' --header 'Content-type: application/json' --data '{"description": "Allows management of application audit indices, including deletion.", "index_permissions": [{"allowed_actions": ["create_index", "delete", "manage_aliases"], "index_patterns": ["app-*"]}]}'
{"status":"CREATED","message":"'audit_manage' created."}
```

Other issues with similar errors:
- _Might_ be the same issue experienced in #91
- Doesn't appear to be related to #129

**Comment by tdmalone** [comment]
Also forgot to include - Elasticsearch 7.9 (via Amazon Elasticsearch Service), running R20210201 (the latest release).

**Comment by phillbaker** [comment]
Thanks for including details.

> (Note how it's referring to a 'role mapping' possibly called 'elastic' - I'm not trying to create any mappings yet, just the role itself).

I think this is just a typo in the error handler: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/99ec07b466a9c0be39067eabe3d2222a91db54a6/es/resource_elasticsearch_opendistro_role.go#L311

The http400 seems likely to be from how we're serializing the role to json, I'm curious if it's related to https://github.com/phillbaker/terraform-provider-elasticsearch/pull/105. Can you try v1.5.1 of the provider?

**Comment by tdmalone** [comment]
I'm really sorry, I gave you a bum steer on this one.

When going to download an older version to test as you suggested, I realised... we weren't downloading from `master` at all, but were pinned to v1.4.1 (due to some difficulty with our watches returning large diffs after that version). Our pinning was done in a shell script that downloaded the provider using `go get`, given that we're not on TF 0.13 with the provider registry yet...

So, I apologise! I updated to `master` and this does now indeed work properly. I will need to figure out how best to install two different versions of the provider at once and then hasten up our move to 0.13 :)

**Comment by phillbaker** [comment]
No problem @tdmalone. 

For what it's worth, there are also binaries published with each release if that makes things easier to test, e.g.: https://github.com/phillbaker/terraform-provider-elasticsearch/releases/tag/v1.5.3. That would avoid any compilation and just let you put the binary into the right spot.
