### ISSUE TITLE
 error creating xxxx: elastic: Error 403 (Forbidden)

### ISSUE THREAD

**Issue by yotsapon** [phillbaker/terraform-provider-elasticsearch#146]
I am trying to use terraform to create tenant project, role and ISM policy. But I got this error when trying to apply. I use basic auth method user/pass for accessing AWS Elasticsearch (VPC).
Provider config
![image](https://user-images.githubusercontent.com/46857257/109327669-2adf5a00-788b-11eb-90c7-06a0ca17fc1a.png)

Error
![image](https://user-images.githubusercontent.com/46857257/109328093-a3deb180-788b-11eb-953e-774dbe67987e.png)

![image](https://user-images.githubusercontent.com/46857257/109327974-7f82d500-788b-11eb-95bc-a8c7d476cc78.png)

**Comment by phillbaker** [comment]
Hi @yotsapon does this happen for only the elasticsearch_opendistro_kibana_tenant resource, or does it happen for other resources? Do you get this error if you plan or just on apply?

**Comment by yotsapon** [comment]
> Hi @yotsapon does this happen for only the elasticsearch_opendistro_kibana_tenant resource, or does it happen for other resources? Do you get this error if you plan or just on apply?

Sorry for late reply. It happens for other resources as well. The error comes out when apply it.

**Comment by Stratouklos** [comment]
If you are using the internal user DB (which it looks like you do) try setting `sign_aws_requests = false`. That did the trick for me.

**Comment by phillbaker** [comment]
Hi @yotsapon can you confirm if the above workaround works for you? If so, I'll go ahead and close this issue.

**Comment by ysytnik** [comment]
Hello, i use this config
`provider elasticsearch {
     url = https://vpc-xxx.eu-west-2.es.amazon.com
     username = "xxxname"
     password = "xxxpass"
     healthechceck = false
     elasticsearch_varsion = "7.9"
     sign_aws_requests = false
}`

and i get error: "Error: context dedline exceeded"

**Comment by phillbaker** [comment]
@ysytnik that doesn't seem related as it's a different error. Please search the issues and documentation for similar problems in the past.

**Comment by phillbaker** [comment]
I'm going to close this issue for now, please reopen if there are further details.
