### ISSUE TITLE
Ignore_changes doesn't work on user password - elasticsearch_xpack_user

### ISSUE THREAD

**Issue by Kronk74** [phillbaker/terraform-provider-elasticsearch#147]
>Terraform version : 0.13.4
>Elasticsearch : 7.10.2
>Elastic-provider : 1.5.0

Hello,

When I create user like below, each time I add/modify a role, password is reset : 

```
resource "elasticsearch_xpack_user" "users_test" {    
  username = "test"
  password = "thisisatest"    
  lifecycle {    
    ignore_changes = [password]    
  }    
  roles = ["public", "reporting_user", "test"]
} 
```

Do I made a mistake or there is a bug somewhere ?

Best regards,

Thomas

**Comment by phillbaker** [comment]
Hello, thanks for the bug report. 

This was recently updated in  https://github.com/phillbaker/terraform-provider-elasticsearch/pull/132, can you try version 1.5.3 of the provider and see if that fixes the issue?

**Comment by Kronk74** [comment]
Hello,

Thanks new version solved my problem :)

It doesn't work when user is modified first time (I think because passwords is saved into state file at this time) but it works second time.

Thanks :)
