### ISSUE TITLE
Create Kibana "Alerts and Actions"

### ISSUE THREAD

**Issue by cedef** [phillbaker/terraform-provider-elasticsearch#155]
Hi,

First, thank you for your work on that provider.
My question is close but different from #115 

I would like to know if it's possible to manage "Alerts and Actions" (and Connectors maybe ?) (using the following [API](https://www.elastic.co/guide/en/kibana/7.11/alerts-api.html)) with `elasticsearch_kibana_object` resource ?

Or is there another resource that I can use to manage alerts objects ?

**Comment by phillbaker** [comment]
Hello! This sounds like a great addition, to the provider. It looks like these are replacing Xpack Watches for the elastic provided alerting solution, so a specific resource makes sense.

**Comment by phillbaker** [comment]
Noting that these routes were deprecated in 7.13 (https://www.elastic.co/guide/en/kibana/7.13/alerts-api.html) in favor of the slightly different `rule` endpoints (https://www.elastic.co/guide/en/kibana/current/create-rule-api.html)

**Comment by phillbaker** [comment]
A resource compatible for the 7.11 api was added in https://github.com/phillbaker/terraform-provider-elasticsearch/commit/edcfe52f72e9d074a34917ccffb95e022b1c6b91.

I'm going to close this for now and we can open a followup issue to add support for the newer 7.13 rule endpoints.
