### ISSUE TITLE
Can't use Basic Auth on AWS

### ISSUE THREAD

**Issue by tompierce** [phillbaker/terraform-provider-elasticsearch#156]
I'm using terraform 0.14, AWS ES (v7.9) and have enabled Fine Grained Access Control like so :

```
...
  advanced_security_options {
    enabled                        = true
    internal_user_database_enabled = true
    master_user_options {
      master_user_name     = "admin"
      master_user_password = random_password.master_user.result
    }
  }
...
```

I can hit the ES API with curl basic auth fine:
```
curl -s -XGET -u 'admin:<redacted>' $ES/_opendistro/_security/api/internalusers/
```

But when trying to set up a role mapping using the provider:

```
provider "elasticsearch" {
  url = "https://${aws_elasticsearch_domain.es.endpoint}"
  username = "admin"
  password = random_password.master_user.result
  healthcheck = false
}

resource "elasticsearch_opendistro_roles_mapping" "mapper" {
  role_name     = "all_access"
  users         = ["admin", "myotheruser"]
}
```

I get the following error:

```
module.elasticsearch.elasticsearch_opendistro_roles_mapping.mapper: Creating...

Error: Get "https://<es-url>.es.amazonaws.com/": NoCredentialProviders: no valid providers in chain. Deprecated.
        For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

Do I still need to provide AWS creds when using basic auth?

**Comment by phillbaker** [comment]
> Do I still need to provide AWS creds when using basic auth?

This likely depends on where you are running terraform. If you're running terraform from the same location where `curl` worked without AWS authentication, then no. The provider automatically detects AWS ES domains, if you need to turn off that functionality, [`sign_aws_requests`](https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs#sign_aws_requests), can be set to false.

**Comment by tompierce** [comment]
Thanks @phillbaker - That's moved me on a bit further, I think? But I'm now currently getting a mysterious "context deadline exceeded" error:

```
module.elasticsearch.elasticsearch_opendistro_roles_mapping.mapper: Creating...

Error: context deadline exceeded
```

My provider config is still similar (the same error with healthcheck true/false):
```
provider "elasticsearch" {
  url = "https://${aws_elasticsearch_domain.es.endpoint}"
  username    = "admin"
  password    = random_password.master_user.result
  healthcheck = true # / false (same result)
  sign_aws_requests = false
}
```

**Comment by tompierce** [comment]
Actually, setting `insecure = true` (in combination with `sign_aws_requests = false` seems to have worked...

I'm quite keen to have `insecure = false`, but I should probably go back to the documentation and ask a different question.

Thanks for the help!
