### ISSUE TITLE
[elasticsearch_opendistro_destination] sns type vanishing from state on refresh

### ISSUE THREAD

**Issue by rudrob** [phillbaker/terraform-provider-elasticsearch#158]
I'm using sns_alerts_destination  but seemingly it is created each time that apply is run. Perhaphs it's something about api not returning object because it seems to happen that it is removed each time from state on refresh being run. This results in multiple destinations being created - each time for apply run

example of erroneous working
**terraform state list**
data.terraform_remote_state.main
elasticsearch_index.test
elasticsearch_kibana_object.test_index_pattern_v7
elasticsearch_opendistro_destination.sns_alerts_destination
elasticsearch_opendistro_monitor.suricata_monitor

**terraform refresh**
elasticsearch_opendistro_destination.sns_alerts_destination: Refreshing state... [id=xBBfMHgBac7je8QV_lxF]
elasticsearch_kibana_object.test_index_pattern_v7: Refreshing state... [id=index-pattern:cloudwatch]
elasticsearch_index.test: Refreshing state... [id=suricata-log]
elasticsearch_opendistro_monitor.suricata_monitor: Refreshing state... [id=tTGhK3gBch3PADDCo2tP]

**terraform state list**
data.terraform_remote_state.main
elasticsearch_index.test
elasticsearch_kibana_object.test_index_pattern_v7
elasticsearch_opendistro_monitor.suricata_monitor

(even though nothing has changed in terms of resources existing - destination is gone each time)

**Comment by phillbaker** [comment]
Hello, can you please include the following:
* terraform version
* provider version
* elasticsearch version
* redacted version of the terraform resource configuration
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by rudrob** [comment]
tf version 0.14.7
provider version 1.5.3
elasticsearch version 7.9

relevant resource from configuration
```
resource "elasticsearch_opendistro_destination" "sns_alerts_destination" {
  body = jsonencode(
    {
      name : "sns_destination",
      type : "sns",
      sns : {
        topic_arn : local.sns_arn,
        role_arn : local.es_alerting_role_arn
      }
  })
}
```

the only thing relevant in terraform logs seems to be:
```
2021/03/18 19:37:44 [WARN] Provider "registry.terraform.io/phillbaker/elasticsearch" produced an unexpected new value for elasticsearch_opendistro_destination.sns_alerts_destination during refresh.
      - Root resource was present, but now absent
```

**Comment by SrAburrido** [comment]
+1 here!

tf version 0.13.0
provider version 1.5.4
elasticsearch version 7.9

```

resource "elasticsearch_opendistro_destination" "alert_sns" {
  body = jsonencode({
    "type" : "sns",
    "name" : "alert-sns",
    "sns" : {
      "role_arn" : aws_iam_role.alert_verisaas.arn,
      "topic_arn" : data.aws_sns_topic.alert_verisaas.arn
    }
  })
}

```

**Comment by phillbaker** [comment]
It seems like the opensource version of opendistro [doesn't support or document how to use SNS as a destination type](https://github.com/opendistro-for-elasticsearch/alerting/issues/91), and [the docs only list "Slack, Amazon Chime, custom webhook, or email"](https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/monitors/#create-destinations).

That being said, [AWS published how to use SNS](https://aws.amazon.com/blogs/big-data/setting-alerts-in-amazon-elasticsearch-service/), so in their custom version of OpenDistro it must be supported.

@rudrob @SrAburrido can you both confirm that you're using the hosted AWS Easticsearch Service?

**Comment by SrAburrido** [comment]
I can confirm we use the AWS managed one! 

In case this info is useful, in our case, the destination resource retrieves an id and the apply is completed successfully, then it keeps creating them but at least no errors are retrieved :)

```
elasticsearch_opendistro_destination.alert_sns: Creating...
[...]
elasticsearch_opendistro_destination.alert_sns: Creation complete after 0s [id=T0dW2ngBliwZ6Q8n830b]
[...]
Apply complete! Resources: 2 added, 6 changed, 0 destroyed.
```

**Comment by phillbaker** [comment]
@SrAburrido can you also share the OpenDistro version being used in the cluster? 

Up until version 1.11.0 there was no API endpoint to retrieve a destination (see https://github.com/opendistro-for-elasticsearch/alerting/issues/56#issuecomment-808942817), so we searched the underlying index: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/8debce22eade895f249523861befcb8021e2a6a9/es/resource_elasticsearch_opendistro_destination.go#L152-L154

However, it looks like with version 1.11.0, that search logic may have stopped working.

**Comment by SrAburrido** [comment]
It seems so:

![imagen](https://user-images.githubusercontent.com/33196983/115546374-3d7f7980-a2a5-11eb-90b0-983bd83b21b0.png)

**Comment by behnm** [comment]
Hello. 
I wanted to use this resource, but it gives me an error. My configuration is:

```
resource "elasticsearch_opensearch_destination" "aws_sns_channel" {
  body = jsonencode({
    "name" : "channel-alert",
    "type" : "sns",
    "sns" : {
      "topic_arn" : "`sns_arn`",
      "role_arn" : "`role_arn`"
    }
  })
}
```

The error is:
` Error: elastic: Error 405 (Method Not Allowed)`
