### ISSUE TITLE
Perpetual diff when setting error_notification on elasticsearch_opendistro_ism_policy

### ISSUE THREAD

**Issue by tdmalone** [phillbaker/terraform-provider-elasticsearch#165]
Given the following configuration:
```hcl
resource "elasticsearch_opendistro_ism_policy" "error_notification_test" {
  policy_id = "error-notification-test"

  body = jsonencode({
    policy = {
      description    = "Temporary policy for testing error notification diffs."
      default_state  = "hot"
      schema_version = 1

      error_notification = {
        destination = {
          slack = {
            url = local.slack.url
          }
        }

        message_template = {
          lang   = "mustache"
          source = "The index *{{ctx.index}}* failed to rollover."
        }
      }

      states = [
        {
          name = "hot"
          actions = [{
            rollover = { "min_index_age" = "30m" }
          }]
          transitions = []
        }
      ]
    }
  })
}
```

The error notification settings are correctly applied to the resource:
```
GET _opendistro/_ism/policies/error-notification-test

{
  "_id" : "error-notification-test",
  "_version" : 2,
  "_seq_no" : 44,
  "_primary_term" : 130,
  "policy" : {
    "policy_id" : "error-notification-test",
    "description" : "Temporary policy for testing error notification diffs.",
    "last_updated_time" : 1618197195266,
    "schema_version" : 1,
    "error_notification" : {
      "destination" : {
        "slack" : {
          "url" : "<REDACTED>"
        }
      },
      "message_template" : {
        "source" : "The index *{{ctx.index}}* failed to rollover.",
        "lang" : "mustache"
      }
    },
    "default_state" : "hot",
    "states" : [
      {
        "name" : "hot",
        "actions" : [
          {
            "rollover" : {
              "min_index_age" : "30m"
            }
          }
        ],
        "transitions" : [ ]
      }
    ]
  }
}
```

But after initial creation and no changes to the configuration, the following plan is perpetually generated:
```
  # module.db_es_04.elasticsearch_opendistro_ism_policy.error_notification_test will be updated in-place
  ~ resource "elasticsearch_opendistro_ism_policy" "error_notification_test" {
      ~ body         = jsonencode(
          ~ {
              ~ policy = {
                    default_state      = "hot"
                    description        = "Temporary policy for testing error notification diffs."
                  + error_notification = {
                      + destination      = {
                          + slack = {
                              + url = "<REDACTED>"
                            }
                        }
                      + message_template = {
                          + lang   = "mustache"
                          + source = "The index *{{ctx.index}}* failed to rollover."
                        }
                    }
                    schema_version     = 1
                    states             = [
                        {
                            actions     = [
                                {
                                    rollover = {
                                        min_index_age = "30m"
                                    }
                                },
                            ]
                            name        = "hot"
                            transitions = []
                        },
                    ]
                }
            }
        )
        id           = "error-notification-test"
        policy_id    = "error-notification-test"
        primary_term = 130
        seq_no       = 44
    }
```

Running Terraform v0.12.30, with the current `master` of this provider (b3995de aka v1.5.5 + one small merge).

Relevant docs: https://opendistro.github.io/for-elasticsearch-docs/docs/im/ism/policies/#error-notifications

Worth noting:
- The perpetual diff issue does not apply to the identically-schema'ed `notification` property under a state (https://opendistro.github.io/for-elasticsearch-docs/docs/im/ism/policies/#notification)
- There are a few other similar perpetual diffs with this resource but the others are easy to resolve, eg. adding `lang = "mustache"` to a state's `notification` property, or adding an empty `transitions = []` property to a state. `error_notifications` is a bit different in that there appears to be no workaround to setting the property without getting the diff back each time.

**Comment by tdmalone** [comment]
Additional version information:
Amazon Elasticsearch Service with Elasticsearch version 7.9, software release R20210201-P2

**Comment by phillbaker** [comment]
It looks like `error_notifications` were included in the initial release of ISM in https://github.com/opendistro-for-elasticsearch/index-management/pull/59 in [v1.0.0.0](https://github.com/opendistro-for-elasticsearch/index-management/releases/tag/v1.0.0.0).

I was able to reproduce this in the test here: https://github.com/phillbaker/terraform-provider-elasticsearch/actions/runs/761034635

I would have expect to not see it in the API response, thanks for including that. Let me check what the provider is doing here.

**Comment by phillbaker** [comment]
This is because `error_notification` is suppressed in when normalizing the response:
https://github.com/phillbaker/terraform-provider-elasticsearch/blob/e0b30474ba0aad6255b982a1729f3bafa46bd4d5/es/util.go#L113

I think this was included to ignore the attribute if it is null in the response, however, we should only be deleting if it is null, not if it has data.
