### ISSUE TITLE
Support for creating XPack users in Elasticsearch 6.x

### ISSUE THREAD

**Issue by brunopadz** [phillbaker/terraform-provider-elasticsearch#170]
Hi there,
Are there any plans on support create XPack users in Elasticsearch 6.x?

I'd be more than happy to contribute to the project. :)

**Comment by phillbaker** [comment]
Hello! Thanks for the offer of help.

Right now, it doesn't look like the upstream client we use (olivere/elastic) supports xpack users in the version for ESv6: https://github.com/olivere/elastic/tree/release-branch.v6. You could try opening a PR to backport the support in v7 to v6 upstream as a first step or asking on this issue if that makes sense to the author: https://github.com/olivere/elastic/issues/1113

**Comment by brunopadz** [comment]
Hi @phillbaker, 
Yeah, I've noticed all the work that must be done after opening this issue and forking both projects. :)

I'll see what I can do in the next weeks. 

Thanks bro.
