### ISSUE TITLE
Insecure not working when Fine-grained access control enabled with an IAM role as the master user

### ISSUE THREAD

**Issue by Kavinraja-G** [phillbaker/terraform-provider-elasticsearch#177]
Hi @phillbaker I'm using similar kind of tunneling from this #113 and using the **localhost** to refer the ES domain. But in my case I have configured the IAM role ARN as the master user instead of using the internal database.

Snippet of my provider configuration:
```
provider "elasticsearch" {
  url = "https://localhost:9200"
  aws_profile = "dev-profile"
  aws_region = "us-east-1"
  insecure = true
  healthcheck = false
}
```

Below is the error I'm getting when creating a sample index:
```
│ Error: Get "https://localhost:9200/": x509: certificate is valid for *.us-east-1.es.amazonaws.com, not localhost
│
│   with elasticsearch_index.test,
│   on main.tf line 33, in resource "elasticsearch_index" "test":
│   33: resource "elasticsearch_index" "test" {
```

**Comment by phillbaker** [comment]
> I have configured the IAM role ARN as the master user instead of using the internal database.

Can you clarify this? Please share the relevant (redacted) configuration for this at both the AWS and Elasticsearch level.

**Comment by Kavinraja-G** [comment]
Hi, This issue was solved by doing a workaround. Mapped the **localhost** with the AWS Elasticsearch endpoint in the  **/etc/hosts** file. Thanks!
