### ISSUE TITLE
Provide darwin_arm64 build

### ISSUE THREAD

**Issue by davidcaste** [phillbaker/terraform-provider-elasticsearch#178]
Hi!

Could you provide a build for the `darwin_arm64` architecture, please?

Thanks!!

**Comment by phillbaker** [comment]
Hello - `darwin_arm64` are provided for each tagged release on the releases page, e.g. in https://github.com/phillbaker/terraform-provider-elasticsearch/releases/tag/v1.5.6, `terraform-provider-elasticsearch_1.5.6_darwin_amd64.zip` is provided.

Is that what you're looking for?

**Comment by davidcaste** [comment]
Hi!!

I'm sorry, but I was in a hurry and I didn't described the issue properly.

One of our developers have a new shiny Apple M1 laptop, and when he tries to do a `terraform init` it fails to download the provider. These new Apple M1 laptops aren't using anymore the `darwin_amd64`, but the `darwin_arm64` architecture.

The problem is easy to replicate with the following configuration:

1. Create a new root module and define the provider in the following way:

    ```
    terraform {
      required_providers {
        elasticsearch = {
          source  = "phillbaker/elasticsearch"
          version = "~> 1.0"
        }
      }
    }
    ```

1. Create a temporary directory, e.g. `/tmp/terraform.d/plugins`, and try to mirror the there for different architectures:

    ```
    terraform providers mirror -platform=linux_amd64 -platform=darwin_amd64 -platform=darwin_arm64 "/tmp/terraform.d/plugins"                                                                   
    - Mirroring phillbaker/elasticsearch...
      - Selected v1.5.6 to meet constraints ~> 1.0
      - Downloading package for linux_amd64...
      - Package authenticated: self-signed
      - Downloading package for darwin_amd64...
      - Package authenticated: self-signed
      - Downloading package for darwin_arm64...
    - Skipping terraform.io/builtin/terraform because it is built in to Terraform CLI
    
    Error: Provider release not available
    
    Failed to download registry.terraform.io/phillbaker/elasticsearch v1.5.6 for
    darwin_arm64: provider registry.terraform.io/phillbaker/elasticsearch 1.5.6 is
    not available for darwin_arm64.
    ```

This is the error our developer with Apple M1 laptop is seeing.

Thanks!!

**Comment by davidcaste** [comment]
Thank you!!
