### ISSUE TITLE
Connection error when using AWS ES with enabled SAML 

### ISSUE THREAD

**Issue by ventsislav-georgiev** [phillbaker/terraform-provider-elasticsearch#183]
Error message:
`Error: rpc error: code = Unavailable desc = transport is closing`

The cluster has internal database enabled and the rest api works using basic authentication. However enabling SAML seems to break the provider, is this expected, can the provider be set up to work with the basic auth APIs for AWS ES?

**Comment by ventsislav-georgiev** [comment]
My bad the trace showed that the issue is not comming from the elasticsearch provider but from the aws provider. It seems the aws provider cannot query the domain via [this data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/elasticsearch_domain) when SAML is enabled.

**Comment by r3kzi** [comment]
i do not use the data source and i'm getting the same error.

``` 
2021-06-22T10:49:35.709+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
``` 

I'm running the same setup as you described.

I found https://githubmemory.com/repo/phillbaker/terraform-provider-elasticsearch/issues/156 which described setting ` sign_aws_requests = false` and `insecure = true`.

Now the provider is working.

**Comment by r3kzi** [comment]
Maybe we can re-open this issue? Setting ` insecure = true` feels not correct. 

What do you think @phillbaker ?

**Comment by phillbaker** [comment]
Hi @r3kzi if you're interested in SAML auth issues, let's move the conversation to #189 which has more information.

If you'd like to discuss options for how not to set `insecure = true`, please open a new issue and include:
* terraform version
* provider version
* elasticsearch version (and opendistro version if relevant)
* redacted version of the terraform resource configuration
