### ISSUE TITLE
How to deal with LCM rollover to not recreate the index?

### ISSUE THREAD

**Issue by atamgp** [phillbaker/terraform-provider-elasticsearch#187]
I want to create this index:

```
resource "elasticsearch_index" "this" {
  for_each = {
    for index in local.indices_to_create : index.name => index
  }

  name               = "${var.team_name}-${each.key}-000001"
  number_of_replicas = each.value.number_of_replicas
  aliases = jsonencode({
    "${var.team_name}-${each.key}" = {
      "is_write_index" = true
    }
  })
}
```

In combination with LCM which does roll-over e.g.

```
{
  "policy": {
    "phases": {
      "hot": {
        "min_age": "0ms",
        "actions": {
          "rollover": {
            "max_size": "${max_size}",
            "max_age": "${max_age}"
          },
          "set_priority": {
            "priority": ${priority}
          }
        }
      },
      "delete": {
        "min_age": "${retention}",
        "actions": {
          "delete": {
            "delete_searchable_snapshot" : true
          }
        }
      }
    }
  }
}
```

With this, e.g. if index **atam-000001** is created, after which LCM rolles-over to **atam-000002** and the prev one is automatically removed. Rerunning a Terraform plan will try to recreate **atam-000001**

What is the advise to deal with this?

**Comment by phillbaker** [comment]
Hello! Sorry for the slow delay, it sounds like what you're describing can be addressed with rollover aliases and index templates. Please see the example in this PR description: https://github.com/phillbaker/terraform-provider-elasticsearch/pull/96.

As well, please see the upstream docs here: https://www.elastic.co/guide/en/elasticsearch/reference/current/getting-started-index-lifecycle-management.html#ilm-gs-alias-apply-policy
