### ISSUE TITLE
Add Watcher resource

### ISSUE THREAD

**Issue by tdmalone** [phillbaker/terraform-provider-elasticsearch#19]
Firstly, thanks so much for doing the work to put this provider together, in absence of an official provider!

I'd love to have support for Watchers - is this something you might consider adding? It looks like there's an implementation at https://github.com/ansoni/terraform-provider-elastic/blob/master/resource_elasticsearch_watcher.go which might be able to be lifted to here with attribution (its MIT licensed), but I will also post in that repo to ask if the owner is interested in collaborating here (makes sense to combine forces).

**Comment by phillbaker** [comment]
Quite open to it! Did you see https://github.com/phillbaker/terraform-provider-elasticsearch/pull/15 which looks like a good start?

**Comment by tdmalone** [comment]
I did not notice that PR - thanks, will check it out.

**Comment by phillbaker** [comment]
https://github.com/phillbaker/terraform-provider-elasticsearch/pull/15 was cherry picked and merged!
