### ISSUE TITLE
Can't create visualization with elasticsearch_kibana_object

### ISSUE THREAD

**Issue by willbabitskiy** [phillbaker/terraform-provider-elasticsearch#190]
Hello,
There is no possible to add visualization with admin user

Provider version: **1.5.7** 
Config:
```
provider "elasticsearch" {
  url = var.url
  username = local.user
  password = local.password
  sniff = false
  insecure = true
  sign_aws_requests = false
  healthcheck = false
  elasticsearch_version = var.es_version
}
```

Visualization resource
```
resource "elasticsearch_kibana_object" "grafana_visualization" {
  body       = <<EOF
[
  {
    "_id": "grafana-log-count",
    "_source": {
      "type": "visualization",
      "visualization": {
        "title": "Grafana count",
        "visState": "state json",
        "uiStateJSON": "{}",
        "description": "Grafana log count",
        "version": 1,
        "kibanaSavedObjectMeta": {
          "searchSourceJSON": "json"
        }
      }
    }
  }
]
EOF
}
```

Error:
```
elasticsearch_kibana_object.grafana_visualization: Creating...
2021/07/02 22:29:07 [DEBUG] EvalApply: ProviderMeta config value set
2021/07/02 22:29:07 [DEBUG] elasticsearch_kibana_object.grafana_visualization: applying the planned Create change
2021-07-02T22:29:07.401+0300 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.7: 2021/07/02 22:29:07 [INFO] elastic7CreateIndexIfNotExists .kibana
2021-07-02T22:29:08.464+0300 [DEBUG] plugin.terraform-provider-elasticsearch_v1.5.7: 2021/07/02 22:29:08 [INFO] Failed to creating new kibana index: elastic: Error 403 (Forbidden)
2021/07/02 22:29:08 [DEBUG] elasticsearch_kibana_object.grafana_visualization: apply errored, but we're indicating that via the Error pointer rather than returning it: elastic: Error 403 (Forbidden)
```

Admin user has full access to the cluster.

Can you please clarify what is wrong with my config?

**Comment by phillbaker** [comment]
Hello, it looks like kibana has not been initialized and the index not created. The provider does a best effort to create the index, but it looks like it did not work. I'd suggest initializing it by opening Kibana in your browser first. Otherwise please confirm that you can create indices using the same credentials on the cluster, e.g.:
```
curl -X PUT -H 'Content-type: application/json' --user <user:password> http://<your url>/.kibana -d '{}'
```

**Comment by willbabitskiy** [comment]
@phillbaker Hello. The thing is the **.kibana** index is already in place. 

I call the ES to create **.kibana** index with admin creds and have the following. 
```
{
  "error": {
    "root_cause": [
      {
        "type": "invalid_index_name_exception",
        "reason": "Invalid index name [.kibana], already exists as alias",
        "index_uuid": "_na_",
        "index": ".kibana"
      }
    ],
    "type": "invalid_index_name_exception",
    "reason": "Invalid index name [.kibana], already exists as alias",
    "index_uuid": "_na_",
    "index": ".kibana"
  },
  "status": 400
}
```
There is no 403 error

**Comment by phillbaker** [comment]
Hi, sorry for the slow reply, but I can't reproduce this. Are you using a hosted ES cluster? If so, on what service?

The check that the provider does is similar to `curl -I https://<domain>/.kibana/`, if it receives a 200, then it doesn't try to create the index. What does that call return on your cluster?

**Comment by willbabitskiy** [comment]
Hello,
We use the AWS ES service. I feel AWS requires adding some extra IAM or other permissions but I can't find them.
The `curl` query gets 403. 
I've been investigating what is wrong with the ES configuration

**Comment by willbabitskiy** [comment]
Closing the issue. Will open a new one if have additional information
