### ISSUE TITLE
elasticsearch_host.url is not populated

### ISSUE THREAD

**Issue by dcrowe** [phillbaker/terraform-provider-elasticsearch#191]
datasource.elasticsearch_host.url does not appear to be populated.

In the code it looks like the ID attribute is being populated with the URL, which doesn't match the docco.

Small problem, easily worked around, just wanted to let you know. Thanks for the project.

**Comment by phillbaker** [comment]
Thanks! Should be fix in https://github.com/phillbaker/terraform-provider-elasticsearch/commit/56744ee5f912bd35daffc421ac74ffb215165778 (made it match the docs, both ID and url are populated).
