### ISSUE TITLE
enable  the option to provide additional argumeents that are meant for backword compatibility include_type_name=true

### ISSUE THREAD

**Issue by sangeethdba** [phillbaker/terraform-provider-elasticsearch#193]
to create a index in v7 with type name specified  we should pass the argument include_type_name=true when we create index

PUT idx_com_reprocess_v6?include_type_name=true
{
  "settings": {
    "index": {
      "number_of_shards": 3,
      "number_of_replicas" : 0,
      "refresh_interval" : -1
    }

is it possible to go get such option.

**Comment by phillbaker** [comment]
@sangeethdba what's the usecase for doing this in Elasticsearch v7?

**Comment by sangeethdba** [comment]
We are using this on 6.8 not 7

**Comment by sangeethdba** [comment]
- In 6.8, the index creation, index template, and mapping APIs support a
   query string parameter (include_type_name) which indicates whether
   requests and responses should include a type name. It defaults to true,
   and should be set to an explicit value to prepare to upgrade to 7.0. Not
   setting include_type_name will result in a deprecation warning. Indices
   which don’t have an explicit type will use the dummy type name _doc.

Elasticsearch 7.x

   - Specifying types in requests is deprecated. For instance, indexing a
   document no longer requires a document type. The new index APIs are PUT
   {index}/_doc/{id} in case of explicit ids and POST {index}/_doc for
   auto-generated ids. Note that in 7.0, _doc is a permanent part of the
   path, and represents the endpoint name rather than the document type.
   - The include_type_name parameter in the index creation, index template,
   and mapping APIs will default to false. Setting the parameter at all
   will result in a deprecation warning.
   - The _default_ mapping type is removed.

**Comment by sangeethdba** [comment]
It’s would be great to allow the these types of additional arguments

**Comment by phillbaker** [comment]
@sangeethdba thanks, I'm aware of what the option does. I'm interested in your usecase - what are you trying to do that is not working? How would you use this argument if it was available? Can you provide a terraform resource configuration that is not currently working?

**Comment by sangeethdba** [comment]
We have few applications  which are explicitly using type name when they
search .to cater those apps we are forced to create index and mapping using
that option.when we go to next version we will
Ask apps to make necessary changes. Hope this helps

**Comment by sangeethdba** [comment]
@phillbaker would  this be possible to implement?

**Comment by phillbaker** [comment]
@sangeethdba  to clarify - doc types are allowed in the mapping block on a v6 cluster today. For example, see the documentation: https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/index

Can you provide a terraform resource configuration and elasticsearch configuration that is not currently working?

There are two scenarios where I can imagine this being relevant:
* trying to configure an index on a v6 cluster without a doc type, i.e. forward compatibility for a v7-style mapping
* trying to configure an index on a v7 cluster with a doc type, i.e. backward compatibility for a v6-style mapping

From your description, it's not clear if you're in either of these cases.

**Comment by sangeethdba** [comment]
#! Deprecation: [types removal] The parameter include_type_name should be explicitly specified in create index requests to prepare for 7.0. In 7.0 include_type_name will default to 'false', and requests are expected to omit the type name in mapping definitions.
{
  "acknowledged" : true,
  "shards_acknowledged" : true,
  "index" : "test"
}

we are on 6.8 and using that parameter when creating indexes .we are in the first category

**Comment by sangeethdba** [comment]
on 7.x cluster ,if we are using type in mapping while creating index we are getting this error.
{
  "error" : {
    "root_cause" : [
      {
        "type" : "mapper_parsing_exception",
        "reason" : "Root mapping definition has unsupported parameters:  [reprocessor : {properties={hostName={type=keyword}, hostIP={type=keyword}, reprocessId={type=text}, errorCode={type=keyword}, isAutoRetryable={type=keyword}, maxRetryCount={type=long}, clientHeaders={type=nested, properties={value={type=keyword}, key={type=keyword}}}, currentRetryCount={type=long}, sequenceNo={type=keyword}, state={type=keyword}, applicationName={type=keyword}, key={type=keyword}, kafkaKey={type=keyword}, groupforSameKey={type=boolean}, query={properties={match_all={properties={applicationName={type=text}}}, term={properties={applicationName={type=text}}}}}, createTimeStamp={type=date}, cassandraTTL={type=long}, modifyTimeStamp={type=date}, flowName={type=keyword}, nextRetryTime={type=date}, script={properties={inline={type=text}, lang={type=text}, params={properties={tag={type=long}}}}}, exceptionGroupName={type=keyword}, isESRecordLocked={type=boolean}, topic={type=keyword}, retryInterval={type=long}, createProgId={type=keyword}}}]"
      }
    ], 


to overcome ,we are using include_type_name=true explicitly on 7.x cluster while creating  or remove the type from mapping when create index.

**Comment by sangeethdba** [comment]
@phillbaker

**Comment by sangeethdba** [comment]
is this not a valid requirement? @phillbaker .

is there any lint available that checks against the resources we create ,like for validation of syntax ,format etc

**Comment by phillbaker** [comment]
Following up here - the include_type_name is not supported in v7 of the elastic library, see https://github.com/olivere/elastic/issues/1448. I've asked whether a PR adding that support would be accepted.
