### ISSUE TITLE
OpenDistro Kibana Tenant Index Calculation

### ISSUE THREAD

**Issue by timcosta** [phillbaker/terraform-provider-elasticsearch#195]
I noticed that the kibana tenant index that is being output has capital letters in the index name, but in Kibana it's all lowercase for me. I believe Kibana isnt case sensitive (or at least in my case I believe it's being run on case-insensitive file systems) btu wanted to highlight that as a potential weirdness.

https://github.com/phillbaker/terraform-provider-elasticsearch/blob/df9749c5477f47c48f9ec887aa78469349dc98fe/es/resource_elasticsearch_opendistro_kibana_tenant.go#L100

I'm seeing `.kibana_1362558315_PlatformServices` be output. The hash is correct so the caps arent affecting the hash calculation, but the index as shown in kibana is `.kibana_1362558315_platformservices`.

**Comment by phillbaker** [comment]
Thanks for opening an issue. 

In fact ES index names cannot have uppercase letters: https://github.com/elastic/elasticsearch/issues/31262, so this should be lowercased.
