### ISSUE TITLE
Improve error messages during plugin crash

### ISSUE THREAD

**Issue by holy-moly-555** [phillbaker/terraform-provider-elasticsearch#199]
Hey there,

first of all I want to thank you for developing and maintaining this great provider! It really helps us to put our many Elasticsearch resources under source control.

Provider Version: 1.6.0
Elasticsearch Version: 7.9.3
Operation Mode: AWS Elasticsearch Service (= OpenDistro)

Yesterday we had an issue where the plugin crashed on every Terraform operation (plan, apply, import) only with the following message (standard log severity):

**_panic: runtime error: invalid memory address or nil pointer dereference_**

Stack trace: 
Stack trace from the terraform-provider-elasticsearch_v1.6.0 plugin:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x11504c0]
goroutine 97 [running]:
github.com/phillbaker/terraform-provider-elasticsearch/es.resourceElasticsearchGetOpenDistroRolesMapping(0xc000386048, 0x14, 0x11f0f80, 0xc0008e5320, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        github.com/phillbaker/terraform-provider-elasticsearch/es/resource_elasticsearch_opendistro_roles_mapping.go:166 +0x380
github.com/phillbaker/terraform-provider-elasticsearch/es.resourceElasticsearchOpenDistroRolesMappingRead(0xc0003a0620, 0x11f0f80, 0xc0008e5320, 0xc0003a0620, 0x0)
        github.com/phillbaker/terraform-provider-elasticsearch/es/resource_elasticsearch_opendistro_roles_mapping.go:73 +0xbf
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00021acf0, 0xc0006c6370, 0x11f0f80, 0xc0008e5320, 0xc000208390, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk@v1.13.1/helper/schema/resource.go:460 +0x12e
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ReadResource(0xc000208308, 0x16946f0, 0xc0006ac1b0, 0xc0003820c0, 0xc000208308, 0xc0006ac1b0, 0xc000393ba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/helper/plugin/grpc_provider.go:525 +0x3dd
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ReadResource_Handler(0x13f4fe0, 0xc000208308, 0x16946f0, 0xc0006ac1b0, 0xc000382060, 0x0, 0x16946f0, 0xc0006ac1b0, 0xc0006ec0b0, 0xa5)
        github.com/hashicorp/terraform-plugin-sdk@v1.13.1/internal/tfplugin5/tfplugin5.pb.go:3269 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0008b0540, 0x16a0678, 0xc0005b2780, 0xc000384000, 0xc0005247b0, 0x1eaa5d0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.33.2/server.go:1210 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0008b0540, 0x16a0678, 0xc0005b2780, 0xc000384000, 0x0)
        google.golang.org/grpc@v1.33.2/server.go:1533 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00068e1c0, 0xc0008b0540, 0x16a0678, 0xc0005b2780, 0xc000384000)
        google.golang.org/grpc@v1.33.2/server.go:871 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.33.2/server.go:869 +0x1fd
Error: The terraform-provider-elasticsearch_v1.6.0 plugin crashed!
This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
```

After long hours of googeling and research I could find the root cause of the issue when I turned on the DEBUG log severity (`export TF_LOG=DEBUG`):

[DEBUG] provider.terraform-provider-elasticsearch_v1.6.0:   <Error>
[DEBUG] provider.terraform-provider-elasticsearch_v1.6.0:     <Type>Sender</Type>
[DEBUG] provider.terraform-provider-elasticsearch_v1.6.0:     <Code>AccessDenied</Code>
[DEBUG] provider.terraform-provider-elasticsearch_v1.6.0:     **<Message>User: arn:aws:sts::ACCOUNT_ID:assumed-role/ROLE_NAME/aws_session is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::ACCOUNT_ID:ROLE_SPECIFIED_IN_PROVIDER_CONFIG</Message>**
[DEBUG] provider.terraform-provider-elasticsearch_v1.6.0:   </Error>
[DEBUG] provider.terraform-provider-elasticsearch_v1.6.0:   <RequestId>REQUEST_ID</RequestId>
[DEBUG] provider.terraform-provider-elasticsearch_v1.6.0: </ErrorResponse>
[DEBUG] provider.terraform-provider-elasticsearch_v1.6.0: ]
[DEBUG] provider.terraform-provider-elasticsearch_v1.6.0: _**PANIC: runtime error: invalid memory address or nil pointer**_ dereference

I also noticed that no crash.log file was created.

It turned out that a colleague made some changes in IAM and my account could no longer assume the role specified via `aws_assume_role_arn` in the provider config.

I am not a go expert but to me it seems that the elastic client will be nil if the authentication with the cluster fails (which is reasonable). But unfortuanetly the provider drops the root cause of the issue (unauthorized) und just logs this very general error message **_runtime error: invalid memory address or nil pointer_**

Now, would it be possible to log such concrete error causes not only to the debug level but especially to the default level? Of course, one could argue that a good developer would just turn on debug mode immediately. But imho this would improve the stability and general acceptance of this great provider even more!

Looking forward to your thoughts.

Greetings.

**Comment by phillbaker** [comment]
> It turned out that a colleague made some changes in IAM and my account could no longer assume the role specified via aws_assume_role_arn in the provider config.
> I am not a go expert but to me it seems that the elastic client will be nil if the authentication with the cluster fails 

Interesting, if this is what's happening, then we should not crash, but return a usable error the user. This should be doable, I'll take a look when I get a chance.

**Comment by phillbaker** [comment]
It looks like this is due to referencing a variable before doing an error check in the response:  https://github.com/phillbaker/terraform-provider-elasticsearch/blob/b1d1eee3f0853661eba48fa1dbea039b99f062d0/es/resource_elasticsearch_opendistro_roles_mapping.go#L162-L166

however, the error message that should be printed is along the lines of:
```
│ Error: health check timeout: Head https://vpc-terraform-i62ad6bn45spqiuz67reoqifka.us-east-2.es.amazonaws.com: NoCredentialProviders: no valid providers in chain. Deprecated.
│ 	For verbose messaging see aws.Config.CredentialsChainVerboseErrors: no Elasticsearch node available
```
