### ISSUE TITLE
Support for OpenDistro for ElasticSearch?

### ISSUE THREAD

**Issue by Jeeppler** [phillbaker/terraform-provider-elasticsearch#20]
AWS introduced it's own open source licensed plugins for ElasticSearch. They call it [OpenDistro for ElasticSearch](https://opendistro.github.io/for-elasticsearch/).

There goal is to have four additional plugins for:

- [x] Security (#45)
- SQL (doesn't have state, so not applicable for terraform)
- [x] Alerting
- Performance Analyzer (doesn't have state, so not applicable for terraform)
- [x] Index State Management (#50)

@phillbaker are you planning to support those extensions?

AWS seems to slowly introduce those new plugins into their installation through Service Software updates. They started rolling out the alerting feature with [AWS ElasticSearch Service upgrade R20190221](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/release-notes.html).

It would be nice to be able to create alerts via Terraform in this plugin.

**Comment by phillbaker** [comment]
I saw the announcement, didn't realize AWS had integrated it into their
service, very cool! Thanks for the link.

Would definitely like to integrate these features. We'll have to take a
look and see how alerts are configured, if they're just ES index documents
should be the same as a Kibana dashboard.

**Comment by Jeeppler** [comment]
It creates three different indices:

- `.opendistro-alerting-alert-history-*`
- `.opendistro-alerting-alerts`
- `.opendistro-alerting-config`

**Comment by Jeeppler** [comment]
Here is the API documentation: https://opendistro.github.io/for-elasticsearch-docs/docs/alerting/api/#create-monitor

**Comment by phillbaker** [comment]
I've started work for supporting destinations and monitors on the [open-distro](https://github.com/phillbaker/terraform-provider-elasticsearch/tree/open-distro) branch

**Comment by wloczykij2** [comment]
Is there any progress with that?

**Comment by phillbaker** [comment]
@wloczykij2 see the description, it has a checklist. As of now, alerting in open distro is supported. Pull requests would be great for the other components.

**Comment by schewara** [comment]
Just came across this issues and was wondering what happened with the `open-distro` branch.
Seems it's either gone or just not visible to the rest of the world.

**Comment by phillbaker** [comment]
@schewara it was merged into master and released! The current status of supporting open distro is in the description as checkboxes.

**Comment by gezb** [comment]
Are you planing to merge #45 and #50 to complete the support for OpenDistro for ElasticSearch?

**Comment by phillbaker** [comment]
They're not quite mergable as is, but the functionality would be great to merge!

**Comment by tdmalone** [comment]
Should `resource_elasticsearch_destination` be renamed to `resource_elasticsearch_opendistro_destination`?

**Comment by phillbaker** [comment]
Yes it should, I'll do that now.

**Comment by phillbaker** [comment]
See https://github.com/phillbaker/terraform-provider-elasticsearch/commit/19c1ee3dd91c35e124069549452543b410d2dc8d.

Since this provider now supports the existing functionality of opendistro, I'm going to close this issue as completed. Please open new issues for specific changes or additions.
