### ISSUE TITLE
elasticsearch_xpack_user is failing with Error: unsupported in elasticv6 client

### ISSUE THREAD

**Issue by sangeethdba** [phillbaker/terraform-provider-elasticsearch#202]
elasticsearch_xpack_user.srv_combo: Creating...

Error: unsupported in elasticv6 client

  on elasticIndex_combo.tf line 59, in resource "elasticsearch_xpack_user" "srv_combo":
  59: resource "elasticsearch_xpack_user" "srv_combo" {

resource "elasticsearch_xpack_role" is working fine .

resource "elasticsearch_xpack_role" "srv_combo" {
  role_name = "test"
  indices {
    names        = ["als_capture_combo"]
    privileges = ["read","index"]
  }
  cluster = [
    "trasport_client",
    "monitor"
  ]
}

**Comment by sangeethdba** [comment]
@phillbaker

**Comment by sangeethdba** [comment]
@phillbaker appreciate your help

**Comment by sangeethdba** [comment]
working on elastic 7 cluster ,but not on elastic 6 cluster .
are there any limitation using this provider for user creation on elastic 6 cluster @phillbaker

**Comment by sangeethdba** [comment]
role creation is working fine for both e6 and e7 cluster .Not sure why user creation is failing for e6.

**Comment by phillbaker** [comment]
Please see #170.
