### ISSUE TITLE
adding a normalizer while creating index

### ISSUE THREAD

**Issue by sangeethdba** [phillbaker/terraform-provider-elasticsearch#204]
```
# Create a simple index
resource "elasticsearch_index" "idx_q1_booking_salesorder_2021_v7" {
  name = "idx_q1_booking_salesorder_2021_v7"
  number_of_shards = 1
  number_of_replicas = 1
  aliases = <<EOF
{
  "als_q1_booking_salesorder_2021_wr": {},
  " als_q1_booking_salesorder": {}
}
EOF
analysis_analyzer = <<EOF
{
"normalizer": {
        "lowercase_normalizer": {
          "char_filter": [],
          "filter": [
            "lowercase"
          ],
          "type": "custom"
        }
      }
}
EOF
  mappings = <<EOF
 {
    "properties": {
        "aggs": {
            "properties": {
                "group_by_status": {
                    "properties": {
                        "terms": {
                            "properties": {
                                "field": {
                                    "type": "text"
                                },
```

```
Error: elastic: Error 400 (Bad Request): analyzer [normalizer] must specify either an analyzer type, or a tokenizer [type=illegal_argument_exception]

  on idx_q1_booking_salesorder_2021_v7.tf line 2, in resource "elasticsearch_index" "idx_q1_booking_salesorder_2021_v7":
   2: resource "elasticsearch_index" "idx_q1_booking_salesorder_2021_v7" {
```

Am i missing some thing.

im passing custom normalizer with this block 
```
analysis_analyzer = <<EOF
{
"normalizer": {
        "lowercase_normalizer": {
          "char_filter": [],
          "filter": [
            "lowercase"
          ],
          "type": "custom"
        }
      }
}
```
and using this custom normalizer in mapping block

**Comment by sangeethdba** [comment]
if i use like this 

# Create a simple index
resource "elasticsearch_index" "idx_q1_booking_salesorder_2021_v7" {
  name = "idx_q1_booking_salesorder_2021_v71"
  number_of_shards = 1
  number_of_replicas = 1
analysis_normalizer = <<EOF
{
        "lowercase_normalizer": {
          "char_filter": [],
          "filter": [
            "lowercase"
          ],
          "type": "custom"
        }
}
EOF
  aliases = <<EOF
{
  "als_q1_booking_salesorder_2021_wr1": {},
  " als_q1_booking_salesorder1": {}
}
EOF
  mappings = <<EOF
 {
    "properties": {
        "aggs": {
            "properties": {
                "group_by_status": {
                    "properties": {
                        "terms": {
                            "properties": {
                                "field": {
                                    "type": "text"
                                },
                                "size": {
                                    "type": "long"
                                }



getting the below error

Error: Unsupported argument

  on idx_q1_booking_salesorder_2021_v7.tf line 6, in resource "elasticsearch_index" "idx_q1_booking_salesorder_2021_v7":
   6: analysis_normalizer = <<EOF

An argument named "analysis_normalizer" is not expected here.

**Comment by sangeethdba** [comment]
@phillbaker appreciate your help

**Comment by sangeethdba** [comment]
please help

**Comment by phillbaker** [comment]
@sangeethdba please use the markdown formatting in issues to separate your blocks of code, otherwise pasted code does not retain its whitespace and is very hard to read. Github has good documentation on this, for example: https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown.

For this question, please see the example in the tests: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/c28d2dec3f5c366de4d694149a1d6489471ea79b/es/resource_elasticsearch_index_test.go#L83-L87

Please confirm the version of the elasticsearch provider you are using.

**Comment by sangeethdba** [comment]
Iam using the latest version 1.6.1

**Comment by sangeethdba** [comment]
when i used the block

analysis_normalizer = jsonencode({ 
 		my_normalizer = { 
       type = "custom" 
       filter = ["lowercase", "asciifolding"] 
     } 
i got the unsupported argument error

Error: Unsupported argument

  on idx_q1_booking_salesorder_2021_v7.tf line 6, in resource "elasticsearch_index" "idx_q1_booking_salesorder_2021_v7":
   6: analysis_normalizer = <<EOF

An argument named "analysis_normalizer" is not expected here.

**Comment by sangeethdba** [comment]
Im using 1.6.0 .sorry for the confusion

**Comment by sangeethdba** [comment]
search homedepot.com homedepot.com ern.homedepot.com amer.homedepot.com amer.qahomedepot.com ssc.homedepot.com hdpromro.interlinebrands.com
nameserver 165.130.1.9

**Comment by sangeethdba** [comment]
```
# Create a simple index
resource "elasticsearch_index" "idx_q1_booking_salesorder_2021_v17" {
  name = "idx_q1_booking_salesorder_2021_v71"
  number_of_shards = 1
  number_of_replicas = 1
analysis_normalizer = <<EOF
{
   "lowercase_normalizer": {
      "type" : "custom",
      "filter" : [
"lowercase", "asciifolding"
]
    }
}
EOF
  aliases = <<EOF
{
  "als_q1_booking_salesorder_2021_wr1": {},
  "als_q1_booking_salesorder1": {}
}
EOF
  mappings = <<EOF
 {
    "properties": {
        "aggs": {
            "properties": {
                "group_by_status": {
                    "properties": {
                        "terms": {
                            "properties": {
                                "field": {
                                    "type": "text"
                                },
                                "size": {
                                    "type": "long"
```
is working fine with 1.6.1 provider. thanks for the help
