### ISSUE TITLE
possible to configure cluster.max_shards_per_node with provider?

### ISSUE THREAD

**Issue by tjbaker** [phillbaker/terraform-provider-elasticsearch#207]
Is it possible to put persistent cluster settings with this provider?

For example:
```
PUT _cluster/settings
{
    "persistent": {
        "cluster.max_shards_per_node": <int>
    }
}
```

Thanks!

**Comment by phillbaker** [comment]
Not currently, but this sounds like a good resource to add!

**Comment by EdRyan** [comment]
This would be very helpful! Maybe it makes sense to make a broader "cluster setting" resource but in this case I am looking specifically to modify max_shards_per_node as well.

**Comment by phillbaker** [comment]
Added in 79e1882e43dde7790f1ebda30337216690ee9308
