### ISSUE TITLE
Perpetual diffing on `elasticsearch_index_template` if `"order": 0` or `"aliases": {}`

### ISSUE THREAD

**Issue by zjanc** [phillbaker/terraform-provider-elasticsearch#211]
Hi,

I'm getting perpetual diffs on `elasticsearch_index_template` for specific scenarios:
- `order` is `0`
- `aliases` is `{}`

For my use case, I'm importing existing ES resources so I'm currently using the index template JSONs as returned by the ES API with no modifications.

The diff does not show up for index templates with order != 0 and non-empty aliases. It's possible to remove `order` and `aliases` from the fetched JSONs if they are zero/empty but I would prefer to have that explicitly in the JSON (as returned by the API).

**Additional Information:**
- Terraform version: `0.14.11`
- Provider version: `1.6.1`
- ES version: `7.10.2`

Terraform Resource configuration:
```terraform
# A mapping of template name -> template JSON file path
variable "index_templates" {
  type = map(string)
}

resource "elasticsearch_index_template" "index_template" {
  for_each = var.index_templates
  name = each.key
  body = file(each.value)
}
```

---
**Similar issues:**
- https://github.com/phillbaker/terraform-provider-elasticsearch/issues/136

**Comment by phillbaker** [comment]
Hi, sorry for the slow response on this. As you pointed out, this is similar to #136 - this seems like an unfortunate side effect of specifying the json bodies directly, see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/93 for a potential fix.

 If the API is returning the value, I suggest you "backport" it into the JSON.
