### ISSUE TITLE
Additional resources for Provider

### ISSUE THREAD

**Issue by AlexanderLahutsin** [phillbaker/terraform-provider-elasticsearch#214]
Dear,

Could you add  a few useful resources?:

**elasticsearch_opendistro_kibana_object**
  - index_pattern and etc
**elasticsearch_opendistro_object**
 - policy for Indices and etc

This is simplifies life & useble
Thanks

**Comment by phillbaker** [comment]
Hi @AlexanderLahutsin, unfortunately I'm not understanding the request.

* There is already a kibana object resource, this is compatible across different distributions of Elasticsearch, see the docs here: https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/kibana_object, it can be used for any object type in Kibana.
* What is a `elasticsearch_opendistro_object`? Please link to any relevant API documentation. There are specific resources for specific opendistro features, for example, for ISM policies, please see https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/opendistro_ism_policy

**Comment by phillbaker** [comment]
Since there's been no update to this issue, I'm going to close it for now. Please reopen if you can provide further details or have concerns.
