### ISSUE TITLE
AWS ES Domain with Cognito Pool returns Error 403 (Forbidden)

### ISSUE THREAD

**Issue by jacktkeys** [phillbaker/terraform-provider-elasticsearch#217]
Good morning.

I am trying to use your TF provider with an AWS Elasticsearch Domain secured by an AWS Cognito user pool. TF Plan works but when trying to Apply, I get the aforementioned error. Here is my TF script and logs.

```
provider "elasticsearch" {
    url = local.elasticsearch_logging_url
    aws_region = "us-east-1"
    sniff = false
    healthcheck = false
    elasticsearch_version = "7.4"
    username = ""
    password = ""
}
```

```
2021-09-09T10:38:46.281-0500 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.3.exe: 2021/09/09 10:38:46 [INFO] Using AWS: us-east-1
2021-09-09T10:38:46.281-0500 [DEBUG] plugin.terraform-provider-elasticsearch_v1.6.3.exe: 2021/09/09 10:38:46 [INFO] Using AWS: us-east-1
2021/09/09 10:38:46 [DEBUG] elasticsearch_index_template.core_search_logs: apply errored, but we're indicating that via the Error pointer rather than returning it: elastic: Error 403 (Forbidden)
2021/09/09 10:38:46 [TRACE] eval: *terraform.EvalMaybeTainted
2021/09/09 10:38:46 [TRACE] EvalMaybeTainted: elasticsearch_index_template.core_search_logs encountered an error during creation, so it is now marked as tainted
2021/09/09 10:38:46 [TRACE] eval: *terraform.EvalWriteState
2021/09/09 10:38:46 [TRACE] EvalWriteState: removing state object for elasticsearch_index_template.core_search_logs
2021/09/09 10:38:46 [TRACE] eval: *terraform.EvalApplyProvisioners
2021/09/09 10:38:46 [TRACE] EvalApplyProvisioners: elasticsearch_index_template.core_search_logs has no state, so skipping provisioners
2021/09/09 10:38:46 [TRACE] eval: *terraform.EvalMaybeTainted
2021/09/09 10:38:46 [TRACE] EvalMaybeTainted: elasticsearch_index_template.core_search_logs encountered an error during creation, so it is now marked as tainted
2021/09/09 10:38:46 [TRACE] eval: *terraform.EvalWriteState
2021/09/09 10:38:46 [TRACE] EvalWriteState: removing state object for elasticsearch_index_template.core_search_logs
2021/09/09 10:38:46 [TRACE] eval: *terraform.EvalIf
2021/09/09 10:38:46 [TRACE] eval: *terraform.EvalIf
2021/09/09 10:38:46 [TRACE] eval: *terraform.EvalWriteDiff
2021/09/09 10:38:46 [TRACE] eval: *terraform.EvalApplyPost
2021/09/09 10:38:46 [ERROR] eval: *terraform.EvalApplyPost, err: elastic: Error 403 (Forbidden)
2021/09/09 10:38:46 [ERROR] eval: *terraform.EvalSequence, err: elastic: Error 403 (Forbidden)
```

**Comment by phillbaker** [comment]
Hello the Error 403 indicates that permissions are denied when using the provider.

Can you confirm that the location where terraform is being run has valid credentials and those credentials can access the cluster? If terraform is being run on a ECS container, IRSA support may not be working, please see #112, which also has a workaround. I have not worked much with AWS Cognito, does anything need to be enabled in the SDKs for authentication support?

**Comment by jacktkeys** [comment]
I am running Terraform on my local machine. I will look at how any SDK calls would authenticate calls to a service protected by a Cognito user pool.

**Comment by phillbaker** [comment]
Hi there, following up on this with what I've been able to ascertain:
* How Cognito is set up determines a lot of how the user authentication flow works. From the examples I've seen, Cognito credentials can't directly be used against an ES cluster - they're to be used for a Kibana (Opensearch Dashboards) login and those Cognito credentials are exchanged for a key that corresponds to an IAM role.
  * See this issue for a description: https://github.com/opensearch-project/documentation-website/issues/152
* There's another description here in the [FAQ](https://aws.amazon.com/opensearch-service/faqs/) which describes this flow:
> Amazon OpenSearch Service also supports an integration with Amazon Cognito, to allow your end-users to log-in to OpenSearch Dashboards and Kibana through enterprise identity providers such as Microsoft Active Directory using SAML 2.0, Amazon Cognito User Pools, and more. Once you sign-in, Amazon Cognito establishes a session using the appropriate IAM principal, which provides access to the Amazon OpenSearch Service domain. These IAM principals are then available to be used with the fine-grained access control feature powered by OpenSearch.

Given that, I'm going to close this issue as Cognito credentials shouldn't be used directly in terraform to access the cluster.

**Comment by brayest** [comment]
On automation the role mappings need to be preserved by fully state the roles and users that are required to be set. 

When the Opensearch cluster is initially created the master user is added to the `all_access` and `security_manager`. This needs to be preserved. 

Normally when creating role mappings we forget about that. Therefore, when the new mapping is set, the old master user configuration is removed. That is why the 403 comes up.  The user replacing the mapping no longer has access to it. 

Once we have created the cluster with the master user ARN we need to add Cognito the master users map. Or what ever mapping we want to place. 

The resources should look something like this . 

```
  + resource "elasticsearch_opensearch_roles_mapping" "master_user_arn" {
      + backend_roles = [
          + "arn:aws:iam::1234567890:role/cognito_role",
        ]
      + description   = "Administrators"
      + id            = (known after apply)
      + role_name     = "all_access"
      + users         = [
          + "arn:aws:iam::1234567890:user/user1",
          + "arn:aws:iam::1234567890:user/master_user",
        ]
    }
```
The "arn:aws:iam::1234567890:user/master_user" initial master user should always be included. 

If for any reason the master was removed, then just replace the master user ARN in the opensearch config and then configure it back.  That will allow you to manage the cluster again and keep the master user in the map.
