### ISSUE TITLE
AWS kibana object _doc -> doc diff appearing suddenly

### ISSUE THREAD

**Issue by timcosta** [phillbaker/terraform-provider-elasticsearch#219]
Hello! We started seeing this crop up in the last day or two. It appears that AWS has made a change on their end that's causing `doc` to be converted to `_doc` internally which in turn leads to a perpetual diff. We're using 1.6.3 if that helps/matters.

```  
# lasticsearch_kibana_object.pattern["redacted"] will be updated in-place
  ~ resource "elasticsearch_kibana_object" "pattern" {
      ~ body  = jsonencode(
          ~ [
              ~ {
                  ~ _type   = "_doc" -> "doc"
                    # (2 unchanged elements hidden)
                },
            ]
        )
        id    = "index-pattern:redacted"
        # (1 unchanged attribute hidden)
```

**Comment by phillbaker** [comment]
Can you share the opendistro/opensearch version and if it changed recently
(correlated with this issue starting)?

**Comment by timcosta** [comment]
We're on Elasticsearch 7.10 and have been - it's possible that it's related to the R20210816 service software release though, the date is recent enough.

**Comment by tjbaker** [comment]
I saw the same, but found that `_type` isn't necessary, just remove it from the body and the diffs will be gone.

**Comment by phillbaker** [comment]
Hi all @timcosta did the above workaround fix the issue for you? If so, I think that's probably the best approach for now.

**Comment by timcosta** [comment]
I can confirm that it did.

**Comment by phillbaker** [comment]
Great, I'm going to close this out for now since there's a workaround. Please reopen if there are other issues
