### ISSUE TITLE
Creating elasticsearch user is not idempotent (breaks upon refresh)

### ISSUE THREAD

**Issue by harveyyau** [phillbaker/terraform-provider-elasticsearch#224]
Hi, I'm trying to create a user with the provider and assign it to a role. I'm using username/password authentication to access AWS ES.

Version: phillbaker/elasticsearch v2.0.0-beta.1
Server: AWS Managed Elasticsearch version 7.9

The user is successfully created and all appears fine. However, upon refresh, it shows:

```
elasticsearch_opendistro_user.user: Refreshing state... [id=es_user]
│ Error: elastic: Error 401 (Unauthorized)
```

How do I get around this? Thanks!

Code:
```hcl
# Configure the Elasticsearch provider
provider "elasticsearch" {
  url = "https://${aws_elasticsearch_domain.es_managed.endpoint}"

  username = data.vault_generic_secret.master_account.data["username"]
  password = data.vault_generic_secret.master_account.data["password"]

  elasticsearch_version = var.elasticsearch_managed_version
  healthcheck = false
  sniff = false
  sign_aws_requests = false
}

resource "elasticsearch_opendistro_user" "user" {
  username = data.vault_generic_secret.user_account.data["username"]
  password = data.vault_generic_secret.user_account.data["password"]
  description = "User account for general access"
}
```

**Comment by phillbaker** [comment]
Thanks for opening an issue! This looks very similar to https://github.com/phillbaker/terraform-provider-elasticsearch/issues/208

**Comment by harveyyau** [comment]
Hi Phill,

Thanks for the response. After some deep debugging, this may not be an issue with the provider. Closing this issue for now.
