### ISSUE TITLE
Provider don't follow cluster re-creation with interpolation 

### ISSUE THREAD

**Issue by alexandrst88** [phillbaker/terraform-provider-elasticsearch#228]
Hi! 

Version:  v2.0.0-beta.2

```
provider "elasticsearch" {
  url               = "${aws_elasticsearch_domain.example.endpoint}"
  aws_region        = var.aws_region
  sign_aws_requests = true
}
```

When I enabled option on the aws_elasticsearch_domain, that requires cluster recreation, provider fails with 
```
│ Error: HEAD healthcheck failed: This is usually due to network or permission issues. The underlying error isn't accessible, please debug by disabling healthchecks.
```

but when i pass

```
provider "elasticsearch" {
  url               = es-example.com
  aws_region        = var.aws_region
  sign_aws_requests = true
}
```

everything works fine, i haven't dig deeper in the code.

**Comment by phillbaker** [comment]
HI @alexandrst88 sorry for the slow reply here. Please provide the following information:

* sanitized versions of the urls being used for the cluster
* elasticsearch version (and opendistro version if relevant)
* redacted version of the terraform resource configuration
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by brayest** [comment]
This needs the HTTPS prefix

```
provider "elasticsearch" {
  url                   = "https://${module.opensearch.cluster_endpoint}"
  aws_profile           = "aws_profile"
  sniff               = false
  sign_aws_requests   = true
  healthcheck         = false
}
```

**Comment by phillbaker** [comment]
Thanks @brayest  - given the age of this issue and the lack of further details, I'm going to close this. Please reopen if further details can be provided.
