### ISSUE TITLE
Provider variable interpolation error during import

### ISSUE THREAD

**Issue by kladiv** [phillbaker/terraform-provider-elasticsearch#23]
Hello,
i'm my actual scenario i got an error during import of an AWS API Gateway resource due to elasticsearch provider issue:

```
$ terraform import aws_api_gateway_rest_api.APIGW-FE <apigw_id>
Acquiring state lock. This may take a few moments...

Error: Provider "elasticsearch" depends on non-var "aws_elasticsearch_domain.ES-DOMAIN-5.0/aws_elasticsearch_domain.ES-DOMAIN-5.N". Providers for import can currently
only depend on variables or must be hardcoded. You can stop import
from loading configurations by specifying `-config=""`.

```

It seems the provider does not support variable interpolation.
Below our provider configuration:

```
  provider "elasticsearch" {
    url = "https://${aws_elasticsearch_domain.ES-DOMAIN-5.endpoint}"
    aws_access_key = "${aws_iam_access_key.ES.id}"
    aws_secret_key = "${aws_iam_access_key.ES.secret}"
    insecure = true
    version = "0.6.0"
  }
```

Are you able to resolve this issue?
Thank you

Best Regards,
Claudio

**Comment by phillbaker** [comment]
Hi @kladiv sorry for the slow reply here. Looks like this is a limitation of terraform: https://github.com/hashicorp/terraform/issues/17847

For the meantime, I'd suggest hardcoding the credentials for ES while importing or commenting those lines out.

**Comment by williamsbdev** [comment]
@kladiv - I also use AWS ES and instead of providing my AWS Access/Secret key via the provider, I set the bash environment variables so that they are not committed to code.

@phillbaker - I think we should close this is as I don't think this is something that could be done.

**Comment by phillbaker** [comment]
Yup, fair enough.

**Comment by john-delivuk-rl** [comment]
Created #119 to address
