### ISSUE TITLE
Add support for data stream resources

### ISSUE THREAD

**Issue by applike-ss** [phillbaker/terraform-provider-elasticsearch#230]
I would like to be able to manage elasticsearch data streams with this terraform provider.

See: https://www.elastic.co/guide/en/elasticsearch/reference/current/set-up-a-data-stream.html

Is there any chance to get this?

**Comment by phillbaker** [comment]
Hello, as that guide suggests, datastreams are typically created with index templates. If you'd like to do that, please see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/159 which shows that it is currently possible, but does have a permanent diff in the terraform output currently.

**Comment by applike-ss** [comment]
Interesting, i must have missed that somehow. My assumption was that the data stream would have to be manually created, but in fact the datastream object will be automatically created once the first log comes in. Just tested that in our test system and indeed that was the behaviour i got. :+1:
