### ISSUE TITLE
Elastic cloud with kibana alert

### ISSUE THREAD

**Issue by shrey-rajvanshi** [phillbaker/terraform-provider-elasticsearch#236]
I'm trying this out against an Elastic Cloud deployment. The index_template resource works perfectly. But when I try applying a `elasticsearch_kibana_alert` resource, I get the following error:

`Error: no active connection found: no Elasticsearch node available`

My provider configuration:
```
provider "elasticsearch" {
  url = "https://XXXX.XX-XXXXX-1.aws.cloud.es.io:9243"
  username = var.elasticsearch_user
  password = var.elasticsearch_password
  sniff = false
  insecure = true
}
```

Resources:

```
resource "elasticsearch_index_template" "test" {
  name = "terraform-test"
  body = <<EOF
{
  "template" : "test-*",
  "settings" : {
    "index" : {
      "refresh_interval" : "30s"
    }
  }
}
EOF
}
```
Just this resource works. Only when I add  the`elasticsearch_kibana_alert` below, I receive the error.

```
resource "elasticsearch_kibana_alert" "test" {
  name = "terraform-alert"
  schedule {
    interval = "1m"
  }
  conditions {
    aggregation_type     = "avg"
    term_size            = 6
    threshold_comparator = ">"
    time_window_size     = 5
    time_window_unit     = "m"
    group_by             = "top"
    threshold            = [1000]
    index                = [".test-index"]
    time_field           = "@timestamp"
    aggregation_field    = "sheet.version"
    term_field           = "name.keyword"
  }
  actions {
    id             = "c87f0dc6-c301-4988-aee9-95d391359a39"
    action_type_id = ".index"
    params = {
      level   = "info"
      message = "alert '{{alertName}}' is active for group '{{context.group}}':\n\n- Value: {{context.value}}\n- Conditions Met: {{context.conditions}} over {{params.timeWindowSize}}{{params.timeWindowUnit}}\n- Timestamp: {{context.date}}"
    }
  }
}
```

Terraform version: v0.13.7
Provider version: 1.6.0

I'm pretty confident the elastic connection works, since index_template is created fine. Could someone please share an example of how a kibana_alert resource is being used.

**Comment by phillbaker** [comment]
Whoops, it looks like we missed it in the documentation, but the `kibana_url` attribute needs to be set on the provider: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/ffe6242df872ecff74bf5e7d2eeaead1db672261/es/provider.go#L75-L80.

Please let me know if that fixes the issue.
