### ISSUE TITLE
Support opensearch

### ISSUE THREAD

**Issue by amirkkn** [phillbaker/terraform-provider-elasticsearch#237]
I'm trying to use this terraform provider for provisioning opensearch roles and other configs, which was deployed on top of the kubernetes using[ official helm chart](https://github.com/opensearch-project/helm-charts). I don't use the AWS opensearch.

Terraform detects my elasticsearch cluster and the connection is established successfully, but I get the error during terraform apply:

`Error: ElasticSearch version 1.2.3 is older than 6.0.0 and is not supported.`

Is any plan to support opensearch in the near future?

Thanks in Advance

-------
Opensearch helm chart: 1.5.7
Opensearch app version: 1.2.3
Terraform elasticsearch provider version: 2.0.0-beta.2

**Comment by phillbaker** [comment]
Please see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/218, enabling compatibility mode on the cluster before using the provider should enable almost all features immediately.
