### ISSUE TITLE
Elasticsearch resources updates fail leads to credential leak 

### ISSUE THREAD

**Issue by pbygrave-lucid** [phillbaker/terraform-provider-elasticsearch#239]
Provider version 2.0.0-beta.2

Running terraform via Jenkins, I encountered an issue yesterday where the provider failed to update 2 elasticsearch index patterns. While the error was seemingly a one-off and the code applied successfully on 2nd attempt, the original failure message prints out several bits of information about the failed request, 1 of which is the IAM cluster admin username (fine) but the other is the user's access key and secret access key, which is a potential security risk.

Unfortunately I can't provide build logs as well only keep the last 10 in what is a busy environment, but could this be looked at as a security risk? Ideally the secret access key value would be obsfucated by default.

**Comment by phillbaker** [comment]
Thanks for opening an issue. Can you please include the following:
* terraform version
* elasticsearch version (and opendistro version if relevant)

>  the original failure message prints out several bits of information about the failed request, 1 of which is the IAM cluster admin username (fine) but the other is the user's access key and secret access key, which is a potential security risk.

What are the settings of `TF_LOG` and/or `TF_LOG_PROVIDER`?

Please provide a redacted version of the logs so that we can pinpoint what resource and/or library was doing the logging.

**Comment by phillbaker** [comment]
Hello, I'm going to close this issue as no further information has been provided and the describe issue isn't reproducible with the given information. Please provide additional details and reopen when you have a chance.
