### ISSUE TITLE
Support for elasticsearch pipelines?

### ISSUE THREAD

**Issue by davidmarkstartapp** [phillbaker/terraform-provider-elasticsearch#24]
Hi @phillbaker

Thanks for this amazing repo!

We currently use gitlab and CI capabilities to store our index / pipeline templates and it will be nice if this provider will support also pipelines resources.

Also, different question, how the json validation is performed during plan / apply?

Thanks
D.

**Comment by phillbaker** [comment]
> will be nice if this provider will support also pipelines resources

Good idea! It looks like they're stored at `ES_HOST//_ingest/pipeline/<pipeline>` and created via a `PUT`. Could probably model these off of some of the existing resources.

> how the json validation is performed during plan / apply

A good question are you seeing errors for invalid json? If i had to guess, it'd be coming back from elasticsearch itself.

**Comment by phillbaker** [comment]
Done in #29
