### ISSUE TITLE
elasticsearch_opendistro_role: support multiple index_permissions

### ISSUE THREAD

**Issue by arminfelder** [phillbaker/terraform-provider-elasticsearch#240]
in opendistro security, you can have multiple index_permissions in one role, therefor 
  
index_permissions 
and
tenant_permissions 

should be arrays

**Comment by phillbaker** [comment]
This is currently possible, they're just specified multiple times. 

See the example here: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/8dc8899c146c078fbe96c112b1b868a17bf30bcc/es/resource_elasticsearch_opendistro_role_test.go#L259-L297
