### ISSUE TITLE
Deprecated resource warning for opensearch resources 

### ISSUE THREAD

**Issue by ngamber** [phillbaker/terraform-provider-elasticsearch#242]
Hi, 

I get a deprecation warning on the latest 2.0.0-beta.3:

│ Warning: Deprecated Resource
│
│   with elasticsearch_opendistro_role.api,
│   on api_roles.tf line 2, in resource "elasticsearch_opendistro_role" "api":
│    2: resource "elasticsearch_opendistro_role" "api" {
│
│ elasticsearch_opendistro_role is deprecated, please use opensearch_role resource instead.
│
│ (and 20 more similar warnings elsewhere)

If I change each instance of "elasticsearch_opendistro_x" to "opensearch_x" as suggested, I get the following warning, as this causes terraform to try and use a non-existent provider for these resources:

│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider hashicorp/opensearch: provider
│ registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/opensearch

$ terraform --version
Terraform v1.1.2

**Comment by phillbaker** [comment]
Whoops, that's certainly a bug. Thanks for opening an issue. I'll take a look in the next day or so.

**Comment by Dmitry9292** [comment]
Also this bug related to other resources as well. Tried to create tenant and get this error:

│ Warning: Deprecated Resource
│ 
│   with elasticsearch_opendistro_kibana_tenant.tenant,
│   on main.tf line 17, in resource "elasticsearch_opendistro_kibana_tenant" "tenant":
│   17: resource "elasticsearch_opendistro_kibana_tenant" "tenant" {
│ 
│ elasticsearch_opendistro_kibana_tentant is deprecated, please use
│ opensearch_kibana_tenant resource instead.
│ 
│ (and 2 more similar warnings elsewhere)
│ Error: ElasticSearch version 1.2.3 is older than 6.0.0 and is not supported.
