### ISSUE TITLE
beta.4 not showing up on Terraform Registry

### ISSUE THREAD

**Issue by BGarber42** [phillbaker/terraform-provider-elasticsearch#247]
Ran into the issue with terraform trying to use the `opensearch` provider for the renamed resources instead of this provider, `init -upgrade` won't pick it up since it's missing from the registry

**Comment by phillbaker** [comment]
Hm, very odd. I see a successful upload here: https://github.com/phillbaker/terraform-provider-elasticsearch/runs/4994626356?check_suite_focus=true and a retry fails due to it already being uploaded: https://github.com/phillbaker/terraform-provider-elasticsearch/actions/runs/1767296644

**Comment by phillbaker** [comment]
Requested a resync on the terraform site, it's there now: https://registry.terraform.io/providers/phillbaker/elasticsearch/2.0.0-beta.4
