### ISSUE TITLE
support `execute-api` AWS signatures

### ISSUE THREAD

**Issue by moritzzimmer** [phillbaker/terraform-provider-elasticsearch#248]
Hi @phillbaker ,

we are using Amazon OpenSearch service with clusters deployed to VPCs. In order to manage the cluster via API, we use a proxy deployed as AWS HTTP gateway + Lambda function, secured by [IAM](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_route#authorization_type) authorization. Thus, requests to that API proxy need to use `execute-api` in the [signing client](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/c5bee9397368416484257e07f15612d039ff950f/es/provider.go#L580).

Wondering if we could make this configurable for the provider (defaulting to `es`)?

**Comment by phillbaker** [comment]
hi @moritzzimmer, happy to review a PR for that.
