### ISSUE TITLE
Got health ckech error with disabled health check

### ISSUE THREAD

**Issue by ppcololo** [phillbaker/terraform-provider-elasticsearch#249]
Hello @phillbaker 
We disabled health check in provider block but still have network issue with health check

provider config

provider "elasticsearch" {
  url                                 = "https://${aws_elasticsearch_domain.es.endpoint}"
  aws_assume_role_arn   = "some_role"
  sign_aws_requests       = true # only needs to be true if your domain access policy includes IAM users or roles
  insecure                       = true # to bypass certificate check
  healthcheck                 = false
  elasticsearch_version = "7.10"
}

plugin version: `2.0.0-beta.4`

error:
`Error: HEAD healthcheck failed: This is usually due to network or permission issues. The underlying error isn't accessible, please debug by disabling healthchecks.`

Seems with disabled health check parameter plugin still wants to check ES cluster

**Comment by ppcololo** [comment]
I was TGW network issue between 2 AWS accounts...
Resolved by Network team

**Comment by nicohouillon** [comment]
I have the same issue
