### ISSUE TITLE
failing with Head  context deadline exceeded

### ISSUE THREAD

**Issue by sabrish72** [phillbaker/terraform-provider-elasticsearch#250]
We have enabled SAML and aws managed elastisearch version is opensearchv1.1.
I am using basic auth and saml enabled with below configuration and we also have custom domain enabled.
```
provider "elasticsearch" {
  url = "https://${aws_elasticsearch_domain.this.endpoint}"
  username = var.advanced_security_options.master_user_options.master_user_name
  password = var.advanced_security_options.master_user_options.master_user_password
  sign_aws_requests = false
  insecure = true
}
```
tf version: Terraform v1.0.6 on darwin_arm64
```
terraform {
  required_providers {
    elasticsearch = {
      source = "phillbaker/elasticsearch"
      version = "2.0.0-beta.4"
    }
  }
}
```
resource: elasticsearch_index_template

**Comment by sabrish72** [comment]
Does this plugin support opensearch version 1.1 ?

**Comment by phillbaker** [comment]
Please see the README for supported versions.

This issue seems similar to #217, SAML authentication in these cases is
used to log into Kibana/Dashboards, not the underlying cluster. You’ll need
IAM credentials to manage the cluster.

**Comment by phillbaker** [comment]
Going to close this, please reopen if you have further information to shre.
