### ISSUE TITLE
[FR] Add support for SIEM Exception Lists

### ISSUE THREAD

**Issue by operatorequals** [phillbaker/terraform-provider-elasticsearch#256]
Hello :)

First of all, this provider has saved an enormous amount of clicks in my life. Thank you tremendously!

As my main job is on SIEMs and I use Elastic SIEM quiet a lot, part of my obsession is about making everything about a SIEM as-code.

I have successfully done this with Ingestion PIpelines and Index Templates with this provider, the SIEM Rules part with Elastic's official repo [1], and I'd love to also do the SIEM Rule exceptions as-code.

----

My thought is to **extend this provider** to also support the `exception_list` and `exception_item` Kibana objects.

This does not currently work, by using a different body in the `resource` `elasticsearch_kibana_object` [2] as it only pushes `documents` to `.kibana` Index Alias (as seen in the provider code [3]).

As Elastic documentation explains [4], the Exception Kibana Objects need to be stored in the `.items`and `.lists` Elasticsearch Indices.
So theoretically fiddling with the Kibana Objects to not get stored in `.kibana` but in the aforementioned indices could support the Exception creation without too much blood getting drawn :) . And by blood I mean actually implementing the Kibana API to the resource (but using the existing JSON `body`).

----

What do you think? Is it doable?

[1] : https://github.com/elastic/detection-rules
[2] : https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/kibana_object
[3] : https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/es/resource_elasticsearch_kibana_object.go#L71
[4] : https://www.elastic.co/guide/en/security/current/exceptions-api-overview.html

**Comment by phillbaker** [comment]
Hi @operatorequals, that is what the existing `index` attribute on the `elasticseach_kibana_object` is intended to do: https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/kibana_object#index

Could you take a look at that and let me know if it resolves your need?

Otherwise, happy to talk more about implementing these as actual resources using the kibana api, in theory, that is a long term goal: https://github.com/phillbaker/terraform-provider-elasticsearch/issues/92

**Comment by operatorequals** [comment]
I don't know how I missed that :)
I'll try that and come back to you!

**Comment by phillbaker** [comment]
Going to close this as it seems to be solved using existing features. Please reopen if further issues.

**Comment by operatorequals** [comment]
I created a Terraform Provider for SIEM rules and exceptions:
https://github.com/operatorequals/terraform-provider-elastic-siem
