### ISSUE TITLE
Create index w/o number of shards

### ISSUE THREAD

**Issue by moritzzimmer** [phillbaker/terraform-provider-elasticsearch#257]
We are using index templates to configure the number of shards/replicas for new indices matching a pattern. 

example:

```json
{
  "index_patterns": [
    "foo-*"
  ],
  "settings": {
    "number_of_shards": 3,
    "number_of_replicas": 1
  }
}
```

Creating a new index via [API](https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/create-index/) `foo-bar` pics up those settings. Creating new indices with `elasticsearch_index` in terraform sets `number_of_shards` to `1` (or the configured number for this ressource).

Would it be possible to use `elasticsearch_index` without defaulting to a number of shards so the configuration from the index template is picked up?

**Comment by phillbaker** [comment]
Thanks for opening an issue. It sounds like the request is to remove the default here: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/420462a96e729e7ad209044c72cd096835aeeae7/es/resource_elasticsearch_index.go#L93-L99, is that accurate?

**Comment by moritzzimmer** [comment]
I guess so @phillbaker - Open/ElasticSearch should use the default or template settings.

**Comment by phillbaker** [comment]
Done in d9d2916be84b814f679adf699ba4225086e8a1a4
