### ISSUE TITLE
checksum issue

### ISSUE THREAD

**Issue by sangeethdba** [phillbaker/terraform-provider-elasticsearch#266]
terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of phillbaker/elasticsearch...
- Installing phillbaker/elasticsearch v2.0.0...

Error: Failed to install provider

Error while installing phillbaker/elasticsearch v2.0.0: archive has incorrect
checksum zh:1d8ec7764eb2ee22643c0a51bc55ff32745a4b77ecc10dc2d4bee90f6c65917e
(expected zh:29dd759a17e60f2f514a94e862c37f4ec4bd54f997a2cec3764186e9b0c4a486)

tried various other versions ,all versions i tried is getting this checksum error

**Comment by sangeethdba** [comment]
@phillbaker

**Comment by phillbaker** [comment]
Please include the version of terraform, OS and architecture of the machine
on which you are seeing this.

**Comment by sangeethdba** [comment]
Tried all tf versions above 13+ and errors occurred on Mac OS

**Comment by sangeethdba** [comment]
@phillbaker any clue.appreciate the help.

**Comment by sangeethdba** [comment]
mac os monterey

**Comment by phillbaker** [comment]
Hello - just following up on this, as I'm not able to reproduce it using teraform `0.13.2` or `1.0.9`.

Some suggestions on stackoverflow include various permutations of `terraform init -reconfigure` and `terraform lock`
* https://stackoverflow.com/questions/57294024/terraform-init-unable-to-verify-checksum
* https://stackoverflow.com/a/67204812

This doesn't seem like a provider specific issue.

**Comment by sangeethdba** [comment]
Yes it is not a provider issue.our machines are behind some proxies and while downloading some sort of corruption or partial file download causing this  issue
