### ISSUE TITLE
elasticsearch_opensearch_role resource errors 

### ISSUE THREAD

**Issue by niladriforu** [phillbaker/terraform-provider-elasticsearch#270]
I am getting : 
Error: rpc error: code = Unavailable desc = transport is closing

when I deploy from jenkins. 

resources I am deploying : 

elasticsearch_opensearch_role
elasticsearch_opensearch_roles_mapping

One more thing : When we search documentaion, it tells us to create elasticsearch_opendistro_role instead of opensearch. Only when we get the error message, we know it needs to be opensearch.

**Comment by phillbaker** [comment]
Hi @niladriforu, I'm going to close this as a dupe of https://github.com/phillbaker/terraform-provider-elasticsearch/issues/251.

Thanks for the reminder about the docs, I'll get those updated.
