### ISSUE TITLE
Help required importing or renaming Elasticsearch provider based modules in terraform on AWS

### ISSUE THREAD

**Issue by olivierots** [phillbaker/terraform-provider-elasticsearch#272]
Hello @phillbaker ! Thank you for your provider, it's really helpful!

I have recently faced a few issues with it at work and need your assistance please 
we currently have a few modules that deploy 3 Logstash deployments & elasticsearch clusters using modules such as rbac, logstash, rbac, elasticsearch, index mappings & Logstash pipelines.

We now want to split these modules into two (Dev/Test & PROD) so that we can deploy new changes to Dev first before PROD in order to comply with the change control strategy  as at the moment we are doing it all at the same time which is goes against our change process.

We've split these modules using a count so that TF is able to differentiate between PROD & DEV
here is a code snippet for ILM only but i am happy to provide you with the entire code for the other modules if required.

<img width="722" alt="image" src="https://user-images.githubusercontent.com/13032092/166722098-66a88d8d-8860-4ede-a391-9917548fe1f8.png">

```
== ILM module (PROD) ==
module "logs-ilm-policy" {
  count                    = local.is_prod ? 1 : 0
  source                   = "git@XXX/XXX//index-lifecycle-management?ref=2.11.0"
  account_name             = var.account_name
  ilm_policy_hot_warm_cold = var.ilm_policy_hot_warm_cold
  ilm_policy_hot_warm      = var.ilm_policy_hot_warm
  ilm_warm_days            = var.ilm_warm_days
  ilm_warm_shards          = var.ilm_warm_shards
  ilm_cold_age             = var.ilm_cold_age

  providers = {
    elasticsearch = elasticsearch.prod
  }
}
```
```
== ILM module (DEV) ==
module "logs-ilm-policy-dev" {
  count                    = local.is_prod ? 0 : 1
  source                   = "git@XXX/XXX//index-lifecycle-management?ref=2.11.0"
  account_name             = var.account_name
  ilm_policy_hot_warm_cold = var.ilm_policy_hot_warm_cold
  ilm_policy_hot_warm      = var.ilm_policy_hot_warm
  ilm_warm_days            = var.ilm_warm_days
  ilm_warm_shards          = var.ilm_warm_shards
  ilm_cold_age             = var.ilm_cold_age

  providers = {
    elasticsearch = elasticsearch.non_prod
  }
}
```
```
== locals.tf ==
logs_ilm_policy = local.is_prod ? module.logs-ilm-policy.ilm_policy_name : module.logs-ilm-policy-dev[0].ilm_policy_name

```

and we have been hitting the below errors on all elasticsearch related modules:
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/13032092/166726215-71d45f12-cad0-45c9-ab0f-a2244a5eeea7.png">
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/13032092/166726281-5ad008b7-f6f6-4a57-a87e-44aa866611ba.png">
<img width="964" alt="image" src="https://user-images.githubusercontent.com/13032092/166726325-09dd16dd-3428-4b01-b385-230a5f03dd35.png">

The only way to bypass these errors was to remove all these modules our build has been complaining about from the state files and re-run a new build which then gives us something like the below but obviously this is quite a critical infrastructure and we cant really afford any downtime and do not want stuffs to be recreated.

<img width="604" alt="image" src="https://user-images.githubusercontent.com/13032092/166725246-48e4e8a5-c691-437f-ad12-ce7720f47c27.png">

we aren't too confident trying to mess with the state files and importing these modules and wondered whether your provider has any best practices or better ways of importing these new modules ? or even better ways of achieving the desired outcome.

Thanks in advance

**Comment by phillbaker** [comment]
Hello,

> We've split these modules using a count so that TF is able to differentiate between PROD & DEV


> we aren't too confident trying to mess with the state files and importing these modules

Based on my understanding of how terraform works, you can't do one without the other unfortunately. I'm not quite following what happened, but if the resources were moved between modules then it's expected that terraform state will have to move in a corresponding way.

> and wondered whether your provider has any best practices or better ways of importing these new modules ?

I don't think this is specific to this provider, but a general terraform question. I don't have much to offer for this specific provider.

Given that this doesn't seem like a provider specific issue, without further details I'll close this issue in a few days.

**Comment by olivierots** [comment]
Hi @phillbaker, thanks for your prompt response !

We've looked to use tf mv, to move the resources to under a new module & we still get the "no active connection found" error though the elasticsearch clusters are up & running fine.

As this hasn't worked, we will look to refactor our code, by removing the module from state, and then look to use a terraform import against the infrastructure. To carry out this import, we need to know how to your provider works, in regards to importing infrastructure.

Thanks

**Comment by phillbaker** [comment]
> we still get the "no active connection found" error though the elasticsearch clusters are up & running fine.

Hi @olivierots, my guess is that the provider isn't configured correctly for the module, please see the terraform docs here: https://www.terraform.io/language/modules/develop/providers

> To carry out this import, we need to know how to your provider works, in regards to importing infrastructure.

I see now that most xpack resource docs are missing import examples. They work very similarly to the resources that _do_ have import examples, e.g.  https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/opendistro_user#import

The form is `terraform import <resource path>.<name> <id or name of resource>`

**Comment by phillbaker** [comment]
The import examples have been added in afaaca57520242e8da2e1a16805ad326ed87465f, I'm going to close this issue now. Please re-open if there are provider specific issues.
