### ISSUE TITLE
Audit log resource

### ISSUE THREAD

**Issue by rm-hull** [phillbaker/terraform-provider-elasticsearch#273]
Hi @phillbaker, am i right in thinking there is no terraform resource that can handle `GET/PUT _plugins/_security/api/audit/config` on as per [AWS docs on audit log API](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/audit-logs.html#audit-log-rest-api) ?

Would you be open to accepting a PR to add this capability?

**Comment by phillbaker** [comment]
Hi @rm-hull, that's correct, nothing today manages that.

A PR for it would be great. Please see https://github.com/phillbaker/terraform-provider-elasticsearch/pull/264 for a good example. What do you think of naming it `elasticsearch_opensearch_audit_config`?

**Comment by phillbaker** [comment]
> I was contemplating creating attributes for each value rather than a big wall of json - assume that is a better way of representing the config.

Yes please, the more recent resources do this, that's preferred.
