### ISSUE TITLE
kibana_url and opensearch dashboard/kibana with SAML

### ISSUE THREAD

**Issue by danielmotaleite** [phillbaker/terraform-provider-elasticsearch#275]
Hi

i'm new to aws opensearch and i'm having some trouble applyting this terraform

I have a test aws opensearch cluster, with a kibana enable SAML (otka). I can login using the browser, after the okta external authentication is done. I also have a basic auth admin
Now i added in to the terraform this:

```
provider "elasticsearch" {
  url = "https://vpc-logs-staging-xxxx-eu-central-1.es.amazonaws.com"
  kibana_url = "https://vpc-logs-staging-xxxx.eu-central-1.es.amazonaws.com/_dashboards"
  username = "admin"
  password = "XXXX"
  healthcheck = false
  sniff = false
}
```

The plan always work fine, and I can change the opensearch cluster config, but all kibana related changes (eg: terraform apply) i hit this error:
```
elasticsearch_opensearch_ism_policy.warm-cleanup: Creating...
╷
provider.terraform-provider-elasticsearch_v2.0.1: 2022/05/17 04:45:44 [INFO] Pinging url to determine version https://vpc-logs-staging-xxxxx.eu-central-1.es.amazonaws.com:
│ Error: HTTP 403 Forbidden: Permission denied. Please ensure that the correct credentials are being used to access the cluster.
```
So looks like pinging kibana fails, where i assumed it would work, as i have the user+password for basic auth

So any hint how to solve this? what should be the kibana_url? any special API path got this to work?
If not, is this provider using the user+password for basic auth kibana? or am i badly understanding how this works?

**Comment by phillbaker** [comment]
Hello - to clarify, kibana SAML credentials do not work with authenticating to the underlying ES API, see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/217. Please see the docs for AWS authentication options: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/docs/index.md#AWS-authentication

The `kibana_url` is used only for kibana-specific resources like kibana_alert.

**Comment by danielmotaleite** [comment]
ok, thanks for the reply
yes, i know that this terraform can't use SAML, but as you said kibana_url was only for some resources, i tried disable SAML and use only basic auth to see if it worked... and still fail to work
so i'm having a problem somewhere else... i'm not using any aws auth, as we will rely on the SAML

OK, i think i found the problem, looks like i need to set 
`sign_aws_requests = false`
i'm not  using any of the aws methods, i'm using basic auth and that setting looks like it was the one that allowed me to talk with the opensearch cluster. not totally sure if other cleanups i have done helped too

So i think this can be closed now
again, thanks for the help
