### ISSUE TITLE
Provider Configuration: ENV vars take precedence over explicit basic auth pair

### ISSUE THREAD

**Issue by olafnorge** [phillbaker/terraform-provider-elasticsearch#289]
Hi, I've an issue configuring the provider properly. In my setup I have `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, and `AWS_SESSION_TOKEN` set in my environment. These are used to assume into a specific deployment role. The search cluster is not accessible through that role but by a master user and password.

The master user and password I configure in the provider setup like so:
```
provider "elasticsearch" {
  password = "password"
  url      = "https://some-endpoint.example.com"
  username = "master-user"
}
```

When I run apply the module takes the AWS related env vars instead of the configured username and password. Currently I need to work around this by configuring the aws provider and the storage backend manually and by unsetting the env vars.

Am I doing something wrong or is this the expected behavior?

**Comment by phillbaker** [comment]
Hello - this is expected behavior. You can set `sign_aws_requests` to false to disable AWS authentication in the provider.

**Comment by phillbaker** [comment]
I'm going to close this issue out, please reopen if there are further aspects to clarify.
