### ISSUE TITLE
[Discussion] Official HashiCorp verification status

### ISSUE THREAD

**Issue by jackson-theisen** [phillbaker/terraform-provider-elasticsearch#299]
I noticed that this provider was [initially PR'd to HashiCorp's official Terraform repository ](https://github.com/hashicorp/terraform/pull/13238) back when all of their 'Official' providers were managed within that repository. They've since refactored their approach a bit and now manage 'official' providers in their own repository within the [HashiCorp organization](https://github.com/hashicorp).

I wanted to inquire around whether there are any plans to either submit this repo to https://github.com/opensearch-project and get it verified by HashiCorp through their [partnerships](https://www.terraform.io/docs/partnerships) program, or potentially even submit it as an official provider to be owned and maintained by HashiCorp.

@phillbaker deserves to be recognized for his efforts on this project, but since it is by far the best solution out there today that is compatible with OpenSearch, it'd be awesome to see this get some official recognition. Selfishly, I would also like this to become officially recognized so I don't have to deal with any red tape in an enterprise setting. @phillbaker - what are your thoughts on this? I'd be happy to help with anything necessary to make this happen.

- https://www.terraform.io/registry/providers#provider-tiers-namespaces
- https://www.terraform.io/docs/partnerships

**Comment by phillbaker** [comment]
Hi @jackson-theisen, not opposed to transferring ownership on my side, if there is corresponding interest on the opensearch-project side and maintainers willing to take that on.

If you'd be able to shepherd that process through, I'm open to it!

**Comment by jackson-theisen** [comment]
@phillbaker I really admire your willingness to transfer the ownership. I'd be happy to attempt to shepherd the process through but will likely need to reach out to you around any opinionated changes that might be requested. Mainly, my concern is that if we want https://github.com/opensearch-project to adopt it, they'll want it branded as opensearch-specific. In my personal opinion, shifting the focus to solely supporting OpenSearch would be a good idea as the elasticsearch community has their own provider out now: https://github.com/elastic/terraform-provider-ec. Shame that the community wound up so divided on this topic, but it is what it is at this point. Will reach out to opensearch-project maintainers today to take their temperature on adopting this project.

**Comment by elfisher** [comment]
hey @phillbaker and @jackson-theisen, @bbarani and I are from the OpenSearch Project. We will look into creating a repo in the OpenSearch org for a terraform provider. Would one of you be willing to create a PR into the repo using this content once we have it setup?

**Comment by bbarani** [comment]
Thanks @elfisher . @phillbaker @jackson-theisen Do you have any preference on the repo name? Listing some options here.. terraform-provider-opensearch | terraform-provider-for-opensearch | opensearch-terraform-provider

**Comment by jackson-theisen** [comment]
Hey @elfisher and @bbarani, thanks for being so quick to respond on this request! To add some context, I am currently not a contributor on this repo and have no affiliation to @phillbaker outside of this request. I'm certainly planning to get more involved as the incentive behind my request was actually so I could begin using this provider (TLDR; red tape around unofficial providers). 

That said, it seems like @phillbaker is fully on board with the migration as long as I would handle the more administrative tasks around the process. I'll take point on submitting a PR to the repo that you guys create. The only changes that I'd make would be anything necessary to meet compatibility requirements with the official terraform registry (unlikely that any will be needed). Here's a couple references that i'll be using to validate the code before submitting the PR:

- https://www.terraform.io/docs/partnerships#terraform-provider-integrations
- https://github.com/hashicorp/terraform-plugin-docs

Regarding naming, `terraform-provider-opensearch` is the clear winner imo (@phillbaker should get final say) as that is the standard convention across the Terraform community. As I previously mentioned, I also think that the future of this provider should strictly focus on OpenSearch compatibility. While it currently supports both OpenSearch and ElasticSearch, it makes sense to deprecate support for anything specific to the latter as https://github.com/elastic/terraform-provider-ec will become the primary tool in that regard. @phillbaker please let me know if you're ok with this and I'll plan to include a note about the shift in focus in the README of the initial PR to the new repo.

**Comment by elfisher** [comment]
> Regarding naming, `terraform-provider-opensearch` i

For what it is worth I also do like this name!

**Comment by phillbaker** [comment]
Hi all, 

Regarding naming, yes `terraform-provider-opensearch` is the convention and we should stick with that.

> the future of this provider should strictly focus on OpenSearch compatibility. While it currently supports both OpenSearch and ElasticSearch, it makes sense to deprecate support for anything specific to the latter as https://github.com/elastic/terraform-provider-ec will become the primary tool in that regard. @phillbaker please let me know if you're ok with this and I'll plan to include a note about the shift in focus in the README of the initial PR to the new repo.

Agreed here as well. I'll update this existing repository to deprecate opendistro/opensearch resources in favor of the new provider once we get it released. I'll continue to maintain elasticsearch 7.x resources in this repository.

Please let me know what I can do to help.

**Comment by bbarani** [comment]
Thanks for the update @phillbaker. I will update this thread once the repo `terraform-provider-opensearch` is created under OpenSearch organization.

**Comment by bbarani** [comment]
@phillbaker @jackson-theisen I apologize for the delay. `terraform-provider-opensearch` [repo](https://github.com/opensearch-project/terraform-provider-opensearch) has been created under OpenSearch project. I will send the maintainer invitation to your GitHub handle soon. Please let me know if you have any other questions. CC: @elfisher @chenkle

**Comment by phillbaker** [comment]
Thanks, @bbarani, I received the invitation. It doesn't look like I have permissions, but please make sure that github actions is enabled for the repository.

**Comment by bbarani** [comment]
@phillbaker Thanks for accepting the invite. You should have necessary permission to view GitHub actions tab now.

**Comment by phillbaker** [comment]
Hi @bbarani, workflows don't seem to be enabled. Please see https://github.com/opensearch-project/terraform-provider-opensearch/pull/7 - I can't access https://github.com/opensearch-project/terraform-provider-opensearch/settings/actions, but that's where it would be enabled.

**Comment by phillbaker** [comment]
@bbarani checking in here - this is preventing progress on getting the first PR merged. 

As well, we'll need:
* set up a terraform provider / account at https://registry.terraform.io/publish/provider
* access to set github actions secrets so that we can push to the hashicorp terraform registry
