### ISSUE TITLE
Terraform Provider for ECE

### ISSUE THREAD

**Issue by mattcsg** [phillbaker/terraform-provider-elasticsearch#30]
Hi Phill, just an update that I've created a new provider for Elastic Cloud Enterprise (ECE) to support creation of ECE clusters. I'm not sure if you're using ECE, but it might be useful if you are:

https://github.com/Ascendon/terraform-provider-ece

I'm also planning to look at adding some additional capabilities to this provider for some upcoming use cases.

Matt

**Comment by phillbaker** [comment]
Cool! I'm not currently using ECE, but the provider looks good. If you have any issues integrating the outputs of your provider into this one, please open an isue!

**Comment by phillbaker** [comment]
Thanks @mattcsg. Going to close this for now, looking forward to any additional PRs!
