### ISSUE TITLE
Using role write for creating multiple roles

### ISSUE THREAD

**Issue by jay2242** [phillbaker/terraform-provider-elasticsearch#300]
https://registry.terraform.io/providers/phillbaker/elasticsearch/latest/docs/resources/opensearch_role
Example here creates single role, I would like to create multiple roles and later map them using "elasticsearch_opendistro_role.writer.id" , How can I do that?
Thanks

**Comment by phillbaker** [comment]
Hi @jay2242, I'm not sure I'm understanding the question, but creating multiple resources and referencing them seems like a general practice in terraform. There are good guides on the terraform site about how to use HCL: https://learn.hashicorp.com/tutorials/terraform/count. Each role can be referenced by its own id.

**Comment by jay2242** [comment]
Thanks, it worked "writer" is just a label for elasticsearch_opendistro_role
