### ISSUE TITLE
Release new version of provider for xpack role bug fix

### ISSUE THREAD

**Issue by maxhand-98** [phillbaker/terraform-provider-elasticsearch#301]
Please could you release a new version of the provider as I am particularly interested in the commit below which will hopefully allow me to avoid deleting old xpac roles for every deployment that we have.

https://github.com/phillbaker/terraform-provider-elasticsearch/commit/7af7307bbf238a458269d0c0e6c2fc7368207fe4

**Comment by phillbaker** [comment]
Whoops, that's my mistake. https://github.com/phillbaker/terraform-provider-elasticsearch/tree/v2.0.4 is released
