### ISSUE TITLE
add support for GP3 type volume

### ISSUE THREAD

**Issue by slawa-c** [phillbaker/terraform-provider-elasticsearch#302]
I try to change volume type to GP3 but got error:
```
expected ebs_options.0.volume_type to be one of [standard gp2 io1], got gp3

  on es-domain.tf line 94, in resource "aws_elasticsearch_domain" "es_kibana":
  94:     volume_type = "gp3"
```

**Comment by phillbaker** [comment]
Hi @slawa-c, did you mean to report this as an error with the [official AWS terraform provider](https://github.com/hashicorp/terraform-provider-aws)? This provider interacts with Elasticsearch itself which does not control the underlying storage of a ES cluster.

I'm going to close this issue for now, please re-open if it's relevant to this provider and provider more details.
