### ISSUE TITLE
error creating user: &{403 map[Access-Control-Allow-Origin:[*] Content-Length:[333] Content-Type:[application/json; charset=UTF-8]

### ISSUE THREAD

**Issue by nirsv** [phillbaker/terraform-provider-elasticsearch#304]
I am using AWS Opensearch with Saml enabled and whatever I try to do I get error 403.

I tried using `aws_assume_role_arn`, `aws_profile`, master username and password all the combination but I always get this error 403.

Maybe the provider is not supported for AWS Opensearch with enabled SAML ?

**Comment by phillbaker** [comment]
Hello - Kibana SAML credentials do not work with authenticating to the underlying ES API, see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/217. Please see the docs for AWS authentication options: https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/docs/index.md#AWS-authentication

**Comment by nirsv** [comment]
@phillbaker So how can I authenticate?
Itried all the optiions (master username and password/ Using my aws profile/ using aws_assume_role_arn ) none of them works.

**Comment by phillbaker** [comment]
@nirsv it depends on the domain access policy applied to the cluster, whether it's a VPC only cluster and other options applied to the cluster. If you can use `curl` to access the cluster, use the same credentials in this provider.
