### ISSUE TITLE
Index template is not created correctly

### ISSUE THREAD

**Issue by duyhieuvo** [phillbaker/terraform-provider-elasticsearch#312]
Hello,

we are currently using the provider to manage our AWS OpenSearch version 1.2 resources. We encountered a problem while using the `elasticsearch_index_template` resource:

```
resource "elasticsearch_index_template" "index-template" {
  name     = "test_template"
  body     = <<EOF
  {
    "index_patterns": ["test-index*"],
    "template": {
      "settings": {
        "plugins.index_state_management.rollover_alias": "test-index"
      }
    }
  }
  EOF
}
```
Terraform indicated that resource was created fine. But we cannot retrieve it when calling `GET _index_template/`. It is only possible to see the template when calling `GET _cat/templates`. And the template also doesn't apply to new index created with the matching index pattern. 

We briefly checked in the elastic client used by the provider and looks like it uses the  `_template/` endpoint to create the index template: https://github.com/olivere/elastic/blob/29ee98974cf1984dfecf53ef772d721fb97cb0b9/indices_put_template.go#L166
While the endpoint in OpenSearch document is `_index_template/` (https://opensearch.org/docs/latest/opensearch/index-templates/#create-a-template).

Maybe that's the cause. But maybe I missed something because I'm not really familiar with Go. 

Additionally, it's indicated in the [olivere/elastic](https://github.com/olivere/elastic) repo that it is deprecated and recommended to use official elasticsearch client. Is there any plan to switch to the new client? 

Thank you!

**Comment by phillbaker** [comment]
Related to https://github.com/phillbaker/terraform-provider-elasticsearch/pull/295/. They must have dropped the older endpoint.


> Additionally, it's indicated in the [olivere/elastic](https://github.com/olivere/elastic) repo that it is deprecated and recommended to use official elasticsearch client. Is there any plan to switch to the new client?

olivere/elastic is not supporting v8, the library is not deprecated.

**Comment by duyhieuvo** [comment]
We checked again with the help from AWS support. The `_template/` endpoint is still available on AWS OpenSearch 1.2. The template can also be seen when doing `GET _template/`.

The reason that the setting wasn't applied to newly created index before is because AWS OpenSearch still uses the old setting for rollover_alias. It should be `index.opendistro.index_state_management.rollover_alias` instead of `plugins.index_state_management.rollover_alias` like in the OpenSearch documentation. Could be interesting for someone running into the same problem.

Could be a problem when they actually remove the old `_template/` endpoint.  But I believe the provider still works fine with the current AWS Opensearch version 1.2 we are using.

**Comment by phillbaker** [comment]
Thanks @duyhieuvo, I'm going to close this issue out as resolved. Hopefully this issue will document the discrepancy for other users with this problem.

**Comment by greut** [comment]
Self hosted OpenSearch 1.3 still has the issue, sadly.
