### ISSUE TITLE
Error: elastic: Error 500 (Internal Server Error): lateinit property name has not been initialized [type=uninitialized_property_access_exception]

### ISSUE THREAD

**Issue by umeat** [phillbaker/terraform-provider-elasticsearch#319]
Using phillbaker/elasticsearch provider version 2.0.5 with terraform version 1.2.1 and receive the following error when trying to create a elasticsearch_opensearch_monitor resource.

```
Error: elastic: Error 500 (Internal Server Error): lateinit property name has not been initialized [type=uninitialized_property_access_exception]
```

Cluster version is Elasticsearch 7.10.

Any ideas what might be causing this?

**Comment by phillbaker** [comment]
Hello, can you please include the following:
* opendistro version
* redacted version of the terraform resource configuration
* terraform logs by setting [`TF_LOG=info`](https://www.terraform.io/docs/internals/debugging.html)

**Comment by umeat** [comment]
Apologies, I stopped looking into this and no longer have the Terraform I was testing with. The Opendistro version was 1.13.3, I believe.
