### ISSUE TITLE
[Request] Cut New Release

### ISSUE THREAD

**Issue by Techcadia** [phillbaker/terraform-provider-elasticsearch#32]
Currently it seems that 0.8.1 is not current with Master. We tried to use it and it fails with a http timeout. But Master does not.

Can we get a new release cut off of master?

**Comment by phillbaker** [comment]
Only
https://github.com/phillbaker/terraform-provider-elasticsearch/pull/31 has
been merged since the last release was cut, AWS creds don’t seem related to
timeouts.

Can you clarify which binary/arch you’re using and how you compiled master
(With CGO, what go version)?

**Comment by Techcadia** [comment]
```bash
awesome@MacBook-Pro ~ $ go version
go version go1.12.1 darwin/amd64
awesome@MacBook-Pro ~ $ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/awesome/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/awesome/src/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/Cellar/go/1.12.1/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.12.1/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/cs/h5wdnvqs7z5f527sln6tr23w0000gn/T/go-build786617776=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

Here is my `go version` and `go env`

the file I tried before this was the binary on the release page
https://github.com/phillbaker/terraform-provider-elasticsearch/releases/download/v0.8.1/terraform-provider-elasticsearch_v0.8.1_darwin_amd64

**Comment by phillbaker** [comment]
Hm, I was thinking that you might have had a networking issue related to compiling with CGO enabled vs. disabled (https://github.com/golang/go/issues/12524). However, that build you linked to shouldn't have that issue. Can you post the error (sensitive information reacted) you were seeing?

**Comment by Techcadia** [comment]
```
Error: Head https://${ELASTIC_SEARCH_ENDPOINT}.us-west-2.es.amazonaws.com: context deadline exceeded

  on .terraform/modules/service/elastic_search_provider.tf line 1, in provider "elasticsearch":
   1: provider "elasticsearch" {
```

This error occurs on both the darwin_amd64 Dynamic and Statically linked binaries. Interesting though is that when I compile it using my own I don't run into the same issue. Currently running Terraform 0.12.5. Without any other updates or changes to the repo.

**Comment by phillbaker** [comment]
@Techcadia sorry for the slow reply. I'm not sure why you're seeing a difference, but I did cut https://github.com/phillbaker/terraform-provider-elasticsearch/releases/tag/v0.8.2

**Comment by phillbaker** [comment]
@Techcadia did the latest version fix your timeout?

**Comment by Techcadia** [comment]
This seems to work as expected. Not sure why the old release was having issues.
