### ISSUE TITLE
API endpoints

### ISSUE THREAD

**Issue by leolorenzoluis** [phillbaker/terraform-provider-elasticsearch#328]
Hi,

We've noticed that the url is using "/_opendistro/.." in the provider. However, our initial tests confirm that "/_plugins/..." is way faster. Is this something that needs to be refactored? If so, I can happily submit a pull request.

Also, I feel like we need to implement a retry similar to opendistro users to other opendistro resources as we're getting intermittent 400 bad request.

I can't seem to recreate the issue with simple parallel requests with multiple GET/PUT requests. I'm not sure if another endpoint similar to https://github.com/phillbaker/terraform-provider-elasticsearch/issues/154 has the same behavior with OpenSearch but instead returns 400? However, based off the tests with simple curl doesn't give us 400, so I'm not sure if it's the provider's package for ES client is the issue. Not sure if it's downstream/upstream

https://github.com/phillbaker/terraform-provider-elasticsearch/issues/154

**Comment by phillbaker** [comment]
Hello, please see the discussion in https://github.com/phillbaker/terraform-provider-elasticsearch/issues/298, they should be supported in the official opensearch provider.

I'm going to close this issue for now, please reopen if that issue doesn't answer your questions.
