### ISSUE TITLE
Using elasticsearch_opensearch_destination for sns generate error

### ISSUE THREAD

**Issue by behnm** [phillbaker/terraform-provider-elasticsearch#334]
I want to create a sns notification channel by terraform . My resource is 

```
resource "elasticsearch_opensearch_destination" "alert_sns" {
  body = jsonencode({
    type = "sns"
    name = "alert-sns"
    sns = {
        topic_arn = "my_topic_arn"
        role_arn = "my_role_arn"
    }
  })
}
```

But it gives me the error.
`Error: elastic: Error 405 (Method Not Allowed)`.
My question is, All the paramters that are used are correct or I should use `config_type`, instead of using `type` for sns for instance. 

The version of things that I use:
**Terraform: v1.1.1
opensearch: v2.3
provider elasticsearch: V2.0.4**

**Comment by MindAwakeBodyAsleep** [comment]
Not only for SNS. I have that kind of error for type: slack also

**Comment by JPLachance** [comment]
👋🏼 

OpenSearch made breaking changes. This provider does not support OpenSearch 2.0

See https://github.com/phillbaker/terraform-provider-elasticsearch/issues/298#issuecomment-1327909365.

**Comment by phillbaker** [comment]
Please see above, as this sounds like a version compatibility issue.
