### ISSUE TITLE
HEAD healthcheck failed!

### ISSUE THREAD

**Issue by LixvYang** [phillbaker/terraform-provider-elasticsearch#338]
Sorry for asking this question, when I want to check the index in my cluster, he bursts out such an error, it seems that I have not configured it well, but I configured it like this
```go
cfg := elasticsearch.Config{
		APIKey:   os.Getenv("ELASTICSEARCH_API_KEY"),
		CloudID:  os.Getenv("ELASTICSEARCH_CloudID"),
		Username: os.Getenv("ELASTICSEARCH_USERNAME"),
		Password: os.Getenv("ELASTICSEARCH_PASSWORD"),
	}
	es, err := elasticsearch.NewClient(cfg)
	if err != nil {
		return nil, err
	}
```
In this case the error is like this:
```
[ error ] 1 error occurred:
        * HEAD healthcheck failed: This is usually due to network or permission issues. The underlying error isn't accessible, please debug by disabling healthchecks.

```
When I debugged, I found that the error is actually caused by this interface
```
/pkg/tfshim/shim.go

type Provider interface {
	Refresh(t string, s InstanceState) (InstanceState, error)
}
```

I don't know the function of this interface, how should I do it? About this interface. Or is there something wrong with my configuration? How do I need to configure resources?

**Comment by phillbaker** [comment]
Hello - the code snippet you shared is not part of this terraform provider, `elasticsearch.NewClient` is not an interface this client exposes. If you have a question regarding usage of the upstream elasticsearch go client, please open an issue on the relevant repository.

**Comment by phillbaker** [comment]
Going to close this issue, please reopen if this is relevant to the provider.
