### ISSUE TITLE
Cannot create references for Opensearch dashboard or visualization kibana objects

### ISSUE THREAD

**Issue by olbees** [phillbaker/terraform-provider-elasticsearch#348]
I am unable to create references for visualizations or dashboards in Opensearch 1.1 using elasticsearch_kibana_object. The objects are created successfully but there are no references present when I check the saved object. This results in an error when opening the dashboard. The error goes away if I add the references manually.

e.g:
```
resource "elasticsearch_kibana_object" "awswaf_dashboard" {
  body = <<EOF
[
  {
    "_id": "dashboard:awswaf-dashboard",
    "_type": "doc",
    "references": [
        {
            "id": "allowed-blocked",
            "name": "panel_0",
            "type": "visualization"
        }
    ],
    "_source": {
      "type": "dashboard",
      "dashboard": {
        "description": "",
        "hits": 0,
        "kibanaSavedObjectMeta": {
            "searchSourceJSON": "{\"query\":{\"query\":\"\",\"language\":\"kuery\"},\"filter\":[]}"
        },
        "optionsJSON": "{\"useMargins\":true,\"hidePanelTitles\":false}",
        "panelsJSON": "[{\"version\":\"1.1.0\",\"gridData\":{\"x\":0,\"y\":0,\"w\":24,\"h\":15,\"i\":\"a8ba3895-8eb8-464f-b5c1-424dc27f0a0c\"},\"panelIndex\":\"a8ba3895-8eb8-464f-b5c1-424dc27f0a0c\",\"embeddableConfig\":{\"vis\":{\"colors\":{\"ALLOW\":\"#629E51\"}}},\"panelRefName\":\"panel_0\"}]",
        "timeRestore": false,
        "title": "awswaf-dash",
        "version": 1
      }
    }
  }
]
EOF
}
```

**Comment by phillbaker** [comment]
Hi @olbees since the kibana object resource is a straight pass through to store json in the relevant index, it sounds like you need to update the json you're storing in the dashboard object. This provider is just determining where to store the data, not what data to store. You can try exporting widgets to raw json from kibana to get an idea of what the correct json to store is.

**Comment by phillbaker** [comment]
Closing this, please reopen if there's additional information to share.
