### ISSUE TITLE
Error: Head "https://xxx.es.eastus2.azure.elastic-cloud.com:9200": context deadline exceeded

### ISSUE THREAD

**Issue by demoran23** [phillbaker/terraform-provider-elasticsearch#352]
I'm getting the following error when trying to apply my changes:

> Error: Head "https://xxx.es.eastus2.azure.elastic-cloud.com:9200": context deadline exceeded

```
provider "elasticsearch" {
  url   = "${var.elasticsearch_endpoint}:9200"
  token = var.elasticsearch_api_key
}
```

I've gotten the same result using username/password authentication, and insecure mode.

Does this provider support Azure?  I know there's some AWS specific settings provided.

**Comment by phillbaker** [comment]
Hello - this provider supports access to elasticsearch clusters, regardless of where they are hosted, provided that the authentication works. Specifically for elastic-cloud, username/password authentication should be all that is required. Related to https://github.com/phillbaker/terraform-provider-elasticsearch/issues/176.

Usually this error indicates that network access (as opposed to an authentication issue) is at fault.

Please include the following information:
* from where are you running the provider?
* where is the elasticsearch cluster located?
* what is the networking configuration for where the elasticsearch cluster runs and all the networks connecting the location where the provider is running to the cluster?

What steps have you taken so far to debug the issue?

**Comment by phillbaker** [comment]
Closing this, please re-open if you have further details.
