### ISSUE TITLE
[Feature request] - Add Support for snapshot_management 

### ISSUE THREAD

**Issue by egarbi** [phillbaker/terraform-provider-elasticsearch#354]
# Description
[OpenSearch 2.1](https://opensearch.org/blog/releases/2022/07/opensearch-2-1-is-available-now/) added a new feature "Snapshot Management" to create a policy for automating the snapshot process.

At the moment there isn't a resource within the terraform provider to support adding this kind of policies or anything related to SM.

You can see the full API docs [here](https://opensearch.org/docs/latest/tuning-your-cluster/availability-and-recovery/snapshots/sm-api/)

**Comment by phillbaker** [comment]
Hi, yes, please open an issue on https://github.com/opensearch-project/terraform-provider-opensearch
