### ISSUE TITLE
[feat] support user API

### ISSUE THREAD

**Issue by Wing924** [phillbaker/terraform-provider-elasticsearch#36]
This provider is very nice!
It would be nice if we can manage users via this provider.
https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-put-user.html

**Comment by phillbaker** [comment]
Hi @Wing924, thanks for opening an issue. Of the Xpack security objects, it looks like we configure roles and role mappings, but not users (https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api.html#security-user-apis).

If you'd like to submit a PR, that be much appreciated!

**Comment by phillbaker** [comment]
Done in https://github.com/phillbaker/terraform-provider-elasticsearch/pull/37
