### ISSUE TITLE
can't build 

### ISSUE THREAD

**Issue by chicagobuss** [phillbaker/terraform-provider-elasticsearch#4]
Hello, trying to build this for linux and it's pretty hard since go is on 1.9 now and dep is the standard for dependency management...

so, I made a docker container, installed go 1.7, tried to use glide install to get dependencies, and a bunch failed on github auth (even though my github ssh key was in my agent and working)

So I tried dep next and actually got further, but then go build fails with:
```
root@69f858b7e81b:~/go/src/phillbaker/terraform-provider-elasticsearch# go build
# phillbaker/terraform-provider-elasticsearch/vendor/google.golang.org/grpc/transport
vendor/google.golang.org/grpc/transport/http_util.go:485: f.fr.SetReuseFrames undefined (type *http2.Framer has no field or method SetReuseFrames)
# phillbaker/terraform-provider-elasticsearch/vendor/github.com/hashicorp/terraform/terraform
vendor/github.com/hashicorp/terraform/terraform/context.go:691: undefined: sort.Slice```

Please let me know how we can help - we'd really like to use this but we need it built for linux :)

**Comment by phillbaker** [comment]
Hey @chicagobuss took me a second, but I think you found a bug in the README 😀, instead of being Golang 1.7 it should be `>= 1.7`.  Locally I'm on go 1.9 (although, yes a mac).

If you trying building in a container with 1.9 and glide does that work for you?

I'd definitely be open to migrating this package to go dep as well (and adding some CI) - this was thrown together in a bit of a rush, so totally can use some love!

**Comment by chicagobuss** [comment]
Ha, I went through a lot of effort just to get on 1.7 because I assumed it was required.  Will try again soon, thanks.

**Comment by phillbaker** [comment]
So in a bit of irony, I did try to convert to `dep` (https://github.com/phillbaker/terraform-provider-elasticsearch/tree/dep-not-glide), but I am seeing the same error you posted above when using dep. On https://travis-ci.org/phillbaker/terraform-provider-elasticsearch/jobs/314409199.

Using glide on travis on master seems to build fine 😕 . Other posts about this seem to indicate that it's a a dependency issue.

**Comment by phillbaker** [comment]
Ah, so it looks like dep strips the `vendor` directories of dependencies which is an issue for at least terraform, aws-sdk-go, see https://github.com/golang/dep/issues/1075#issuecomment-325492178.

However, dep did merge support for govendor (which terraform uses) a couple of weeks ago, although it hasn't been included in a release yet, which I _think_ solve the issue of recursive dependencies?

Until it's clear how `dep` support dependencies like terraform, seems better to stick with `glide`.

**Comment by IslamAzab** [comment]
I am trying to `build` on mac but I am getting the following:

```console
unexpected directory layout:
    import path: github.com/hashicorp/terraform/plugin
    root: /Users/username/.gvm/pkgsets/go1.10.1/global/src
    dir: /Users/username/.gvm/pkgsets/go1.10.1/global/src/github.com/phillbaker/terraform-provider-elasticsearch/vendor/github.com/hashicorp/terraform/plugin
    expand root: /Users/username/.gvm/pkgsets/go1.10.1/global/src
    expand dir: /Users/username/.gvm/pkgsets/go1.10.1/global/src/github.com/phillbaker/terraform-provider-elasticsearch/vendor/github.com/hashicorp/terraform/plugin
    separator: /
```

**Comment by phillbaker** [comment]
Hello, I'll need a bit more context to help debug. 

The steps to build this project are documented [in the readme](https://github.com/phillbaker/terraform-provider-elasticsearch#requirements). (The [travis build script](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/0caad9d0fb429fb36515d231aa0145d7571568a2/.travis.yml#L6-L12) is also a good resource.)

Can you list all the commands you used to generate that error?

**Comment by IslamAzab** [comment]
@phillbaker Thanks for your reply, sorry for the late reply.

I tried with the master updates and it worked, I can not reproduce the issue.
