### ISSUE TITLE
Support for Elastic Cloud

### ISSUE THREAD

**Issue by earlpotter0** [phillbaker/terraform-provider-elasticsearch#40]
Trying this out against an Elastic Cloud deployment (Similar to ECE).  Just trying to create an index template.  When I do an apply, I get the following:

`Error: no active connection found: no Elasticsearch node available`

The Elastic cloud deployment uses port 9243.   I can curl to the ECS endpoint and get an appropriate response.

When I try the Terraform to a locally installed ES instance, it works w/o issue.  Port 9200 and 9243.  
```
provider "elasticsearch" {
  url = "https://XXXXXXXXX.us-west-2.aws.found.io:9243"
  username = "XXXXXXXXXX"
  password = "XXXXXXXXXX"
}

resource "elasticsearch_index_template" "test" {
  name = "terraform-test"
  body = <<EOF
{
  "template" : "test-*",
  "settings" : {
    "index" : {
      "refresh_interval" : "30s"
    }
  }
}
EOF
}
```

**Comment by phillbaker** [comment]
Hi @earlpotter0, sorry to hear you're having issues. I do believe that this provider works to connect to elasticsearch host hosted on Elastic Cloud - there was a previous issue opened that indicated it worked: https://github.com/phillbaker/terraform-provider-elasticsearch/issues/30.

One thing I have noticed is that the way terraform is compiled it can be hampered by issues in Go's DNS resolution on Mac OS (see https://github.com/golang/go/issues/12524) - are you by chance running this from a Mac? 

If not, can you provide your OS and the version information of the provider?

**Comment by earlpotter0** [comment]
I am using this from a Mac, but I tried from an Ubuntu EC2 instance, also.
OSX: 10.14.6.
Ubuntu: 18.04.1

If I'm not mistaken, ECE is effectively self hosted Elastic Cloud.  In my case, I'm using Elastic hosted Elastic Cloud.  I even tried signing up for a 14 day trial w/my personal email and I got the same issue.

**Comment by robbruce** [comment]
Same issue for me, also running on a Mac, and had the same when running inside a docker container with alpine (binary build inside golang:1.13-alpine).

I created a small app against https://github.com/olivere/elastic and had the same issue, until I added `elastic.SetSniff(false)` then that connected successfully.

Adding `sniff = false` to the provider declaration made this issue go away

**Comment by earlpotter0** [comment]
sniff = false did indeed fix the issue!  Thank you!!
