### ISSUE TITLE
Index Template creation uses create: True

### ISSUE THREAD

**Issue by xiu** [phillbaker/terraform-provider-elasticsearch#52]
We use `create` = `true` in https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/resource_elasticsearch_index_template.go#L116. This behavior prevents an user from transitioning to Terraform on an existing cluster as resources might already exist:
```
Error: elastic: Error 400 (Bad Request): index_template [index1] already exists [type=illegal_argument_exception]

  on elasticsearch/index/index1.tf line 35, in resource "elasticsearch_index_template" "index1":
  35: resource "elasticsearch_index_template" "index1" {



Error: elastic: Error 400 (Bad Request): index_template [index2] already exists [type=illegal_argument_exception]

  on elasticsearch/index/index2.tf line 35, in resource "elasticsearch_index_template" "index2":
  35: resource "elasticsearch_index_template" "index2" {



Error: elastic: Error 400 (Bad Request): index_template [index3] already exists [type=illegal_argument_exception]

  on elasticsearch/index/index3.tf line 35, in resource "elasticsearch_index_template" "index3":
  35: resource "elasticsearch_index_template" "index3" {
```

```
resource "elasticsearch_index_template" "index1" {
  name = "index1"
  body = <<EOF
{
    "aliases": {
        "index1": {}
    },
    "index_patterns": [
        "index1-*"
    ],
    "settings": {
        "index": {
            "lifecycle": {
                "name": "index1",
                "rollover_alias": "index1"
            },
            "number_of_shards": "2",
            "number_of_replicas": "1",
            "routing": {
                "allocation": {
                    "require": {
                        "box_type": "hot"
                    }
                }
            }
        }
    }
}
EOF
}
```

I'm happy to create a PR to always set `create` to `false` but I might be using the provider the wrong way, am I?

References:
- https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html#put-index-template-api-query-params
- https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/resource_elasticsearch_index_template.go#L174

**Comment by phillbaker** [comment]
Hi @xiu, thanks for opening an issue. I'm not sure I understand the issue you're describing. 

It seems like you've hardcoded the line below to avoid triggering errors from the ES api:

https://github.com/phillbaker/terraform-provider-elasticsearch/blob/974ae3aee69034986b1d12ffc7526cae2dc061cd/resource_elasticsearch_index_template.go#L174


It's not clear from your comment (you mention hardcoding both true and false) - are you using `Create(false)` or `Create(true)`?
  * The docs describe this attribute as `If true, this request cannot replace or update existing index templates. Defaults to false.`
  * The code as written uses `Create(true)` when creating the index and `Create(false)` when updating the index.

> This behavior prevents an user from transitioning to Terraform on an existing cluster as resources might already exist

I didn't understand this - do you have shared terraform state between users? If so, the shared terraform state should serve that purpose?

**Comment by xiu** [comment]
Thanks for you answer. Indeed it wasn't clear: I haven't touched the code, I'm just using the provider to provision index templates. My issue is that index templates with these names already exist on my target clusters and they haven't been provisioned using Terraform.  On my first run, while I don't have a state yet, Terraform will fail applying its plan as the templates already exist.

What I was proposing is that the provider could use `Create(false)` in all cases to be able to overwrite an existing template if need be.

Does it make sense?

**Comment by xiu** [comment]
I was actually able to import my resources using `terraform import`, I'm fine closing this issue, thanks!

**Comment by phillbaker** [comment]
Ah, yes. `terraform import` is the recommended approach!
