### ISSUE TITLE
New release with Elasticsearch 7 features

### ISSUE THREAD

**Issue by williamsbdev** [phillbaker/terraform-provider-elasticsearch#53]
First off, thanks for this provider!

I noticed that the [v0.11.0 release](https://github.com/phillbaker/terraform-provider-elasticsearch/releases/tag/v0.11.0) was done 9 days ago and then within a couple of days, Elasticsearch 7 features were released. Do you have time to cut a new release?

Thanks again for curating this provider and helping the community!

**Comment by phillbaker** [comment]
No problem - just to clarify though, ES7 has been supported since June '19, it looks like the additional commits are some bugfixes.

**Comment by williamsbdev** [comment]
@phillbaker - My apologies. You're right. I recently upgraded to ES 7 and then noticed that some of the features I wanted were just recently implemented to support ES 7.

**Comment by phillbaker** [comment]
https://github.com/phillbaker/terraform-provider-elasticsearch/releases/tag/v0.11.1 has also been released.

**Comment by williamsbdev** [comment]
@phillbaker - Thank you!
