### ISSUE TITLE
Make roles, users, and role-mappings importable?

### ISSUE THREAD

**Issue by mindbat** [phillbaker/terraform-provider-elasticsearch#57]
Hey, @phillbaker! Bless you for writing this provider; excited to start using it for the ES clusters on my team :)

I've run into one blocker, though. All of the ES clusters I'd like to put under tf management (with this provider) have existing users, roles, etc. These aren't currently importable, so my tf plans think they need to create new copies of all of these.

I see other resources like [indices](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/resource_elasticsearch_index.go#L116) and [index templates](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/resource_elasticsearch_index_template.go#L33) are importable. Could we get roles/users/role-mappings to also be importable?

**Comment by phillbaker** [comment]
Hey @mindbat glad you found it useful - I assume you're referring to the xpack user/role/role mappings? Happy to accept PR for these - however, I have seen that there may be some bugs in how the provider stores these objects in terraform currently (e.g. https://github.com/phillbaker/terraform-provider-elasticsearch/issues/49), so imports might be a bit finicky.

If you're interested in trying to add these importers yourself, here are a couple of examples:
* https://github.com/phillbaker/terraform-provider-elasticsearch/pull/47
* https://github.com/phillbaker/terraform-provider-elasticsearch/commit/92b143a44f766f2852f869df2d15181550d7e2b1

**Comment by mindbat** [comment]
> I assume you're referring to the xpack user/role/role mappings?

Yep! 

Thankfully, the  default `field_security` setting is fine for what I need, so the issues with that field shouldn't affect me 🤞 

> If you're interested in trying to add these importers yourself

Thanks for the examples! I'm working on a PR, in fact, but I'm having issues getting the tests to run. Even if I use the [`docker-compose`](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/docker-compose.yml) file in the repo, and run them using the command from [`travis.yml`](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/master/.travis.yml#L45), I get a whole lot of skipped tests:

```
~/Code/terraform-provider-elasticsearch % TF_ACC=1 go test -v
=== RUN   TestAccElasticsearchDataSourceDestination_basic
--- SKIP: TestAccElasticsearchDataSourceDestination_basic (5.02s)
    data_source_elasticsearch_destination_test.go:18: err: health check timeout: no Elasticsearch node available
=== RUN   TestAccElasticsearchDataSourceHost_basic
--- FAIL: TestAccElasticsearchDataSourceHost_basic (0.00s)
    provider_test.go:67: ELASTICSEARCH_URL must be set for acceptance tests
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccElasticsearchDestination
--- SKIP: TestAccElasticsearchDestination (5.01s)
    resource_elasticsearch_destination_test.go:20: err: health check timeout: no Elasticsearch node available
=== RUN   TestAccElasticsearchDestination_importBasic
--- SKIP: TestAccElasticsearchDestination_importBasic (5.01s)
    resource_elasticsearch_destination_test.go:57: err: health check timeout: no Elasticsearch node available
=== RUN   TestAccElasticsearchIndexLifecyclePolicy
```

Though even the docker-compose usage has errors. Only one of the containers comes up properly:

```
~/Code/terraform-provider-elasticsearch % ES_VERSION=7.5.0 ES_OSS_IMAGE=docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION} ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION} docker-compose up
WARNING: The ES_COMMAND variable is not set. Defaulting to a blank string.
Starting terraform-provider-elasticsearch_opendistro_1    ... done
Starting terraform-provider-elasticsearch_xpack_1         ... done
Starting terraform-provider-elasticsearch_elasticsearch_1 ... done
Attaching to terraform-provider-elasticsearch_xpack_1, terraform-provider-elasticsearch_elasticsearch_1, terraform-provider-elasticsearch_opendistro_1
terraform-provider-elasticsearch_opendistro_1 exited with code 0
elasticsearch_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
xpack_1          | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
terraform-provider-elasticsearch_elasticsearch_1 exited with code 137
```

Any guidance on what I might be doing wrong?

**Comment by mindbat** [comment]
Ah, I think I figured it out.

I'm running on a Mac, so I needed to boost the resources used by Docker Desktop to 4GB of RAM. 

I also needed to set the [`vm.max_map_count`](https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#_set_vm_max_map_count_to_at_least_262144).

Once that was done, I was able to run the tests with:

```
~/Code/terraform-provider-elasticsearch % ES_VERSION=7.5.0 ES_OSS_IMAGE=docker.elastic.co/elasticsearch/elasticsearch-oss:${ES_VERSION} ES_IMAGE=docker.elastic.co/elasticsearch/elasticsearch:${ES_VERSION} docker-compose up -d
WARNING: The ES_COMMAND variable is not set. Defaulting to a blank string.
Starting terraform-provider-elasticsearch_elasticsearch_1 ... done
Starting terraform-provider-elasticsearch_opendistro_1    ... done
Starting terraform-provider-elasticsearch_xpack_1         ... done

~/Code/terraform-provider-elasticsearch % ELASTICSEARCH_URL=http://127.0.0.1:9200 TF_ACC=1 go test -v
=== RUN   TestAccElasticsearchDataSourceDestination_basic
--- SKIP: TestAccElasticsearchDataSourceDestination_basic (0.19s)
    data_source_elasticsearch_destination_test.go:35: Destinations only supported on ES 6, https://github.com/opendistro-for-elasticsearch/alerting/issues/66
=== RUN   TestAccElasticsearchDataSourceHost_basic
--- PASS: TestAccElasticsearchDataSourceHost_basic (0.11s)
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccElasticsearchDestination
--- SKIP: TestAccElasticsearchDestination (0.01s)
    resource_elasticsearch_destination_test.go:37: Destinations only supported on ES 6, https://github.com/opendistro-for-elasticsearch/alerting/issues/66
=== RUN   TestAccElasticsearchDestination_importBasic
--- SKIP: TestAccElasticsearchDestination_importBasic (0.01s)
    resource_elasticsearch_destination_test.go:74: Destinations only supported on ES 6, https://github.com/opendistro-for-elasticsearch/alerting/issues/66
...etc
```

**Comment by mindbat** [comment]
Posted a PR: https://github.com/phillbaker/terraform-provider-elasticsearch/pull/58

With my limited knowledge of golang, I think I've taken it about as far as I can :/ 

@phillbaker can you take a look, and maybe you'll see the pieces I'm missing?
