### ISSUE TITLE
Error refreshing State on v1.0.0

### ISSUE THREAD

**Issue by andrescolodrero** [phillbaker/terraform-provider-elasticsearch#62]
Hi,
Im testing the latest version, and i get this issue:
elasticsearch_ingest_pipeline.logging-kibana-reader: Refreshing state... [id=logging-pipeline]
2020/03/31 20:24:48 [ERROR] <root>: eval: *terraform.EvalReadState, err: missing expected [
2020/03/31 20:24:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: missing expected [
2020/03/31 20:24:48 [ERROR] <root>: eval: *terraform.EvalReadState, err: missing expected [
2020/03/31 20:24:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: missing expected [
2020/03/31 20:24:48 [ERROR] <root>: eval: *terraform.EvalReadState, err: missing expected [
2020/03/31 20:24:48 [ERROR] <root>: eval: *terraform.EvalSequence, err: missing expected [

Im using exactly same code that with latest version

**Comment by phillbaker** [comment]
Sorry to hear that - can you share the terraform config that's having an issue?

**Comment by phillbaker** [comment]
Hi @andrescolodrero, I'll close this issue in a bit unless more information can be provided. 

Unfortunately with the major version bump, some resources might need to be deleted from state and re-imported. Please add any details/reproduction steps if this is still an issue.

**Comment by nelg** [comment]
Do you know which resources this is impacting?  I have to assume it's a change of format in the state file.  Just would be nice to figure out as have 85 resources defined, and don't want to drop all of them from the state file.

I get this error:
Error: missing expected [

around 18 times, but no clues as to which resources.

Can we improve the error message? IE, to say which resource it's got a problem with?

**Comment by nelg** [comment]
Please add the following to the documentation:

Run the following commands prior to upgrading to version 1.0.0t:
`
terraform state list | grep role\\.  > roles.txt

for i in $(cat roles.txt); do id=$(terraform state show $i | egrep "id"|tr -d '"'| cut -d'=' -f 2); echo terraform state rm $i; echo terraform import $i $id; done

`
then: 

Upgrade to the new provider.
Copy and paste the state commands that were printed above.

**Comment by phillbaker** [comment]
see 777021a
