### ISSUE TITLE
Feature request: create the cluster AND the index in the same run

### ISSUE THREAD

**Issue by sorin-costea** [phillbaker/terraform-provider-elasticsearch#63]
As far as I understand, I can use this provider only if I already have the ES cluster - because I need to have its URL. But to have it all in one run, I'd need to write something like the below. There is an old closed issue #11 which suggest it was working, once... (with a hand wired https prefix) but if I try it now, _terraform plan_ complains "health check timeout: no Elasticsearch node available" (kinda true)
```
provider "elasticsearch" {
  url = aws_elasticsearch_domain.my-freshly-created-domain.endpoint
}
```

**Comment by phillbaker** [comment]
Being about to create these at the same time would be great - as I remember, there were upstream terraform issues: terraform 0.11 specifically documented that providers could not depend on resources: https://www.terraform.io/docs/configuration-0-11/providers.html#interpolation.

It looks like 0.12 has similar language: https://www.terraform.io/docs/configuration/providers.html#provider-configuration:
> The configuration arguments defined by the provider may be assigned using expressions, which can for example allow them to be parameterized by input variables. However, since provider configurations must be evaluated in order to perform any resource type action, provider configurations may refer only to values that are known before the configuration is applied. In particular, avoid referring to attributes exported by other resources unless their values are specified directly in the configuration.

Unfortunately this is a feature request for terraform itself, not this provider.

**Comment by sorin-costea** [comment]
:( thank you... it doesn't look like something trivial on their side either.

**Comment by john-delivuk-rl** [comment]
Created #119 to address
