### ISSUE TITLE
context deadline exceeded at terraform plan

### ISSUE THREAD

**Issue by yteraoka** [phillbaker/terraform-provider-elasticsearch#64]
I got following error at execute `terraform plan` when I use terraform-provider-elasticsearch binary downloaded from release page (both static and non-static binary) on my mac book.

```
Error: Head https://*****.ap-northeast-1.es.amazonaws.com: context deadline exceeded
```

When I use self build (git clone & go build) binary works fine. Other mac users are OK ?

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.4
BuildVersion:	19E287

Terraform v0.12.23

terraform-provider-elasticsearch version: 1.0.0
```

**Comment by phillbaker** [comment]
This seems similar to the discussion in
https://github.com/phillbaker/terraform-provider-elasticsearch/issues/32#issuecomment-518223711
.

How are you compiling the binary?

**Comment by yteraoka** [comment]
I just typed `go build` on my macbook pro.

**Comment by CmdrChaos** [comment]
I am experiencing the same issue.  Just installed v1.2.0 and getting the same error.
Error: Head "https://******************.us-west-2.es.amazonaws.com": context deadline exceeded

  on root.tf.json line 59, in provider[7].elasticsearch:
  59:       }

lines from root.tj.json
    {
      "elasticsearch": {
        "alias": "portal",
        "url": "https://****************************.us-west-2.es.amazonaws.com",
        "insecure": true,
        "version": "~> 1.2.0"
      }
    },

**Comment by CmdrChaos** [comment]
Quick update.... Issue resolved for me.
Issue was resolved by adding:
"healthcheck": false
to the Elasticsearch provider definition. So it now looks like:
{
"elasticsearch": {
"alias": "portal",
"url": "https://****************************.us-west-2.es.amazonaws.com",
"insecure": true,
"healthcheck": false,
"version": "~> 1.2.0"
}


},

**Comment by phillbaker** [comment]
Great - if there are other details, please provide them. Going to mark this as closed for now.
