### ISSUE TITLE
OpenDistro Role example

### ISSUE THREAD

**Issue by stempher** [phillbaker/terraform-provider-elasticsearch#68]
There is an OpenDistro Role example:

```
resource "elasticsearch_opendistro_role" "test" {
  role_name = "test"
  index_permissions {
    index_patterns = [
      "test*"
    ]
    allowed_actions = [
      "read"
    ]
  }

  tenant_permissions {
    tenant_patterns = [
      "global_tenant"
    ]
    allowed_actions = [
      "kibana_all_write"
    ]
  }
}
```
How can I specify a few index permissions?

**Comment by phillbaker** [comment]
I'm not sure I understand the question - in the example above, the read permission is granted on the test* indices. Are you asking how to specify multiple permissions?

The security plugin also provides the opendistro_role_mapping resource, please see the underlying docs at:
* https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/users-roles/

The full list of available permissions and actions are in the underlying docs:
* https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/permissions/
* https://opendistro.github.io/for-elasticsearch-docs/docs/security-access-control/default-action-groups/

**Comment by stempher** [comment]
I want the role to have different permissions on the two indexes:
- pattern test* with action read
- pattern ?kibana with action indices_all
But I don’t understand how to do it syntactically in one resource

**Comment by phillbaker** [comment]
@stempher please try something like the following:
```
resource "elasticsearch_opendistro_role" "test" {
	role_name = "%s"
	description = "test"
	index_permissions {
		index_patterns = [
			"test*",
		]

		allowed_actions = [
			"read",
		]
	}

	index_permissions {
		index_patterns = [
			"?kibana",
		]

		allowed_actions = [
			"indices_all",
		]
	}

	tenant_permissions {
		tenant_patterns = [
			"*",
		]

		allowed_actions = [
			"kibana_all_write",
		]
	}

	tenant_permissions {
		tenant_patterns = [
			"test*",
		]

		allowed_actions = [
			"kibana_all_write",
		]
	}

	cluster_permissions = ["*"]
}
```

**Comment by stempher** [comment]
thanks - it works
