### ISSUE TITLE
'Cannot unmarshal object' when creating a new elasticsearch_kibana_object

### ISSUE THREAD

**Issue by tdmalone** [phillbaker/terraform-provider-elasticsearch#70]
I'm unable to create a new `elasticsearch_kibana_object` that looks like this:

```hcl
resource "elasticsearch_kibana_object" "test" {
  body = <<EOF
{
  "test": "yes"
}
  EOF
}
```

```bash
elasticsearch_kibana_object.default_space_advanced_settings: Creating...
  body:  "" => "{\n  \"test\": \"yes\"\n}\n  "
  index: "" => ".kibana"

Error: Error applying plan:

1 error occurred:
        * elasticsearch_kibana_object.default_space_advanced_settings: 1 error occurred:
        * elasticsearch_kibana_object.default_space_advanced_settings: json: cannot unmarshal object into Go value of type []map[string]interface {}
```

It sounds like a provider problem, but just in case it was a problem with the schema of the object I also tried a fully correct object (a space, with top-level `space` and `type` keys), and got the same error.

(Also tried without the heredocs, to avoid the extra whitespace around the JSON string, and got the same result).

Maybe related: #22 & #69

**Comment by phillbaker** [comment]
@tdmalone what version of elasticsearch was this against?

**Comment by tdmalone** [comment]
@phillbaker This was on 7.6.2. I can try to replicate again now with 7.8.0 or 7.8.1 if that would be useful?

**Comment by phillbaker** [comment]
If I had to guess, I'm not sure that `{"test": "yes"}` is a valid kibana object. Can you try the example in the tests? https://github.com/phillbaker/terraform-provider-elasticsearch/blob/15a448c3aafa25ce3b7ac89f41f08e1cad154e46/es/resource_elasticsearch_kibana_object_test.go#L139-L154

**Comment by phillbaker** [comment]
Added an additional validation and documentation around the format of these objects 95d9b71d9778c885433b3ceef7bfb5f394a21bec, this shouldn't crash any more.
