### ISSUE TITLE
Publication of this provider to https://registry.terraform.io/

### ISSUE THREAD

**Issue by ntdt** [phillbaker/terraform-provider-elasticsearch#74]
In order to simplify the use of this provider with terraform init, could you please follow this guide
https://www.terraform.io/docs/registry/providers/publishing.html#publishing-to-the-registry to publish to the community providers on Terraform registry?

**Comment by phillbaker** [comment]
Interesting, I hadn’t seen this before, I’ll take a look at getting this
set up.

**Comment by phillbaker** [comment]
Looks like feature is still in private beta, if you can get me an invite, I'll publish the provider 😀

**Comment by ntdt** [comment]
We have to wait then :)

**Comment by phillbaker** [comment]
This was published and the readme updated, please see https://registry.terraform.io/providers/phillbaker/elasticsearch/latest
