### ISSUE TITLE
Use SharedCredentialsProvider in the AWS SDK when the AWS client is set up in the provider

### ISSUE THREAD

**Issue by jmisharp** [phillbaker/terraform-provider-elasticsearch#8]
It would be awesome to be able to use shared AWS credentials, when setting up the provider. This can be done by using the  [SharedCredentialsProvider](https://github.com/aws/aws-sdk-go/blob/master/aws/credentials/shared_credentials_provider.go#L25-L41) in the AWS SDK.

Should be implemented here:
https://github.com/phillbaker/terraform-provider-elasticsearch/blob/2c758c1e70117c85d9f49c6751bc1e38f7daf706/provider.go#L101

**Comment by phillbaker** [comment]
Thanks for the idea @jmisharp, one way to approach this without repeating credentials is something like:

```
resource "aws_iam_user" "user" {
  name = "${var.name}-logging"
}

resource "aws_iam_access_key" "user" {
  user = "${aws_iam_user.user.name}"
}

provider "elasticsearch" {
  url            = "https://${var.elasticsearch_endpoint}"
  aws_access_key = "${aws_iam_access_key.user.id}"
  aws_secret_key = "${aws_iam_access_key.user.secret}"
}
```

If you're interested in contributing a PR for this functionality, would be happy to discuss the approach and help review!

**Comment by jmisharp** [comment]
We figured out how to do this without shared credentials by assuming a role and getting temporary credentials, so there's a workaround. But I would like to contribute with a PR though. It's not a big change in the code, so it should be an easy implementation. Do you add me as contributor or can you open up for PRs?

**Comment by phillbaker** [comment]
Great! This repo is already open for PRs ([a few have been submitted](https://github.com/phillbaker/terraform-provider-elasticsearch/pulls?q=is%3Apr+is%3Aclosed)). You can [fork and submit a PR](https://github.com/phillbaker/terraform-provider-elasticsearch#contributing). Looking forward to reviewing the PR.

**Comment by Lngramos** [comment]
Hi, I've run into the same problem.

I've raised the following PR that adds the wanted functionality: https://github.com/phillbaker/terraform-provider-elasticsearch/pull/9

**Comment by jmisharp** [comment]
Great work @Lngramos. You were faster than me :-) Thanks.
