### ISSUE TITLE
how can we use this for terraform 0.12?

### ISSUE THREAD

**Issue by benyitzhaki** [phillbaker/terraform-provider-elasticsearch#82]
As this syntax
`terraform {
  required_providers {
    elasticsearch = {
      source = "phillbaker/elasticsearch"
      version = "1.4.1"
    }
  }
}`
is not available in terraform 0.12, is there a workaround on using the provider?

thanks!

**Comment by mrudrara** [comment]
@benyitzhaki did you resolve the issue. i am in same boat wondering if you can share

**Comment by phillbaker** [comment]
@mrudrara please see the manual installation instructions in the README: https://github.com/phillbaker/terraform-provider-elasticsearch#installation
