### ISSUE TITLE
How to create Opendistro users - internalusers 

### ISSUE THREAD

**Issue by sahilpugalia** [phillbaker/terraform-provider-elasticsearch#83]
As mentioned users/roles/rolemapping with opendistro is supported , although i dont see a way to create users in it.

**Comment by phillbaker** [comment]
Whoops, it does look like users was an oversight, got confused with xpack.

To be clear though, internalusers cannot be created via the API, [see the docs](https://opendistro.github.io/for-elasticsearch-docs/docs/security/configuration/yaml/#internal_usersyml).

**Comment by sahilpugalia** [comment]
I guess they can be created:

https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#create-user

**Comment by JPLachance** [comment]
Hello!

The support for ODFE internal users was added in Coveo's fork a few month ago by one of my colleagues: https://github.com/coveooss/terraform-provider-elasticsearch/blob/master/resource_elasticsearch_odfe_user.go

I think he forgot to open a PR to this repo for his contribution :)

**Comment by phillbaker** [comment]
In looking at the [docs](https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/api/#create-user) I don't see a `description` field, looks like [it is in the source though](https://github.com/opendistro-for-elasticsearch/security/blob/630d5824d2fb4f42a8cd6821b36674d23bcee113/src/main/java/com/amazon/opendistroforelasticsearch/security/securityconf/impl/v7/InternalUserV7.java#L54).

**Comment by phillbaker** [comment]
I've pulled this commit it, it will be released in v1.4.4, https://github.com/phillbaker/terraform-provider-elasticsearch/releases/tag/v1.4.4

**Comment by CumpsD** [comment]
Is it possible for an example on the syntax? Since it is not in the docs, trying to figure it out from the code, but it would be nice to be sure

**Comment by CumpsD** [comment]
Nevermind...

```
// https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/default-action-groups/
resource "elasticsearch_opendistro_role" "reader" {
  role_name   = "oslo_reader"
  description = "OSLO Reader Role"

  index_permissions {
    index_patterns  = ["oslo-*"]
    allowed_actions = ["get", "read", "search"]
  }
}

resource "elasticsearch_opendistro_user" "reader" {
  username = "oslo-reader"
  password = var.password
}

resource "elasticsearch_opendistro_roles_mapping" "reader" {
  role_name   = elasticsearch_opendistro_role.reader.id
  description = "OSLO Reader Role"
  users       = [elasticsearch_opendistro_user.reader.id]
}
```
