### ISSUE TITLE
How to create index-patterns using elasticsearch_kibana_object resource

### ISSUE THREAD

**Issue by Shubydo** [phillbaker/terraform-provider-elasticsearch#87]
I'm trying to figure out how to create an index pattern using the `elasticsearch_kibana_object` resource, but keep getting errors. Currently using ES 7.7

```hcl
resource "elasticsearch_kibana_object" "cloudwatch_index_pattern" {
  body =  file("${path.module}/index_patterns/cloudwatch.json")
}
```

Below are the configurations I have tried for `cloudwatch.json`.

`cloudwatch.json` using ES7 format.
```json
[
    {
        "id": "index-pattern:cloudwatch",
        "type": "index-pattern",
        "attributes": {
            "title": "cloudwatch-*",
            "timeFieldName": "timestamp"
        }
    }
]
```
This causes the following error: `Error: rpc error: code = Unavailable desc = transport is closing`

`cloudwatch.json` using ES6 format.
```json
[
    {
        "_id": "index-pattern:cloudwatch",
        "_type": "index-pattern",
        "_source": {
            "title": "cloudwatch-*",
            "timeFieldName": "timestamp"
        }
    }
]
```
This causes the following error: `Error: elastic: Error 400 (Bad Request): mapping set to strict, dynamic introduction of [timeFieldName] within [_doc] is not allowed [type=strict_dynamic_mapping_exception]`

Any help or advice on this issue would be greatly appreciated.

**Comment by bjfish25** [comment]
The kibana saved object doesn't strictly take es6/es7 exported object format. Something like this should work though for a simple index pattern:

```
[{
	"_id": "index-pattern:cloudwatch",
	"_type": "doc",
	"_source": {
		"type": "index-pattern",
		"index-pattern": {
			"title": "cloudwatch-*",
			"timeFieldName": "timestamp"
		}
	}
}]
```

**Comment by phillbaker** [comment]
Potentially related: #22 & #70.

**Comment by Shubydo** [comment]
Closing. Was able to use @bjfish25 's example to create the index pattern

**Comment by lakshayarora476** [comment]
When I use the provider as below

`terraform {
  required_providers {
    elasticsearch = {
      source = "phillbaker/elasticsearch"
      version = "2.0.7"
    }
  }
}

provider "elasticsearch" {
#configuration options
}`

And run terraform init and terraform plan, I get error "Error: Missing required argument
│ 
│ The argument "url" is required, but was not set", though I specified the url in the provider block above.
