### ISSUE TITLE
The "elasticsearch_index_template" resource is using the legacy `/_template` API endpoint

### ISSUE THREAD

**Issue by haywoood** [phillbaker/terraform-provider-elasticsearch#88]
Not sure there is going to be any action needed from this library, but figured I'd link the two issues. 

https://github.com/olivere/elastic/issues/1393

I was trying to create this resource:

```
resource "elasticsearch_index_template" "logs-haywood4-template" {
  name = "logs-haywood4-template"
  body = <<-EOF
{
  "index_patterns": ["logs-haywood4-*"],
  "data_stream": {},
  "composed_of": ["logs-mappings"],
  "template": {
    "settings": {
      "index.lifecycle.name": "logs-epr-ilm",
      "index.codec": "best_compression",
      "index.query.default_field": ["message"]
    }
  }
}
EOF
}
```

But it failed to apply because of a 400 error from Elasticsearch. Downstream, the legacy `/_template` endpoint is being used instead of the new `/_index_template` endpoint.

**Comment by ruflin** [comment]
@haywoood The only work around I can think of at the moment, is to just not load a template and use the default one. I would hope this works. At the same time I do not want to consume more time of you for this as what you created works and is the most important part here.

We can still iterate later on this again and improve it!

**Comment by haywoood** [comment]
@ruflin yea, the only problem is that the default ILM policy won't work for us, neither is missing the no hot/warm default that will arrive in 7.10.

**Comment by ruflin** [comment]
@haywoood Please ignore me on this thread, I commented on the wrong issue 🤦‍♂️

**Comment by phillbaker** [comment]
I'd suggest contributing a PR upstream for this, which will then need to be pulled into this provider.

It looks like this endpoint was added in ES7.8 - I'm not sure how we want to handle that in the provider, we're currently only differentiating based on major versions of ES which tie to major versions of the client.

**Comment by z0rc** [comment]
In addition to new endpoint it would nice to have support of "component templates" which is also part of ES 7.8. Tracked at https://github.com/olivere/elastic/issues/1388

> It looks like this endpoint was added in ES7.8 - I'm not sure how we want to handle that in the provider, we're currently only differentiating based on major versions of ES which tie to major versions of the client.

I'd suggest introducing new resources for component templates and index templates.

**Comment by haywoood** [comment]
> introducing new resources for component templates and index templates

++

**Comment by phillbaker** [comment]
Going to close this as composable templates were added in #120. Component templates support is being tracked upstream in https://github.com/olivere/elastic/issues/1414, a new issue can be opened to support that when upstream support is added.
