### ISSUE TITLE
roles and role mappings generate 403s

### ISSUE THREAD

**Issue by ngamber** [phillbaker/terraform-provider-elasticsearch#91]
Trying to create/update roles and mappings but get 403s back. Using AWS ES 7.7 (latest) and assuming an IAM role mapped to the all_access role, equivalent direct rest API calls work fine.  Using 1.4.3 of this provider, other resources such as templates/state policies also work. This also occurs with the test role provided here: 

https://github.com/phillbaker/terraform-provider-elasticsearch/blob/v1.4.3/es/resource_elasticsearch_opendistro_role_test.go#L237-L261

`elasticsearch_opendistro_role.test: Creating...`

`Error: error creating role mapping: elastic: Error 403 (Forbidden): []`

 ` on roles.tf line 44, in resource "elasticsearch_opendistro_role" "test":`
  `44: resource "elasticsearch_opendistro_role" "test" {`

**Comment by ngamber** [comment]
I think the 403 was unrelated, I get a 400 now that I've fixed our roles. Wondering if this is the problem (note the following comma added to each element (indices_all,*, etc.): 

```  # elasticsearch_opendistro_role.test will be created
  + resource "elasticsearch_opendistro_role" "test" {
      + cluster_permissions = [
          + "cluster:admin/ingest/pipeline/get",
          + "cluster:admin/ingest/pipeline/put",
          + "cluster_composite_ops",
          + "cluster_monitor",
          + "indices:admin/template/get",
          + "indices:admin/template/put",
        ]
      + description         = "Log collector service role"
      + id                  = (known after apply)
      + role_name           = "test"

      + index_permissions {
          + allowed_actions = [
              + "indices_all",
            ]
          + fls             = []
          + index_patterns  = [
              + "*",
            ]
          + masked_fields   = []
        }

      + tenant_permissions {}
} 



````

Adding those extra commas to a request to the API manually fails with a "could not parse content of request error.

**Comment by phillbaker** [comment]
Hello, I'm not quite following the issue. Can you include a formatted terraform example and the output of a terraform apply with the `TF_LOG=INFO` environmental variable set?

**Comment by phillbaker** [comment]
Hi @ngamber  unfortunately without further details, a test case or a way to reproduce this, this bug report isn't actionable. Please provide any updates you can.

**Comment by ngamber** [comment]
Sorry about that, we switched to using a script via local-exec to create these resources as a workaround. If I get a chance I'll try this again and report back.

**Comment by phillbaker** [comment]
Closing for now, please reopen if this can be reproduced via a terraform resource and shared.
