### ISSUE TITLE
Extensions: machine, user, and role management

### ISSUE THREAD

**Issue by jonathan-johnston** [phillbaker/terraform-provider-elasticsearch#94]
@phillbaker We're looking to configure more of our ES infrastructure declaratively, with willingness to contribute features that help us get closer to 100%. This Terraform provider has a lot of the features that we need and feels to me like it could be naturally extended to handle configuration and management of ES cluster machines, users, and roles. As the maintainer, I would love to get your opinion on whether this provider is the right place for these responsibilities.

To be more specific about what I think this Terraform provider could handle:

- Machine provisioning (per hosting platform; we use elastic.co)
- Machine configuration (ex. hot & warm labels)
- Kibana user CRUD operations (primarily for managing user creation and deletion)
- Kibana role CRUD operations

**Comment by phillbaker** [comment]
👋 hello @jonathan-johnston, thanks for asking! I certainly see room to improve the management of kibana and other resources that live in an ES cluster (your latter two points), PRs for those would be welcome, and would be happy to talk through good ways to structure them.

Given the many ways to provision and configure an ES cluster, I'd like to keep that outside of this provider. A user of this provider built one for ECE, see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/30 (https://github.com/Ascendon/terraform-provider-ece).

One downside of this split is that some aspects that one would expect to work between providers don't work, see https://github.com/phillbaker/terraform-provider-elasticsearch/issues/63.

**Comment by phillbaker** [comment]
@jonathan-johnston when you refer to "kibana users" are you referring to the XPack managed security users or something else? (The XPack users are already supported by this provider.)

**Comment by jonathan-johnston** [comment]
@phillbaker Thanks for the detailed information! I hadn't noticed `Ascendon/terraform-provider-ece` but that is exactly what I need for machine management. And it turns out I am indeed referring to XPack but didn't know user and role management was built on it. Thanks for the clarification!

I'll try hooking your provider up to our Terraform config and can swing back around with any extensions we implement (most likely talking details with you first) along the lines of those initial points I posted (excluding machine management, of course). I'm satisfied. Feel free to close this issue!

**Comment by phillbaker** [comment]
Sounds good, any feedback on issues with this provider would also be appreciated!
