### ISSUE TITLE
Terraform - provider configuration

### ISSUE THREAD

**Issue by serenacor** [phillbaker/terraform-provider-elasticsearch#97]
I am using  "0.13.4" terraform version with the follow config 
required_providers {
    elasticsearch = {
      source  = "phillbaker/elasticsearch"
      version = "1.4.4"
    }
  }

provider "elasticsearch" {
  url = "http://127.0.0.1:9200"
}

and used the resource as indicate in the documentation but after the init command I can see this issue:

> - Using previously-installed hashicorp/template v2.2.0
> - Finding latest version of hashicorp/elasticsearch...
> 
> Error: Failed to install provider
> 
> Error while installing hashicorp/elasticsearch: provider registry
> registry.terraform.io does not have a provider named
> registry.terraform.io/hashicorp/elasticsearch

**Comment by phillbaker** [comment]
Just following up here, what was the resolution?

**Comment by vijay-singh** [comment]
What was the resolution here? I'm seeing the same issue
