### ISSUE TITLE
Watches with basic auth trigger replacement due to password redaction

### ISSUE THREAD

**Issue by tophercullen** [phillbaker/terraform-provider-elasticsearch#99]
At least with elastic cloud, elasticsearch redacts basic auth passwords returned by the get watch api. Instead of the real password, it is always "::es_redacted::". This causes large quantities of low quality output in plans and re-applies all watches that require passwords. 

This seems like a case where we need to somehow ignore this specific field in templates, or check it against the existing state rather than what is returned by the API.

**Comment by tophercullen** [comment]
Short after opening the issue, I found a simple workaround for this: basic auth headers. This is all the auth input is doing anyway. Changing this

```
"headers": {},
"auth": {
    "basic": {
        "username": "elastic",
        "password": "<plain text>"
     }
}
```

to this

```
"headers": {
          "Authorization": "Basic <base64encoded auth string>"
        }
```

Elasticsearch doesn't redact the headers, so provider can just work as is.

Rather than changing the provider, could this be added to the usage information/examples?

**Comment by phillbaker** [comment]
> could this be added to the usage information/examples?

Yes please! A PR would be great! I'm not sure we have xpack watches documented yet (https://github.com/phillbaker/terraform-provider-elasticsearch/tree/master/docs/resources), but the contribution would be welcome!
